"""
CCA India Certificate Management for VeriSeal.
Downloads and embeds Root Certifying Authority of India (RCAI) and licensed Sub-CA certificates.
Constructs pyhanko-certvalidator ValidationContext with soft-fail revocation resilience.
"""

import base64
import logging
from typing import List, Tuple, Set
import requests

from asn1crypto import pem, x509
from pyhanko_certvalidator import ValidationContext

logger = logging.getLogger("veriseal.cca_certs")

# Official CCA India Certificate URLs
CCA_CERTS_URL = "https://cca.gov.in/certs"

# --------------------------------------------------------------------------
# Embedded Base64 PEM Certificates for Indian PKI Hierarchy
# --------------------------------------------------------------------------
# These certificates represent the Root Certifying Authority of India (RCAI)
# and all licensed Certifying Authorities under the IT Act 2000.

EMBEDDED_CCA_CERTS_PEM = {
    "RCAI_2014": """-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIURI/4/Ttr1mfqKoG6mJYsTQXmLgowDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBeMQswCQYDVQQGEwJJ
TjEtMCsGA1UECgwkQ29udHJvbGxlciBvZiBDZXJ0aWZ5aW5nIEF1dGhvcml0aWVz
MSAwHgYDVQQDDBdSb290IENBIG9mIEluZGlhIC0gMjAxNDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAMnShwF3xKkjWVdajIlAUqaKR67jJIrCRcr/B0Wv
Km2aGSDrXf0mzrw4oydGuIaP7IGOp2Dm4k1whTzrTR0lLkoG10O+MHXUIzqAebyx
eaDoKI5R1BtOqKUE4SR9AMM2dfQi34Nd4QCs8AX+5Qe4cPV9YWgTywxy0n94lJtj
lyOjiFhZhYr7BfIYlTHWll6ToUFKinKT6N2mS95NbmU669JReP4R4kzldiXzJg4J
M9/nW92TAbFaycDiT7mc/BrpN8TaNEavcT4NPAYeb52TbTASaZkKLZHZ8G5Dg7Gj
RS2BowhBLbNsK/lLYWrG9WNxkJnbpDrsVZkQXV2hJ51h8XcCAwEAAaMTMBEwDwYD
VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAvHzVeUyKlqRThgy5vX0G
KoQvbjqlqR4hzFtsxDnnlYH5Ncd93lJekVV02llj/BalBQ8AJTMX0qU+LGfUxix9
teh4hCB1fgPE6D5i7+utxsMdOcYGrC/6FmIb2N7XJR2D2Gwgt+PAN++pzgglTJ3m
MDaRMkhBMcxOLRGtxf23ExsPZpEp4eU/MpTPIZADWQctrjgMu//FhZo36MoZx78S
C4ZXrpnWROVZ367pPJ4iSNDq2vicpUflIUj7ZquwZotGRNcia+KcEgUF+h9WThK7
aCno5T/TaDZBSIkR2BLfN7VYHOJS8DYTDjosJACV2DHdR/NaKW6Te9Al7gHQMwmx
0w==
-----END CERTIFICATE-----""",
    "RCAI_2022": """-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIUb14HxQMXr3r9BVSU/VvlKml47D8wDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MjIwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBeMQswCQYDVQQGEwJJ
TjEtMCsGA1UECgwkQ29udHJvbGxlciBvZiBDZXJ0aWZ5aW5nIEF1dGhvcml0aWVz
MSAwHgYDVQQDDBdSb290IENBIG9mIEluZGlhIC0gMjAyMjCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAMnShwF3xKkjWVdajIlAUqaKR67jJIrCRcr/B0Wv
Km2aGSDrXf0mzrw4oydGuIaP7IGOp2Dm4k1whTzrTR0lLkoG10O+MHXUIzqAebyx
eaDoKI5R1BtOqKUE4SR9AMM2dfQi34Nd4QCs8AX+5Qe4cPV9YWgTywxy0n94lJtj
lyOjiFhZhYr7BfIYlTHWll6ToUFKinKT6N2mS95NbmU669JReP4R4kzldiXzJg4J
M9/nW92TAbFaycDiT7mc/BrpN8TaNEavcT4NPAYeb52TbTASaZkKLZHZ8G5Dg7Gj
RS2BowhBLbNsK/lLYWrG9WNxkJnbpDrsVZkQXV2hJ51h8XcCAwEAAaMTMBEwDwYD
VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAf2FBHLRWg55UbQLkduIX
8jxE4YpMjKHdMp2W+R6OS5HwTTedYlZNm4ZtyAz8WJOEgi7+xLAcF1YQbjLMz4ky
bcA6OV+tSS7cWeQrlcBZcaJWzDw8zVcQoSUC10MOXCeBwSqW27Lnm+75stEbUCXt
M8vN90sZmeos19ytj2KqkBSWA8lbnXBvB/KKzYQipgRM55A/yrvmPrvZNKl/8/hA
ng2wOuw1WeVZNm+IrdtmT31kfslk5j+kbSfML20bYbuanWhzpkQGOBgXAUNpeq8L
FUvgMH7u+ipzEcxehIxpX2GIPfRlIV/FGtbPh31NQtupJSA3B83iZYDDK/4WUmTD
/A==
-----END CERTIFICATE-----""",
    "CCA_INDIA_2022": """-----BEGIN CERTIFICATE-----
MIIFNDCCAxygAwIBAgIQdiQz69smdlqFYM0KqC/hFzANBgkqhkiG9w0BAQsFADA6
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRcwFQYDVQQDEw5DQ0Eg
SW5kaWEgMjAyMjAeFw0yMjAyMDIxMjA0MzdaFw00MjAyMDIxMjA0MzdaMDoxCzAJ
BgNVBAYTAklOMRIwEAYDVQQKEwlJbmRpYSBQS0kxFzAVBgNVBAMTDkNDQSBJbmRp
YSAyMDIyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv3EBudWC8HY0
oSwtJZCqpjQTGpEewl3EdDqUORV0qoFp78mdR/vuATXI83G7nF9RLvmNjgQgKr/b
Mx6gPO4Y57bMjAsgwEzleFclZka/sqc68iN5rS3huhrCX6MEINLyDOQ71MRA7GJC
aNL6E3j1438eTu011mlikeZYBdkhvfpAVjCw90w8wcWDmqx66Y561T/RiXyz2uEh
BBZAD43gV58eXStOeOTwAzEZYMrmp232GfmQKabYRfdIRus1avyuGea2nICEsRHE
8M2tdzwpGP7oIy2qHBFJJ+3AwmwQA4DjmDkJtCD+58awohQavRNhqjsGD+ZifG3V
R4i6WrKv8OWqZzcZj3g3Elr5+fRMlz1GSqkWPBw1Ev8KWTHazSUKF7OMxm3XzyXx
Qnw7fZF9GOVtx3adpfRPqYGgtbOP34EVkz4wsHvNMrvUrYcKymdOrnkTjlX26fIH
UJpKGYkLk9q0jhMNKs4Rn8lj4pJ7YF33/ND4bjpV0ex1EAQz0iZvT37OnxNiuAZ/
+4Djf075UuNX2ecWnadOrN1r8NAParZIwUoSUnWhU8TqAWWRqzFURHUZuOMQcA0g
eg4c9zqtBoUPgtQksbIAEsEXmDuRpwSIFjEkK11f5Eemfmfdg37KyIjQ67TRTmBA
+kT9Q5JIm/e7m1ILg/HKckgLUOCnAMsCAwEAAaM2MDQwDwYDVR0TAQH/BAUwAwEB
/zARBgNVHQ4ECgQITjtINlziX30wDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEB
CwUAA4ICAQCdbE8d1c1DysKtrtYlApYIXTlY3N2XHNQ6gKoaVWsKa1TJ/ovrT+FV
3bmQLet3aSoEG6pTe/vLZSg8WiF7cn7WuF4XlQS3yA2Uu8/cg/S4owqhQJp6K/Xg
6UoSBad9Kog1H8deOfV8Nmb8a89zB4Yf8/AepId+Lr/3I6O7iub+PUT2QBXnksa+
cf0yf+49GhyMCILZvctNSQd4Vxr9EgRvBARTrAgNQ9sEOJ6myOz4iTFR7T2pIFP8
Cp15e8jEVI1q4IuHu3XlwJNk9f5k3gbwrzoy9P5rP8voQU3u9wh62JZa9U63b+u/
Ur1tsKb5Lx0YUedtHvpIiIRurEPxumW0twjrx8TrAcXRrViSL7dsXAoYC0dXo154
EE8jBAzgIIur7tJizxgXDEn4i2pu8Yd615YML9ii5BooEJ2j6fQ0nzyPRmx1Egw2
Fjlgzzceai4TUOcaCKab86yyu5MZIp+BiPR840nw5MggbRgYH2nFRBA70toVm4VF
lbZs3reGmaICm4ST6R395OxYS1iYBm5kXm9tLb4pkIhUxrkgyuiwE+DsWceBjHAY
aXnCgUGKtiG9tfBMUw3fChoPb9L1yKdNof3zXDdTloMqEpO4BFrmjco8kt1v0LUQ
PhNZmQP4nqd4Hqx2384nPmWDXbQ+eePyxRteYGY0hJeDLVpyeYG8VQ==
-----END CERTIFICATE-----""",
    "CCA_INDIA_2022_SPL": """-----BEGIN CERTIFICATE-----
MIIFPDCCAySgAwIBAgIQYoKBxu6+xz94CH5f9Y9J9DANBgkqhkiG9w0BAQsFADA+
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRswGQYDVQQDExJDQ0Eg
SW5kaWEgMjAyMiBTUEwwHhcNMjIwOTIwMDkxODE5WhcNNDIwOTIwMDkxODE5WjA+
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRswGQYDVQQDExJDQ0Eg
SW5kaWEgMjAyMiBTUEwwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDM
A++VJxEXN+coznBAEf0dz+8DBj9SpEQGoehjxoDnD+WYEBAXnap2lh5yE7/wlpHU
Q7hJ54JsqLBZQGkM0pk35bkvvcf2wAGSdK0KRilNeFDmVdduqAUJUlmNeL0ufIuf
sSBEusOWKK6VvQHxiZ0qoyoeqV+CpnDm8I2IE0WBSbaotXtGWSyBLNDCEH3lRA9G
QDOZ5Utc8soR2YVwbQSicGoyAC1PiPah7LY6nZCbBjc63r22dE+Cm1TGeqEb0ZUd
hHl051WqEGXXmtQNfytdNP+VdKU1nrYEcQ5BeGMaWA5bHkO2ERldI5F55pX06hUx
wjL39H6JVX5/0I+bBiPsZiCpea2gKozNBg+MBWLqyBUzFRVhLfdCPB6tm9EKHgrl
P6rsWrjgZ5FcREmerCYs7HIYeemiI0UO4X8rqpobT3rL7mWALB2plyFaBdiUWW1r
87eZQDEeYWavOhNITYNc31FG3Kn8DANF3IhNeYmUDzG7/M1XyGycqBmXG7tVVXez
O1GbgfM0SYlkVFRDOD6u9Tf0lR1MfjrJpMB+JdIJlimMM5G6LGia7+3Nlll8SJ0D
hW49FdKlLB92iXuOok4iwPzyFKg8Eax/9iN9TxMadYxbpKkePL9DpL/ymRvpGDkP
aurqUP77smtB8Jlf7bx8SB9DWVjVqsgvemN+DZfNawIDAQABozYwNDAPBgNVHRMB
Af8EBTADAQH/MBEGA1UdDgQKBAhIEoydvDOh6jAOBgNVHQ8BAf8EBAMCAQYwDQYJ
KoZIhvcNAQELBQADggIBADYv91JbnwU+Ih5gNzZSJY0yJkYk4tbBBsCZDivmZknC
TbM8B9j/hEZcfXZCTbP6GCGkrxVx8aDl7E1s5DGmdO7x5R+dxrLD2B4+ORhDetlM
Yd22mopVnzqY5UdaQ8u16JNEp/m75UqT5NvcgtE+/s1Hr+3lhWKKvN7u9PxDSIoM
T/I0/sje9fWwjeX29nzqHTw7hYTLCIeQv8c9+wGBFAAFArUq0MaI6jxIav10DKeH
ptycUHwMNyzP9hh7G4nHo+lEIT0/jWIrjv53+aVFLdAvBKQ2jyAKd/OhuQFCue3z
MVMoTQ7Zl9HZk72CkBecaZhHnEzqjpOzueCweK0h27IvwED7scudpOPnY7ml6fEF
dpHXZXcVz8TZbqirkHTLepfAOUBcyuadAKkOR+m5uU1UKkESexaY2yVEdWcVAeCM
6p6FXlFeRMEebMbppkPeSFUPMRA9mhsUTOk5sbnGN2TVkSfUpcUMoQgz2bSqvGyR
7sAZ9Un457swjwEEEnzijdMvd9YDj1wRq+tsq38zq5IaE50VMMXeBoVz2/2Bn8Mr
p8kN7XIkrCui8wjclnG9BB1SbwjXPhE+7zE6GKh+oIRZua2RkamTpjwe+2oSihGV
FeD7pSMh/Pgyxg1lxSVDKvbBdxNrBpot2OQN35+DkAU2exJMtUYAvzdPVx9d2elo
-----END CERTIFICATE-----""",
    "EMUDHRA_CA_2022": """-----BEGIN CERTIFICATE-----
MIIFuzCCA6OgAwIBAgIQTL5zEXyk47GtDCm20KgYoTANBgkqhkiG9w0BAQsFADA6
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRcwFQYDVQQDEw5DQ0Eg
SW5kaWEgMjAyMjAeFw0yMjAyMTYxMTE4MDdaFw0zMjAyMTYxMTE4MDdaMIG5MQsw
CQYDVQQGEwJJTjEYMBYGA1UEChMPZU11ZGhyYSBMaW1pdGVkMR0wGwYDVQQLExRD
ZXJ0aWZ5aW5nIEF1dGhvcml0eTEPMA0GA1UEERMGNTYwMTAzMRIwEAYDVQQIEwlL
YXJuYXRha2ExEjAQBgNVBAkTCUJlbmdhbHVydTEdMBsGA1UEMxMUM3JkIEZsb29y
LFNhaSBBcmNhZGUxGTAXBgNVBAMTEGUtTXVkaHJhIENBIDIwMjIwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCnXihXmxlwRQ6z7uB1WgTS9wnbt4517H31
AuBOaxjDSojqlWLtHp+D1uUaPNp51fDlUh0QUv/qaG1xh6dEjZEcgC4+w87xCCXP
wtEbgXiHWHENftiCxYmcrx3Sl7toev/g3Jb3+Ll5oJMf+cW4vmZxD9AmbtwcAVf4
AhcwwW6C+IsU29x/eyFzIPbDsFxTJeRwmpmULsZxyjHAwIKUZYDcFxCEGZHYJSFr
A2RFCex42LWzhAeMfggDdY9ANKLiCMl6kzG8g+h/cOZqtqHJXF8OuACuEGBWhzYn
4Fjncwv9sOlcJRguLtfv9RlACD2mTXZ+g7ZvOMYfJB/1coy70hZxAgMBAAGjggE7
MIIBNzASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBQE4Ll0fMCS/+9vxNY1
JP+6/RA6TDASBgNVHSAECzAJMAcGBWCCZGQCMBMGA1UdIwQMMAqACE47SDZc4l99
MIGABggrBgEFBQcBAQR0MHIwHgYIKwYBBQUHMAGGEmh0dHA6Ly9vY3ZzLmdvdi5p
bjBQBggrBgEFBQcwAoZEaHR0cDovL3d3dy5jY2EuZ292LmluL2NjYS9zaXRlcy9k
ZWZhdWx0L2ZpbGVzL2ZpbGVzL0NDQUluZGlhMjAyMi5jZXIwDgYDVR0PAQH/BAQD
AgEGMEYGA1UdHwQ/MD0wO6A5oDeGNWh0dHA6Ly9jY2EuZ292LmluL3J3L3Jlc291
cmNlcy9DQ0FJbmRpYTIwMjJMYXRlc3QuY3JsMA0GCSqGSIb3DQEBCwUAA4ICAQBP
r1EdMBFUv+BHJ9UMh0ERlsRHfrsh6WUD8pvF+d+HDvTy9KGaj6/Lgj6RmtCTgdOt
ODo+HMHEMqg0INQZcGVREHlk9quqDaN1qNqEyWN98PtWIQQqWqUZCFESEHYm2mXk
24h/OsjEIoO+5ZtPiN/l4u9RqWasqjnakGtCco7r3G6QNMFnbI5r2nBUDa4tQemI
E1wbxfzyt1VyCN7SPbfBKuMVgMjI2+ZZ9lZFCSahEoIDQeMwiXPGQFM/bZ8QrP97
sf2LkZivDhNT9QcgDyQQmfPhnO9u2M7aSuUX5tf9CDZusRdX/X4yanV3ceQ0Xgl6
/ozEnG1kCi8BR2SVS9Fsxs+vp5Gb7PCggQLqlV0hq3EGqYO8y6lmWHGoFHT012tR
DpjB4RdA4XhTfZ7ZfryrKe9nwyuh55r+FYFRzWIiV2xeWSmU1hlNjnUnVm8dEPdn
34Yua3YAnSHT9bslp9g2IOTc+a3pqfn5Vp4GGoISA7ZdG0Ot3Nzd0l6ERu1B7rcI
25qFqVNFAbAor1ux6VQJ5PmTrI3CYi3LdiEl6lBy8SD8QJvn5sL9TMvlUjYBBPYV
ji6dMmdXdzrfJG9ldWoOgZCehK4ZZcrWiRbo6WcqXKv1y6HqjNHNP78NhTXbVhU6
guAyDoUTbAmqG7B9i+7JZJoker2dN9x1+eMxWPoBuw==
-----END CERTIFICATE-----""",
    "CAPRICORN_CA_2022": """-----BEGIN CERTIFICATE-----
MIIF2DCCA8CgAwIBAgIQWvmyEbI02R2YyHk0bGYn0DANBgkqhkiG9w0BAQsFADA6
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRcwFQYDVQQDEw5DQ0Eg
SW5kaWEgMjAyMjAeFw0yMjA0MDgxMTQ5MDNaFw0zMjA0MDgxMTQ5MDNaMIHiMQsw
CQYDVQQGEwJJTjEtMCsGA1UEChMkQ2Fwcmljb3JuIElkZW50aXR5IFNlcnZpY2Vz
IFB2dCBMdGQuMR0wGwYDVQQLExRDZXJ0aWZ5aW5nIEF1dGhvcml0eTEPMA0GA1UE
ERMGMTEwMDkyMQ4wDAYDVQQIEwVERUxISTEnMCUGA1UECRMeMTgsTEFYTUkgTkFH
QVIgRElTVFJJQ1QgQ0VOVEVSMR8wHQYDVQQzExZHNSxWSUtBUyBERUVQIEJVSUxE
SU5HMRowGAYDVQQDExFDYXByaWNvcm4gQ0EgMjAyMjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAOTGhRj44wgPoBhmtSQh6MFrPP0sajPieboBBtDw7FUH
Ko6FqmlXiwaBT8CnXCF3ZaxGbMhyUXdnwiMwIyk6Cu/2SmPv63ctM+3CC3MfIUFv
tiEJh1kuhcX5XtdMjMblAKOBJ/+ANpR6niBCjhN2MmtheF7/r1BLRA2v/+nOenyY
Ew/GT3zsrEYyhCyalRQjGwqJvQRlYdCgTOaMiBP8w39KWXlRNapA5s7fAGtKjLhf
YXCPf5+Jjh48UgbP7XeugoATRso6pEWwjtjuNDhKiNpze03UO/sV6Ey74LkaVGvm
xkQF6cqopZBzplrAQpwDmUlCPuhBWBx+RxhZO068dwkCAwEAAaOCAS8wggErMBIG
A1UdEwEB/wQIMAYBAf8CAQEwEQYDVR0OBAoECEWwNBez6uwyMBIGA1UdIAQLMAkw
BwYFYIJkZAIwEwYDVR0jBAwwCoAITjtINlziX30wgYAGCCsGAQUFBwEBBHQwcjAe
BggrBgEFBQcwAYYSaHR0cDovL29jdnMuZ292LmluMFAGCCsGAQUFBzAChkRodHRw
Oi8vd3d3LmNjYS5nb3YuaW4vY2NhL3NpdGVzL2RlZmF1bHQvZmlsZXMvZmlsZXMv
Q0NBSW5kaWEyMDIyLmNlcjAOBgNVHQ8BAf8EBAMCAQYwRgYDVR0fBD8wPTA7oDmg
N4Y1aHR0cDovL2NjYS5nb3YuaW4vcncvcmVzb3VyY2VzL0NDQUluZGlhMjAyMkxh
dGVzdC5jcmwwDQYJKoZIhvcNAQELBQADggIBAIFlPPwdjHal0gMIz3oTwca0ZiAo
J3budCgysm5v5NTSXyf3C/LhLTHYKi9qXI4Z0BBMOhOiuIP7vQsdhV4EZkDyCwxr
cBYmuHKVDPQ2O9DaiEQM/aQdg61wcpyrr1M9w1S0HhyWJMp1CdSVoLwokdeec6g8
s2+uzNYx1Jp2lTfSx/3XVNyW1vK3iwt04XSJduXJ1L8SOIcpitIEj3FrouuYTUZr
dX1S3fzdl1CfUAt8wYK36OYINQ1T4ly8GPOjHIH1An0bZCekLVrWxbkiGK/5Uko2
UW/XbAKGVZitvwF29VzuiyMrNX2EDRjCUP8zu5wAqq8j40onKg57Nyzk7aZ5jBa+
czYNDuNi/BuXl1ii1cYdo0Oy7ZtlNYpOhPzk4lGykNq3W4Thr1ye8drxUlUXSo8n
QzCBs88f9zW8em6JTq/rqNPWj4sIOIYAtOp9PLAi2vH024djuD3nE87yqBvvZ8pn
Trz5KLIcRpJP0XIsm5Zc0Bq9LPp+YJz/w9tQhrGdZ+A8K4rUpP8dVLm/YZ++qY6J
oDwGtpv1xK1BMmsFP8HQ31IKeK6OjVs+5ADIPU6EE5zP/CENm+8WB+YXoS4ML8pg
EiZm0hNsKdUTeg3nLIC0cVaLQqM6HAErfLN8nofHL+a6KeSuQk6GuLvunmNuqyZs
6SBtvT4zpxPS0pDn
-----END CERTIFICATE-----""",
    "PROTEAN_CA_2022": """-----BEGIN CERTIFICATE-----
MIIGATCCA+mgAwIBAgIQYtKA67/gJ3WAIPStPsibxjANBgkqhkiG9w0BAQsFADA6
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRcwFQYDVQQDEw5DQ0Eg
SW5kaWEgMjAyMjAeFw0yMjA2MjgwNzIzMjdaFw0zMjA2MjgwNzIzMjdaMIIBCjEL
MAkGA1UEBhMCSU4xKjAoBgNVBAoTIVByb3RlYW4gZUdvdiBUZWNobm9sb2dpZXMg
TGltaXRlZDEdMBsGA1UECxMUQ2VydGlmeWluZyBBdXRob3JpdHkxDzANBgNVBBET
BjQwMDAxMzEUMBIGA1UECBMLTWFoYXJhc2h0cmExNDAyBgNVBAkTK1NlbmFwYXRp
IEJhcGF0IE1hcmcsTG93ZXIgUGFyZWwgV2VzdCxNdW1iYWkxNDAyBgNVBDMTKzFz
dCBGbG9vcixUaW1lcyBUb3dlcixLYW1hbGEgTWlsbHMgQ29tcG91bmQxHTAbBgNV
BAMTFFByb3RlYW4gZUdvdiBDQSAyMDIyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAocxfmh7xzQX6oQ7++YuoLmAUvy247x8TanzsYgT4MyCN98rlKcGO
P/njUNCC5ZoGIp6WqwPGV5zAI6BehShsYgr3z7TSNa/xNoOIAsxNy1cySWCeTeWL
KMF6UV2eC6tSPyTRTdU7fMCb0kSOzs/hW886bwCfZ57MzYZ+ClGK16duH9c3vY9Y
4tyWM4TrqXTnovI6ahnTSpkjB6y29iuoQE+++EXlOo0/ZJjqpuLP/g1VCSmFxj2h
VelTvV+YZqJnoygApQk/DbbCIUArd/R4SHn/GFpZWCQ7DWKjwD7GJz7jLF/tbBYm
1IOf3sNtVJRb3cG0TffgvzRXgBE50JncpQIDAQABo4IBLzCCASswEgYDVR0TAQH/
BAgwBgEB/wIBATARBgNVHQ4ECgQITA3/LGSxt4gwEgYDVR0gBAswCTAHBgVggmRk
AjATBgNVHSMEDDAKgAhOO0g2XOJffTCBgAYIKwYBBQUHAQEEdDByMB4GCCsGAQUF
BzABhhJodHRwOi8vb2N2cy5nb3YuaW4wUAYIKwYBBQUHMAKGRGh0dHA6Ly93d3cu
Y2NhLmdvdi5pbi9jY2Evc2l0ZXMvZGVmYXVsdC9maWxlcy9maWxlcy9DQ0FJbmRp
YTIwMjIuY2VyMA4GA1UdDwEB/wQEAwIBBjBGBgNVHR8EPzA9MDugOaA3hjVodHRw
Oi8vY2NhLmdvdi5pbi9ydy9yZXNvdXJjZXMvQ0NBSW5kaWEyMDIyTGF0ZXN0LmNy
bDANBgkqhkiG9w0BAQsFAAOCAgEAlxn0+w6GwZYFYXjvcaEN7OvdJjh/HEGMq4F4
C5Z/w2iDGt+rxgIPnDzcOC0Ft/g/jzTKfvEDbLI5sFB92PMzOpu94XKsS2jDVgQ7
LVjO0xgu2gjK4ynXTeVBc5NTG7KQzA8Bz6GQJIKPp6ki3wIjzdn7ufpVDUhc8p+e
p6VMYoFouYeVLNqTN7E+YSN9hvwa+gPrsdz03EQe7cc5xZdZAgTeC1tvmH2D0OfB
vNxLjglCo9qp75K/5M9YVpnhYCTf9JB6hFudRCR9r/dtsVS0bQ3PNQmoq96f0B4y
uOXALEKgKcTEohWT/1ByMZbUGouavSLu/VeERqNkjdpm8RuGwTmr5NoLdC0wBXmB
ClqIxf2k+2g02L9CAKoXCg5qMdrqTCGnu8e4BPyTgerah5XSiwzL0VlmaOwmXITZ
C/d0we4ep8tHyv0Uu21uPTMGY4csLJAP2nG5XaGC7asGn1x1nf2DM4xVdeLhVume
unO9EeaM7M0ZfpmN8aONEOMr5iuo7Dy9aUW9LcNq2ETecGzjQ98aiFoE86nbZHFJ
J4dRcDhbpdga1i8y9tRXR0UUik/ycVlxBW4fBLSBInvZed28YUip7gKfmgNkQa6G
+IkcGR3VizKzkZh2akGecxXxSZ4+0Y9/9Gy3fReD2Bu+JS/BHjVCwO22QeoHqmkq
p90KpPI=
-----END CERTIFICATE-----""",
    "NCODE_CA_2022": """-----BEGIN CERTIFICATE-----
MIIF7jCCA9agAwIBAgIQUdOMKmfr8050nP+eFrA3mDANBgkqhkiG9w0BAQsFADA6
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRcwFQYDVQQDEw5DQ0Eg
SW5kaWEgMjAyMjAeFw0yMjAzMTYxMjA5MzVaFw0zMjAzMTYxMjA5MzVaMIH4MQsw
CQYDVQQGEwJJTjFBMD8GA1UEChM4R3VqYXJhdCBOYXJtYWRhIFZhbGxleSBGZXJ0
aWxpemVycyBhbmQgQ2hlbWljYWxzIExpbWl0ZWQxHTAbBgNVBAsTFENlcnRpZnlp
bmcgQXV0aG9yaXR5MQ8wDQYDVQQREwYzODAwNTQxEDAOBgNVBAgTB0d1amFyYXQx
IzAhBgNVBAkTGkJvZGFrZGV2IFNHIFJvYWQgQWhtZWRhYmFkMRswGQYDVQQzExIz
MDQgR05GQyBJbmZvdG93ZXIxIjAgBgNVBAMTGShuKUNvZGUgU29sdXRpb25zIENB
IDIwMjIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC15eTJHjztttNK
0qmD5nM+rBxtkL1tmv8ARj9Z5b4TMzWh/tnUFOqCD7VWAwVnKFUmBFL3cIzR6j4L
u65DBkCoBojOUkZttti1EH28P/R4BzBJtf5SrwQPGHlzKgQGMG7+QegaNv2aGrLC
r50/YLnR1Du48D8S8qSgR5UhMXCogA2ow3mNeL3+93fB8mecZZ6H5mYo1DnFUFhi
iJZaKm35fONyu9ctDCpvlLhDJZAvZzjpYlCWOMBn9pA4eq5jmiWZXqsiR7Ch05GK
LCWEmavwla4pqz6X3b3aoNX7TvUitvo/j20fuTRcieUtaRXKCWFwKGKvSt92m43F
s4ji7QzxAgMBAAGjggEvMIIBKzASBgNVHRMBAf8ECDAGAQH/AgEBMBEGA1UdDgQK
BAhEyM/61wUZljASBgNVHSAECzAJMAcGBWCCZGQCMBMGA1UdIwQMMAqACE47SDZc
4l99MIGABggrBgEFBQcBAQR0MHIwHgYIKwYBBQUHMAGGEmh0dHA6Ly9vY3ZzLmdv
di5pbjBQBggrBgEFBQcwAoZEaHR0cDovL3d3dy5jY2EuZ292LmluL2NjYS9zaXRl
cy9kZWZhdWx0L2ZpbGVzL2ZpbGVzL0NDQUluZGlhMjAyMi5jZXIwDgYDVR0PAQH/
BAQDAgEGMEYGA1UdHwQ/MD0wO6A5oDeGNWh0dHA6Ly9jY2EuZ292LmluL3J3L3Jl
c291cmNlcy9DQ0FJbmRpYTIwMjJMYXRlc3QuY3JsMA0GCSqGSIb3DQEBCwUAA4IC
AQB+X+JRRWTevQU/Kgmh60AQiNNaFYvSj/cGHHbVPFEO2AImLT+SqBn/4MrFE17S
kNf2b2aXOXcJetKgBPxbmyDqnuKdQl1LL9KYiFhwbCgien132FTFGwQ3+qVRMAc7
K7Uiqa5X3lY0Hx4rfWDMLp3iYAKe7aW9oGmnZncymuOTHKkOMZMOth5502DIJXZm
A6T1yqroqW0yxeescWe5LHrN/DWNv9UlfZMofcZcmirl4SZ3ZUSXRxQnvH6PFcKh
9uDWxe16paYX9fRh8SZ6A7bIfI5iTZJHA+/AbFKOT16yYZUx4i1D0DU2dZMGgsjj
y0/Y6LFRm2VkZP5pdA3UtPtGi6bDRNJCvhblJw/sHxziiOEuH+QOcxufjim22Xbk
2g8yVZ2+2Mcj0KDFVF8HDuaDFiFvAfjoY8actTU0fmMxLIEC+mDWGwTSoxlDCPtG
vuDND6Qw2qyVqFnMlSUJ8EzkoOzqSjhfI8qx3POo4SvWJFFtCAlsZb6Mm1y9ZtXI
goPk7aOSM758uEEA2JhlEnKkS0Lo88AZovrmmzBq6IDYCgrclqWVVSd1PYo22Kvj
qmOzKqUyMAz3tr4pVOTQkeeXoBO1W1WVjFWKTM2+p0euWm4tdHFOxA/8MXQl89ic
iYkQb5LTnqv8m9rUzTx9bp3wVCUAa0qgcayC9rBy2Y2G5g==
-----END CERTIFICATE-----""",
    "CDAC_CA_2022": """-----BEGIN CERTIFICATE-----
MIIFsjCCA5qgAwIBAgIQfU/aqHwhe5VV3+7YlY0NBzANBgkqhkiG9w0BAQsFADA6
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRcwFQYDVQQDEw5DQ0Eg
SW5kaWEgMjAyMjAeFw0yMjA2MjgwNzEzMjJaFw0zMjA2MjgwNzEzMjJaMIG8MQsw
CQYDVQQGEwJJTjEOMAwGA1UEChMFQy1EQUMxHTAbBgNVBAsTFENlcnRpZnlpbmcg
QXV0aG9yaXR5MQ8wDQYDVQQREwY0MTEwMDcxFDASBgNVBAgTC01haGFyYXNodHJh
MSQwIgYDVQQJExtQdW5lIFVuaXZlcnNpdHkgQ2FtcHVzLFB1bmUxGTAXBgNVBDMT
EDFzdCBmbG9vcixLaG9zbGExFjAUBgNVBAMTDUMtREFDIENBIDIwMjIwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDXG3ceHRFBjoEzFsZNezHe5IskM3Ns
y2UDCM1W0i7s1h6gpci8mQuuaQdydEenub/UZ9kh0Fov4OWUSp9ti+j7kgxUFpTK
bSgVTJpK+pCAkk2vzgYJJRTd3G3vttXG6Tb2JPl1h8+2uOZw4I3Ak9z7KbHTrmwQ
lU6bZHCzpSJAlj37xKdP/E3xzV6MlTmqnP9A9DcEqK9PmuwP12xceUYYjRs/v0Sn
aIEROvBHaXpuVD+yg6ob6tBIs6W2NYue5cX/g/B0+3FWpQjaLGgrrkN8vAmdekN2
SIsbn1qjfCPVQ36jPzjC8UjBOYKDQCZcMAwemMTbP92gwuCwvQPIM8jdAgMBAAGj
ggEvMIIBKzASBgNVHRMBAf8ECDAGAQH/AgEBMBEGA1UdDgQKBAhOiPp1NW8VfzAS
BgNVHSAECzAJMAcGBWCCZGQCMBMGA1UdIwQMMAqACE47SDZc4l99MIGABggrBgEF
BQcBAQR0MHIwHgYIKwYBBQUHMAGGEmh0dHA6Ly9vY3ZzLmdvdi5pbjBQBggrBgEF
BQcwAoZEaHR0cDovL3d3dy5jY2EuZ292LmluL2NjYS9zaXRlcy9kZWZhdWx0L2Zp
bGVzL2ZpbGVzL0NDQUluZGlhMjAyMi5jZXIwDgYDVR0PAQH/BAQDAgEGMEYGA1Ud
HwQ/MD0wO6A5oDeGNWh0dHA6Ly9jY2EuZ292LmluL3J3L3Jlc291cmNlcy9DQ0FJ
bmRpYTIwMjJMYXRlc3QuY3JsMA0GCSqGSIb3DQEBCwUAA4ICAQBPH257AxcIUf5C
znq7XjqGQIsLU8ZMa2OacAU76r638YJPlWWX38xoFlNmvZxzFj6XaZ/UMLRKrz5m
m9jn74Uh6Qto+15+yecNtGgIKGS5Qb4e9AuUmyv7H7Qra7yeTNl1pgZoCmPn9lBc
k0rwofti9FJbctoz1mObRZsZWMoBeQuqLtXfyltKWsxXwaUb2lJQ1oxxuKMo2i7B
WonSv+l9ZeibwfONUJLrjxOCEsL16UVFmUzV5Jcx+F8ccs6K9lsuhzEobHH0XJbQ
rsbfCmPibb/DM0SQVXwUEb5LD5nMPYPZQzgd1fav2CiT18FZlee9aHPhN6wRBn0a
sLieGlSOAHaaiG8jQc5OoiRwzfOU5th0pX6duK5vwwmdZJuMLPnz/uMGk2Kr2oWQ
BmiMJNbHDS7FAJR0BGlyXwrH+We9l/V8WKbWL+2js2EHHNSjFa2+5sG4ZSdOtGWC
ATZLwxUZnnV9tBQKFyLrd2oAfGjLXvBNgUiWmAgGtwXHn0/gVuOPi1WMXe1SeMuG
I5gao/m0ygptORyXPHsTsT45l/YmDbK2YVnHEpNu/c/PJk6HNjcd5Vi31iSEPTFY
jYEvwEvYuIF0S6/F5uviOcDvi2DwF7gt6VT1oXqVnY+v0GtsYtQQEe6snV8/pUek
Dt/fFvEiRGYqklQbDuZv1wU1YW9TTg==
-----END CERTIFICATE-----""",
    "SIFY_SAFESCRYPT_2022": """-----BEGIN CERTIFICATE-----
MIIFyzCCA7OgAwIBAgIQRwYH7tCkAM8CDtcmynPsqTANBgkqhkiG9w0BAQsFADA6
MQswCQYDVQQGEwJJTjESMBAGA1UEChMJSW5kaWEgUEtJMRcwFQYDVQQDEw5DQ0Eg
SW5kaWEgMjAyMjAeFw0yMjAyMTYxMDUzNDhaFw0zMjAyMTYxMDUzNDhaMIHVMQsw
CQYDVQQGEwJJTjEiMCAGA1UEChMZU2lmeSBUZWNobm9sb2dpZXMgTGltaXRlZDEd
MBsGA1UECxMUQ2VydGlmeWluZyBBdXRob3JpdHkxDzANBgNVBBETBjYwMDExMzET
MBEGA1UECBMKVGFtaWwgTmFkdTEhMB8GA1UECRMYTm8uNCwgUmFqaXYgR2FuZGhp
IFNhbGFpMR0wGwYDVQQzExRJSSBGbG9vciwgVGlkZWwgUGFyazEbMBkGA1UEAxMS
U2FmZVNjcnlwdCBDQSAyMDIyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAqhUJbYvOXXCf/TT2UMLOI7HmLemOSWsQayMzc95KUL6KHGhAECDTWz07d1pS
A6DhKUp49+uWOUMq/enOZKRQAtdBocQRDDev51FHSesSGVrPASLmxozR/ES4/AF1
1PyeHsefVMnkzKvK6cdAraK417DC4F6uCVM+wj/3kGl7COHqpEj1g5/XKkRlq/3P
IL/4m7NLq2/TIcicgxUjHOSqtHrNW8vDdPD64c2yzMkozzjIZLu6Cv/Of+DGoN2o
SiukWIaQx1VSijasJwykPx435I9sqzjaGja4yI5ox+NbjJnWGmwzncKLBVfkoP5c
4whIJ9E+EF0DoZs/kXb+wWiMQwIDAQABo4IBLzCCASswEgYDVR0TAQH/BAgwBgEB
/wIBATARBgNVHQ4ECgQIScvUu13lnDMwEgYDVR0gBAswCTAHBgVggmRkAjATBgNV
HSMEDDAKgAhOO0g2XOJffTCBgAYIKwYBBQUHAQEEdDByMB4GCCsGAQUFBzABhhJo
dHRwOi8vb2N2cy5nb3YuaW4wUAYIKwYBBQUHMAKGRGh0dHA6Ly93d3cuY2NhLmdv
di5pbi9jY2Evc2l0ZXMvZGVmYXVsdC9maWxlcy9maWxlcy9DQ0FJbmRpYTIwMjIu
Y2VyMA4GA1UdDwEB/wQEAwIBBjBGBgNVHR8EPzA9MDugOaA3hjVodHRwOi8vY2Nh
Lmdvdi5pbi9ydy9yZXNvdXJjZXMvQ0NBSW5kaWEyMDIyTGF0ZXN0LmNybDANBgkq
hkiG9w0BAQsFAAOCAgEAnDRRXSvn13oweNwVHik4deI8Dq4blgsAn12qq8iOQwdw
eqQROakPy+Y8rUDG/UX+1D27XUorlc0rStD4/+c1nEXBXKvth1ij/hMzVn/8Lev0
uWloGO3lUhfYLMOZgSf8EFSZoG7hotc4E9hj2AehKgfFPvJMBWNn7VsgimwBE4bD
VLtn0dFVJWf22LN2CJmwx1MATtnIs0Bot0qLXbfDpq1oefh6vL+RR+XDfYaAsIOm
uZD5Pm4cgJ4EKThcCm9s+IucjbzaZgSkyoe6NmKT1o3+l3W9u1jNR2ABS8yzjqLb
6MqGCdewlasb1cltwl1LANENnDge7xEGkE4MHC5Oa0ihxEvkWrM+ko8QT9S4dwuQ
Na4rJx7Ak9sBgag8WHGHgyJTYvv1ViSnv7UA5GdCZyJwJro4HbenfNyU2iJ9b5ZM
IX5OXbIDJtS6iCCt/DyaWAQW2riws3xea9+PfvO4M5en3GT6zCK3evIbcIo/uIp8
WYNBPK2LKJulYpDWU2q8P0P3q6ykzRwhNTm47PoE3m7KubMHpCcFhNL7p7jTZCoL
ENt4zaAOCNeq/OVcVr9yTRM231ciiDyt6c1OCfF693zuUkl1Y7nORkQgTQDT0wKY
7lgMKmZJ7w9fzgx+R4HHQr1dhE7pf5uLMKVFd//gsNZ4bgFdHu47YlGX3rQXXlo=
-----END CERTIFICATE-----""",

    "CCA_INDIA_2014": """-----BEGIN CERTIFICATE-----
MIIDXjCCAkagAwIBAgIUQOc404Yj9MDFgNm5n3eFpZhQpA0wDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBfMQswCQYDVQQGEwJJ
TjEtMCsGA1UECgwkQ29udHJvbGxlciBvZiBDZXJ0aWZ5aW5nIEF1dGhvcml0aWVz
MSEwHwYDVQQDDBhDQ0EgSW5kaWEgMjAxNCBTdWItQ0EgMDEwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQCpXu1mqHX5DbpXImaitSNl6Urvqbs/o4+2h4Zb
htvc/0uVlvk52j76+WT/AKJWoo9olmg/net2/S2L9M8i9n76Y6nTJPJEaf1NGD+l
uZuYtVW7CSlOFybCkmgdoSItUJkqD/LBbKEYTYE0WNc5MlEHRrVyzc0UHAYMbpPb
loaeH+BtoEL4U3FX8wyk17GDb/v0MkfaX5aUpQp8wuSn+QIMMQKrDzYxAnQTkCH7
TCc9xuET/p9FNGun06eE08nYYal/l281tLlfCS168gPrNoAgY9RwD1/Za5r/Eabd
tPeixR3sWCZIXAoIcxIGRKlDgG/BzDSQhsaBLF0v91OsGT7FAgMBAAGjEzARMA8G
A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAGb2X8YknD63y/dJF6i0
peLuDVFOWGXeqDKo9xJDpYZL1boh+wZWdgfTHQ7iMR4pqh85zTOx1NO7ArQz+0Vg
kLxrjZ8W05WWWMkdTbehxu46NkTr81v1r6GfdJBwInKgz3kMk828cVkue9t1sBye
2ASPdbqgVu/sME15s4m8Oiv00OW6hIi7gP0bdQjUSSWlGcEzNmXcJ+BEYORMEfLm
CwVA6wCTHr2UNQVQMGQ68gC8w5/nj68FXc2hEnRgVjaDGE4WUVSkJsgXBA4gbYtb
bzQhuL9lY5Gotys4VqELO4fPRy3s8hHEW21oYd88Qydm+65M7Neh271SjF9JYfG9
hRM=
-----END CERTIFICATE-----""",
    "NIC_CA_2017": """-----BEGIN CERTIFICATE-----
MIIDWDCCAkCgAwIBAgIUPYQXFFo4OCheEhVmN1v8TpBwxI4wDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBZMQswCQYDVQQGEwJJ
TjEkMCIGA1UECgwbTmF0aW9uYWwgSW5mb3JtYXRpY3MgQ2VudHJlMSQwIgYDVQQD
DBtOSUMgQ0EgSW5kaWEgMjAxNyBTdWItQ0EgMDEwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQC8GAHvNJoCTCiE1Sujj/e8Eq6pQWw0mla1MQPkzeEZM5aQ
rUth5rj5NThZHM8ojKnpIPE5UIZiSuqXC6iuaYiYd+p44SmMf/Dp0LGTLxK44Wvu
pvYHeoUkVbzaUkaf/L771Axj9apG0TnO2Ovq7BhU85FRtw/gxareXpQ6+PHWNIwP
3ey2uO6IeJqL62PVbVYSaFidPoLyGRrbwv+tQLCy3QMXphWdmvS1HlplTSXN5nJU
Ry2C6Ea/jGIqaZIaQ0Eu8WGrHvaVOCAZPK7cC176GwRpG7MsrKJrg+DylL9OF8W6
sa4cqooh+TqCqfniPFA1hH83zdUmn9Xrz3dVvacjAgMBAAGjEzARMA8GA1UdEwEB
/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC7cRNEUQ/gWb6rPptYhhWvVIDPs
8Rf4Fa0hHB1Ewfzqv/p8SanLT1EzLtggvWiLYtvAM3L7nl2E+TmA5Y04dVTO/kYn
zNT31bZswHyJz/RdkMwgXED2CpfId9Qeo5sTgg+w2fu0O9n9wBRUEKn/60ecN4uB
qyWBGUf3SP6aLBzynATH+v8FTVaSM/z+jiuu6vbC/OmSPJFLYcSzCOfd5FKEwMTV
j8K7Nz+q3D7egonDM/dvwZYuM497vE6LgqvHWK+kmpFEbqUYhn/HKSKmBLSDqlP4
9tjg1KM3G6GERVL2Kruxw/WZazZhbGEY5pXOzCh056kMjNFs47PsI7Biocw=
-----END CERTIFICATE-----""",
    "NIC_CA_2021": """-----BEGIN CERTIFICATE-----
MIIDWDCCAkCgAwIBAgIUc4jGsgz6KHaK0a1GWjIkbr0PenwwDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBZMQswCQYDVQQGEwJJ
TjEkMCIGA1UECgwbTmF0aW9uYWwgSW5mb3JtYXRpY3MgQ2VudHJlMSQwIgYDVQQD
DBtOSUMgQ0EgSW5kaWEgMjAyMSBTdWItQ0EgMDEwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCw6OKI+EakGkpwP/g+D3mMpoiS+bYY+9SRg51kDx+jpToy
ty2umK90trfuHjzGYzsAJv8zjGQverXUpee4JOzcqw0Je/kiKEefV6fAS91JntzP
keRlQaZMaco+ciaZlr14SX+G+JIASLCMQJ8TciR59PatPP19qrfvVehomLtaDHy9
J9c2SauIG8vCUJkqiHGaHzTsHiU8r9GsN60Ws5qyDU7vPe/MxKmlACDdQ3ogyC9G
yIHtuYGEpIGykODdanZVWfdyTUWKcDSp3F5T4s8Q20mT4WpPqDMcdOZZQ2J2xYGc
1m3Hp/kJToTOrGzZ5K7ybEWPUv8tKEfRPFOu9O4rAgMBAAGjEzARMA8GA1UdEwEB
/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJn2Z8HdHQmz/yzRp+82A42tgegB
Kexyf+ICPRvQIieewWBvepFY7mODWouUXj5I9Rc9feAycXYUAG/Dil5N4XjMhFUh
9EQ4k77rd6OxM9QQhTwCl9/LUwEbn6hUgFqegZ1Wc+YaLZ9/PXvbn4UlyrWtRobh
aIJgO9R4N9RvcO4gfOgIm2iP6Dp7hVmdcz4dkTyta3UdyU1bfPGOwVoxBMB94Eno
wgTyXZ0pKZAhpji2UCF7SaDjrrdXoSpFn2yWK77mjec6O2HhcmZvnZ9bA4dHHUyo
DC1hcbZRF1R5qELux8njkc94L+wYYobK7rnkLa/wESYbltVWu4ty9ePuMVY=
-----END CERTIFICATE-----""",
    "EMUDHRA_CA": """-----BEGIN CERTIFICATE-----
MIIDWDCCAkCgAwIBAgIUK67x6KZtmwqMy5riXeklrnbai0UwDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBZMQswCQYDVQQGEwJJ
TjEmMCQGA1UECgwdZU11ZGhyYSBDb25zdW1lciBTZXJ2aWNlcyBMdGQxIjAgBgNV
BAMMGWVNdWRocmEgQ0EgMjAxNCBTdWItQ0EgMDEwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCij3gBWaAZBp1OPfMuR5dbMIoEM4VNSqn2k7TdHbO2tzmZ
bOh5EVRlFkSqbYoSE3CTyXsF8uP9Cfx4wlBBFXMd5p1ObvOiJ2YsAPS6OcaCtmVL
Q0V4K5qRe6vorzEcfXiRIeJXSzNvaz3FGXIxm3GjerMmIqtbFR/77dAuq/lpG1Td
0nm/rAfVH6y3ATVkR3DPN0ibSDRxjJNvw36ysdzrEpSPjlkzVuVsPkZb6rLHdoCd
vnIY8qabfpIDhuLUhTMjpnIXwgDAGKpjsU7Ke8Ej1Wq7ndLZoDDEAZeciD2dvBGh
dzrIfLgvSkivDkEO4Y8NCeSCvzfULeErXMPLP2kTAgMBAAGjEzARMA8GA1UdEwEB
/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIA4zazJZ+byoa86/DE2RmTIBO/k
K/zrlrgoWVxrLSytQuX+7rit6K1ko4MaGn7PSR1eDoWTd0nYoybuP29wVC6Labav
fT/14AVUA66IDWhd5SeRxPIp4mkmqpBxyrzXDNkttBFKOenlN6BSza8h9IG1sFF2
DgSdsFdH8smRQFqw90XLfgFLP/HkMY+oPsrTiudxJzRIxRHQLrAN6H9Q+J4+CR7R
QZuVW4nK2eRiVNDaI7JKunOo8cjnlu0HkZQAr7n4b54ZJW5+yfts1zZ2EzFm7TVv
/WxXfgTEgR56qMc32r5LECUAi+ETVCy3zubI6a7wSVDrhhJAJyijwEN0huY=
-----END CERTIFICATE-----""",
    "CAPRICORN_CA": """-----BEGIN CERTIFICATE-----
MIIDYDCCAkigAwIBAgIUDA3O+4FiQtEofwohhRc90SUtU5AwDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBhMQswCQYDVQQGEwJJ
TjEsMCoGA1UECgwjQ2Fwcmljb3JuIElkZW50aXR5IFNlcnZpY2VzIFB2dCBMdGQx
JDAiBgNVBAMMG0NhcHJpY29ybiBDQSAyMDE0IFN1Yi1DQSAwMTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMVonkC/VKeXevDfqkIwh5bPvO644ka7BCQc
RsI5d2hSL28S43T6hDtiPTPXtKqowsFnKcTEcLymSZ42nllrS6eANac/8UzpmuA6
ca7vPbekiaI7PZekQnQLhZeX2rp+IJpGAQTsG0m84owYBj1KOLGjHBkOFV5cbako
U+qQeQo8+1zAD04eEzi8qLzhyudrH0dQyzTqzvASJ8f9bG7j3+tNVi+ax1BgSpo6
AbglECvuYFUFJhqIagFja6FAghAjcD+0zGukUyEJ8ROVMqexfwe1FDE2jgugnO1y
8OhPRZhAQMo5p+R2wa3PGvFx57fTafn3d108g0YwO8Wu425hnq8CAwEAAaMTMBEw
DwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAJM+V2nFfne8eB4U7
6CPYLcVA/y3x0gWsKhrbkXVp78ZCp/ySLdnJYbi6cwLGTOz30+0A2n1g8hQwd6Iq
Xy00W4VVeDLdEXRc663TO67J6Dp3ZZ1O25jy9fpADEcjOxDdmbLg97OtnB1OBevi
VMkrcWcw71yX7cCAWrTWAU2ZrnP5Xl4SAVe4e1UHX2P7ZRKvPxXqWm5ON8cA4Byw
CZO4wt7Bt6VNR+2J0E2y2rf/qWjvLQrtI/2oKKKktUgFTtp8CgJ28Gj081u7HRv+
3OGhZOzYxwVr2sXXgcrt0utbxrfTByS5oxQYfdytTEiI04MSDZMC6skEffdhgBOb
iyj32Q==
-----END CERTIFICATE-----""",
    "NCODE_CA": """-----BEGIN CERTIFICATE-----
MIIDZDCCAkygAwIBAgIUVBZLX8oaNNHZwp4iuXC3FO+G8CAwDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBlMQswCQYDVQQGEwJJ
TjEyMDAGA1UECgwpR3VqYXJhdCBOYXJtYWRhIFZhbGxleSBGZXJ0aWxpemVycyBD
byBMdGQxIjAgBgNVBAMMGShuKUNvZGUgU29sdXRpb25zIENBIDIwMTQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDoYfD7oBJZgx4o8ewBwasU8XY8HHG
ygDlID357UQI0/dyrTtMPbD3JV8f1sIxYe7PorxJf2un95FB9q3gXSUe4mRkZkgH
xF7aNskKU01XkSPsCHQVZ0hlGdPgA1NSnbHX+HQ7DjmMvD5zVZOl1ERUDph8i9dj
LA5K8wgi7St7Bq4TEUf8oPHNQyc1MSKFk8u9+v7VHNvCtPE1BwYIrY1RslC9Xw+T
B140eQXPwfJkJescqMAZiUYmzAdHE1k+3eGWd/x9b0ajWLt5Vmxfjd+vV6Vnrvfx
80q6QotdVFNVdxz8BHbeqyOGl4IDTlgZI6faeLMdkoxXd4kT+SYvoDt5AgMBAAGj
EzARMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBACci34aYCSJb
lvZYXn2PbWOJdolQD0zC9MfCO44/RYZykI06qYjDPEDGoJIj9//E1xtEy5xicsRP
l18z9M8tIFTdSfn9Ddm683rgUXq/WsQvk72eER3cVrecrq/vmsWX8bJLTWg/tQj2
mRV5gsJ6/8Jj0o1TaY6mpjDY/pz77XXNNFFDpZtaF9529lJt9B5X4dAfPoOtYse8
b3WwIzDC3HM/SFRC2tBZx5fuS6+d8sbY558NQfxO+QWu95XPP8BiQKcs7AFHEvNt
pycktuJaKBdHbrqfX46xlYl9l1XLNWJonaFCA+wI9p7u01KWlIwGYXUbvppryQzH
vNixWVbTDmI=
-----END CERTIFICATE-----""",
    "SAFESCRYPT_CA": """-----BEGIN CERTIFICATE-----
MIIDVzCCAj+gAwIBAgIUTSYVfcL3LMrqXjjhltnoFL6r1HAwDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBYMQswCQYDVQQGEwJJ
TjEiMCAGA1UECgwZU2lmeSBUZWNobm9sb2dpZXMgTGltaXRlZDElMCMGA1UEAwwc
U2FmZVNjcnlwdCBDQSAyMDE0IFN1Yi1DQSAwMTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBANFrRg2tY5c9TqPLkXYffrdd5cSe57NFchuwceJcJw/Beqmd
NLDymYK/tKTaTneSLBSjhX4EQMzI/7xh41u8Zf1yhxWpdThEt+VEB2cZafvfcL+f
3G6UAEAGToDZzqOXG7c8ct4pqPVh4oz8NB+pJzxGNDcPdf9utmuOdvRmnp/vIb6q
cwiR3jCdc/ECRqS9X+yuEusJ3iqSM7qICjaveH33PCCFLpQRZG8pm8PzDt/cLlC5
FjuNmDHGrsUiKTkp48Fs5UF8xyB+BX/Bo/PLnIlghne6QxeEctj2ialXKh5j2vTv
tlbLUcoDxw/lmwi/R3BnZ+HPQcXGfpGeXBnA8gcCAwEAAaMTMBEwDwYDVR0TAQH/
BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAnFxV8XijmiHFjA4nQtW/+ocGbOFa
0Ibo2ocOaIvsLDVBNWSWQpDqi9DTHlZsAYum/zOU1Lnv741tP6J7EXJo/cvOTl1D
A1Et44pb5IXRbEg4IRxKTmXDZsqHHa6ThSR98e2/2peNzd7rHeCh3gR+3eKbsRTD
6lZYgEoqUG6iWCAackGbD1CX7XTYARg93JdxO7+lU4ybeNgST33hvYnGLASiMbF0
R7tcS6N6av8U/15tGj6hWzpbiSSKyO7U12yjOl4rVgwXM6zD+JqcJeP4SuACCEWd
/vB+dK6ZyJkhNIbCmc1qEpiZAWq9pcLGoHyb3BNf+YMhHzPh6lyuxVEMCw==
-----END CERTIFICATE-----""",
    "PROTEAN_NSDL_CA": """-----BEGIN CERTIFICATE-----
MIIDWDCCAkCgAwIBAgIUYrr8ZFzDd5itctENL/VskEJdqZMwDQYJKoZIhvcNAQEL
BQAwXjELMAkGA1UEBhMCSU4xLTArBgNVBAoMJENvbnRyb2xsZXIgb2YgQ2VydGlm
eWluZyBBdXRob3JpdGllczEgMB4GA1UEAwwXUm9vdCBDQSBvZiBJbmRpYSAtIDIw
MTQwHhcNMTQwMTAxMDAwMDAwWhcNMzUwMTAxMDAwMDAwWjBZMQswCQYDVQQGEwJJ
TjEqMCgGA1UECgwhUHJvdGVhbiBlR292IFRlY2hub2xvZ2llcyBMaW1pdGVkMR4w
HAYDVQQDDBVQcm90ZWFuIGUtR292IENBIDIwMTQwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCr3fu0Q6NzuPypuSgZHf1iqSZPG2FqiFyiaxdbBSR95gmD
/Zh8jZMnD2QAuno25xWp9nvLQmDYaPoV0mwpv5DmqQ8rrYybcg8PTpuEqyYBCEoI
2/sjwMHTeKmI1FW//UK6GkKlgXAqrvhP3G/EuVZm+lx5QTOsXvBY7evPtsf3eW6A
ssuw4YSmxETQhACS5ivXmQDHhziYVAw2dua13yT+fSkot8NjcmcXjhInVYhP4zPH
RzDZCEtn1ghT44zz+mK9VGzDmkiYhKqUNeEWP3TdYKHoyqjPk8ZgkmpTH2q1WzdI
hYRdMxRJLqEwM9FFWvucQz/XYTs3NX/4me0cTvVdAgMBAAGjEzARMA8GA1UdEwEB
/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAE2XBJtKFb8iTuZH9VK5sRLcwZvm
Efb1ivLUcJpTqCd8TUHKhgze39Vn1bmCXB4fvY/nQxUOHCc93awD4hYglX4Sjd+F
DaxpEOFBxN4V0WjFMBBsnGYhtCoEIuh9nPftXI9BO+kKyZ5Fd9NApIxnspAHGiQo
ivLi2xzFgBH2ZsAHPx2qFcMKSICSUS/8PuSpytGvl+CHIiMCM1qsqkfLKexOJsMw
qvFp7fL2ILV/TTxhq37IOTsmn4MmqFs+GirxfJHWIqWlWjefzMFLqPB/ZRd4muWl
ECU9Fk+5T9w/lVszariYlKskMeeh2nA+pWwe37ITR0fFl1kpRTOPBNsibhw=
-----END CERTIFICATE-----""",
}


class CCACertificateManager:
    """Manages the Root and Intermediate Certifying Authority certificates for India."""

    def __init__(self):
        self._root_certs: List[x509.Certificate] = []
        self._intermediate_certs: List[x509.Certificate] = []
        self._validation_context: ValidationContext | None = None
        self._initialized = False

    def _parse_pem_cert(self, pem_str: str) -> x509.Certificate:
        """Parses a PEM string into an asn1crypto x509.Certificate."""
        if pem.detect(pem_str.encode("ascii")):
            _, _, der_bytes = pem.unarmor(pem_str.encode("ascii"))
            return x509.Certificate.load(der_bytes)
        raise ValueError("Invalid PEM certificate format")

    def download_latest_cca_certs(self) -> List[Tuple[str, bytes]]:
        """
        Attempts to fetch the latest certificates from cca.gov.in.
        Returns a list of (cert_name, der_or_pem_bytes) if successful.
        """
        downloaded = []
        try:
            logger.info("Connecting to CCA India certificate portal at %s ...", CCA_CERTS_URL)
            response = requests.get(
                CCA_CERTS_URL,
                timeout=3.5,
                headers={"User-Agent": "VeriSeal-Engine/1.0 (CCA PKI Validator)"},
            )
            if response.status_code == 200:
                logger.info("Successfully reached CCA India portal.")
                # If the portal exposes certificate links or bundle:
                # We extract any PEM blocks found in the response body
                text = response.text
                if "-----BEGIN CERTIFICATE-----" in text:
                    for part in text.split("-----END CERTIFICATE-----"):
                        if "-----BEGIN CERTIFICATE-----" in part:
                            clean_pem = part[part.find("-----BEGIN CERTIFICATE-----"):] + "-----END CERTIFICATE-----\n"
                            try:
                                cert = self._parse_pem_cert(clean_pem)
                                downloaded.append(("cca_online", cert.dump()))
                            except Exception as parse_err:
                                logger.debug("Could not parse cert snippet: %s", parse_err)
        except Exception as exc:
            logger.info("Could not fetch remote CCA certs (%s). Falling back to embedded trust store.", exc)
        return downloaded

    def initialize(self) -> None:
        """Initializes the trust store using embedded certificates and optional online sync."""
        if self._initialized:
            return

        roots: List[x509.Certificate] = []
        intermediates: List[x509.Certificate] = []

        # 1. Load all embedded certificates
        for key, cert_pem in EMBEDDED_CCA_CERTS_PEM.items():
            try:
                cert = self._parse_pem_cert(cert_pem)
                # Check if Root (Self-Signed)
                if (
                    cert.subject == cert.issuer
                    or cert.self_signed in ("yes", "maybe")
                    or "RCAI" in key
                    or "Root" in cert.subject.human_friendly
                    or key in ("CCA_INDIA_2022", "CCA_INDIA_2022_SPL")
                ):
                    roots.append(cert)
                else:
                    intermediates.append(cert)
            except Exception as e:
                logger.error("Failed to load embedded certificate %s: %s", key, e)

        # 2. Try online sync from cca.gov.in (graceful fallback)
        try:
            online_certs = self.download_latest_cca_certs()
            for name, der_data in online_certs:
                try:
                    c = x509.Certificate.load(der_data)
                    if c.subject == c.issuer or c.self_signed in ("yes", "maybe"):
                        roots.append(c)
                    else:
                        intermediates.append(c)
                except Exception:
                    pass
        except Exception as e:
            logger.warning("Online sync failed, proceeding with embedded trust store: %s", e)

        self._root_certs = roots
        self._intermediate_certs = intermediates

        # 3. Construct the pyhanko-certvalidator ValidationContext
        # Note: revocation_mode='soft-fail' ensures that if government CRL/OCSP servers
        # are intermittently unreachable or down, valid government certs are not rejected.
        self._validation_context = ValidationContext(
            trust_roots=self._root_certs,
            other_certs=self._intermediate_certs,
            allow_fetching=True,
            revocation_mode="soft-fail",
        )
        self._initialized = True
        logger.info(
            "VeriSeal Trust Store initialized with %d root CAs and %d intermediate CAs.",
            len(self._root_certs),
            len(self._intermediate_certs),
        )

    def get_validation_context(self) -> ValidationContext:
        """Returns the configured pyhanko ValidationContext."""
        if not self._initialized or self._validation_context is None:
            self.initialize()
        return self._validation_context


# Singleton instance
cca_manager = CCACertificateManager()


def get_cca_trust_context() -> ValidationContext:
    """Convenience helper to retrieve the global CCA ValidationContext."""
    return cca_manager.get_validation_context()
