import * as React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import {
  ShieldCheck,
  ChevronRight,
  Zap,
  Lock,
  Sparkles,
  CheckCircle2,
  HelpCircle,
  AlertTriangle,
  Info,
  Sliders,
  Scale,
  Banknote,
  Calculator,
  GraduationCap,
  Award,
  FileCheck2,
  Clock,
  Globe,
  Code2,
  Ruler,
  Coins,
  Heart,
  FileText,
  FileSpreadsheet,
  TrendingUp,
  Building2,
  Languages,
} from 'lucide-react';
import SalarySlipGeneratorEngine from '@/components/tools/SalarySlipGeneratorEngine';
import { AdSlot } from '@/components/ads/AdSlot';

export const metadata: Metadata = {
  title: 'Free Salary Slip / Pay Slip Generator Online (With EPF, ESI & TDS) | Kagazo',
  description: 'Generate professional corporate and SME monthly salary slips with automatic calculation of EPF, ESI, Professional Tax, and TDS. Bilingual format (English & Tamil) with company seal box. 100% private in-browser generation.',
  alternates: {
    canonical: 'https://kagazo.in/tools/salary-slip-generator',
  },
  openGraph: {
    title: 'Free Salary Slip / Pay Slip Generator Online (With EPF, ESI & TDS) | Kagazo',
    description: 'Generate professional corporate and SME monthly salary slips with automatic calculation of EPF, ESI, Professional Tax, and TDS. Bilingual format (English & Tamil) with company seal box. 100% private in-browser generation.',
    url: 'https://kagazo.in/tools/salary-slip-generator',
    siteName: 'Kagazo',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Free Salary Slip / Pay Slip Generator Online (With EPF, ESI & TDS) | Kagazo',
    description: 'Generate professional corporate and SME monthly salary slips with automatic calculation of EPF, ESI, Professional Tax, and TDS. Bilingual format (English & Tamil) with company seal box. 100% private in-browser generation.',
  },
};

const HOW_TO_STEPS = [
  {
    "step": 1,
    "title": "Enter Employer Details",
    "desc": "Input company name, registered office address, corporate logo, and GSTIN / PAN identifiers."
  },
  {
    "step": 2,
    "title": "Fill Employee Particulars",
    "desc": "Provide employee name, designation, department, employee ID, date of joining, and bank details."
  },
  {
    "step": 3,
    "title": "Specify Earnings Breakdown",
    "desc": "Input Basic Pay, HRA, Dearness Allowance, Conveyance, and Special Allowances for the pay month."
  },
  {
    "step": 4,
    "title": "Calculate Deductions",
    "desc": "Apply automatic statutory deductions for EPF, ESI, Professional Tax, and voluntary loan recoveries."
  },
  {
    "step": 5,
    "title": "Export Clean A4 Pay Slip",
    "desc": "Review total gross vs net pay with automatic numbers-to-words conversion and export print-ready A4 PDF."
  }
];

const COMMON_ERRORS = [
  {
    "badge": "Error: Arithmetic Mismatch",
    "title": "Gross Minus Deductions Not Matching Net Pay",
    "desc": "Manual Excel pay slips frequently contain rounding discrepancies between component sums and net salary. Kagazo calculates all line items with exact cent/paise arithmetic precision."
  },
  {
    "badge": "Error: Over-Deducting EPF",
    "title": "Calculating 12% on Gross Instead of Basic",
    "desc": "EPF rules mandate 12% deduction on Basic Pay + DA up to the Rs 15,000 ceiling, not on gross earnings. Applying PF to gross reduces employee take-home pay illegally."
  },
  {
    "badge": "Error: Missing Bank Account Info",
    "title": "Omitting Bank Name, Account & IFSC",
    "desc": "Banks reject salary slips submitted for home loans or visa applications if salary credit bank details are missing. Ensure employee bank and IFSC numbers are explicitly noted."
  },
  {
    "badge": "Error: Missing Attendance Days",
    "title": "Omitting Total Working vs Paid Days",
    "desc": "Auditors and visa consular officers look for effective working days, paid leave days, and LOP (Loss of Pay) count. Always include monthly attendance figures."
  }
];

const FAQS = [
  {
    "question": "Are salary slips generated by Kagazo legally valid for bank loans?",
    "answer": "Yes. When stamped or signed by an authorized company director or HR manager, salary slips formatted with complete company details, PAN/GSTIN, statutory deductions, and employee bank details are fully accepted by banks for home, car, and personal loans."
  },
  {
    "question": "Does this salary slip generator automatically calculate EPF and ESI?",
    "answer": "Yes. You can enable automatic calculation toggles that apply standard statutory rules: 12% on Basic Pay for EPF (with optional Rs 15,000 statutory cap) and 0.75% of Gross Wages for ESI."
  },
  {
    "question": "Can small business owners, contractors, and startups use this tool?",
    "answer": "Yes. Kagazo is engineered for SMEs, retail shops, contractors, startups, and domestic employers who need to issue professional, standardized salary receipts without expensive HRMS software."
  },
  {
    "question": "Is our company financial and employee payroll data stored online?",
    "answer": "No. Kagazo works with 100% in-browser privacy. No payroll numbers, employee bank accounts, PAN numbers, or corporate records are uploaded to any cloud server or database."
  },
  {
    "question": "Does the salary slip include the Net Salary amount written in words?",
    "answer": "Yes. The generator automatically converts your net take-home pay into official Indian Rupee currency words (e.g., \"Rupees Seventy-Five Thousand Four Hundred Only\") preventing tampering."
  },
  {
    "question": "Can I add our company logo to the pay slip?",
    "answer": "Yes. You can upload your company logo directly from your device. It is embedded dynamically into the PDF header with high-DPI clarity."
  },
  {
    "question": "What are the standard mandatory components of an Indian salary slip?",
    "answer": "A compliant Indian pay slip must include: Company Name & Address, Pay Period (Month & Year), Employee Name & ID, Designation & Department, UAN & PF Number, Bank Account & IFSC, Earnings Table, Deductions Table, and Net Pay."
  },
  {
    "question": "What is Professional Tax and how is it calculated?",
    "answer": "Professional Tax is a state-level tax levied on salaried employees, typically ranging between Rs 150 to Rs 208 per month depending on state slabs (e.g., Maharashtra, Karnataka, Tamil Nadu)."
  },
  {
    "question": "Can I generate salary slips for contract or daily-wage staff?",
    "answer": "Yes. You can customize earning headers to show Daily Wage, Overtime (OT), and Piece-rate incentives while disabling corporate benefits like PF and gratuity."
  },
  {
    "question": "How should I print the salary slip for physical distribution?",
    "answer": "Download the generated PDF, open in any PDF viewer, select A4 paper with Actual Size scaling, and print in crisp black-and-white or full color with space for company stamp and employee acknowledgement signature."
  }
];

export default function SalarySlipGeneratorPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebApplication',
        name: 'Bilingual Salary Slip Generator',
        url: 'https://kagazo.in/tools/salary-slip-generator',
        applicationCategory: 'FinanceApplication',
        operatingSystem: 'All',
        browserRequirements: 'Requires JavaScript',
        offers: {
          '@type': 'Offer',
          price: '0',
          priceCurrency: 'INR',
        },
        description: 'Generate professional corporate and SME monthly salary slips with automatic calculation of EPF, ESI, Professional Tax, and TDS. Bilingual format (English & Tamil) with company seal box. 100% private in-browser generation.',
      },
      {
        '@type': 'HowTo',
        name: 'How to Generate a Professional Salary Slip in 5 Steps',
        description: 'Step-by-step verified workflow instructions for Bilingual Salary Slip Generator.',
        step: HOW_TO_STEPS.map((s) => ({
          '@type': 'HowToStep',
          name: s.title,
          text: s.desc,
          position: s.step,
        })),
      },
      {
        '@type': 'FAQPage',
        mainEntity: FAQS.map((faq) => ({
          '@type': 'Question',
          name: faq.question,
          acceptedAnswer: {
            '@type': 'Answer',
            text: faq.answer,
          },
        })),
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          {
            '@type': 'ListItem',
            position: 1,
            name: 'Home',
            item: 'https://kagazo.in',
          },
          {
            '@type': 'ListItem',
            position: 2,
            name: 'Tools',
            item: 'https://kagazo.in/tools',
          },
          {
            '@type': 'ListItem',
            position: 3,
            name: 'Bilingual Salary Slip Generator',
            item: 'https://kagazo.in/tools/salary-slip-generator',
          },
        ],
      },
    ],
  };

  return (
    <div className="min-h-screen bg-background bg-dot-grid text-text-main pt-28 pb-20 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="absolute top-28 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[350px] bg-primary/10 rounded-full blur-3xl pointer-events-none -z-10" />

      <div className="max-w-7xl 2xl:max-w-[1536px] mx-auto space-y-8">
        {/* Breadcrumb Navigation */}
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-text-main/60">
          <Link href="/" className="hover:text-primary transition-colors font-medium">
            Home
          </Link>
          <ChevronRight className="w-3.5 h-3.5 text-text-main/30" />
          <Link href="/tools" className="hover:text-primary transition-colors font-medium">
            Tools
          </Link>
          <ChevronRight className="w-3.5 h-3.5 text-text-main/30" />
          <span className="text-primary font-bold">Bilingual Salary Slip Generator</span>
        </nav>

        {/* Hero Header */}
        <header className="text-center space-y-4 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-primary-light border border-primary/20 text-xs sm:text-sm font-semibold text-primary shadow-2xs">
            <span className="flex h-2 w-2 rounded-full bg-primary animate-pulse" />
            <span>Statutory EPF & ESI Auto-Math • A4 PDF Export</span>
          </div>

          <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight text-text-main leading-[1.18]">
            <span>Professional Monthly Salary Slip & </span>
            <span className="text-primary">Pay Slip Generator</span>
          </h1>

          <p className="text-base sm:text-lg text-text-main/80 leading-relaxed font-normal">
            Generate professional corporate and SME monthly salary slips with automatic calculation of EPF, ESI, Professional Tax, and TDS. Bilingual format (English & Tamil) with company seal box. 100% private in-browser generation.
          </p>
        </header>

        {/* 2-Column Responsive Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          <main className="lg:col-span-9 xl:col-span-10 space-y-8">
            {/* Interactive Engine Canvas */}
            <SalarySlipGeneratorEngine />

            {/* Post-Action Native Ad Placement */}
            <AdSlot slot="post_download" />

            {/* Key Differentiators Showcase */}
            <section className="bg-white rounded-3xl border border-surface-darker shadow-card p-6 sm:p-8 space-y-4">
              <div className="space-y-2">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-wider">
                  <Sparkles className="w-3.5 h-3.5" />
                  Engineering &amp; Compliance Excellence
                </div>
                <h2 className="text-xl sm:text-2xl font-extrabold text-text-main">
                  Key Technical Features &amp; Architecture
                </h2>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
                <div className="p-4 rounded-2xl bg-surface border border-surface-darker/60 space-y-1.5">
                  <span className="text-xs font-bold text-primary flex items-center gap-1.5">
                    <Sparkles className="w-4 h-4 text-primary" /> Auto Statutory Math
                  </span>
                  <p className="text-xs text-text-main/70 leading-relaxed">
                    Automatic computation of EPF (12% of Basic), ESI (0.75%), Professional Tax, and Income Tax TDS.
                  </p>
                </div>
                <div className="p-4 rounded-2xl bg-surface border border-surface-darker/60 space-y-1.5">
                  <span className="text-xs font-bold text-primary flex items-center gap-1.5">
                    <Sparkles className="w-4 h-4 text-primary" /> Bank-Approved Layout
                  </span>
                  <p className="text-xs text-text-main/70 leading-relaxed">
                    Clean tabular earnings and deductions layout compliant with SBI, HDFC, and ICICI loan verification standards.
                  </p>
                </div>
                <div className="p-4 rounded-2xl bg-surface border border-surface-darker/60 space-y-1.5">
                  <span className="text-xs font-bold text-primary flex items-center gap-1.5">
                    <Sparkles className="w-4 h-4 text-primary" /> 100% Confidential
                  </span>
                  <p className="text-xs text-text-main/70 leading-relaxed">
                    Employee salary figures, bank account numbers, and PAN data are rendered exclusively in browser RAM.
                  </p>
                </div>
              </div>
            </section>

            {/* Official Specifications & Reference Table */}
            <section className="bg-white rounded-3xl border border-surface-darker shadow-card p-6 sm:p-8 space-y-4">
              <div className="flex items-center justify-between border-b border-surface-darker pb-3">
                <div>
                  <h2 className="text-lg sm:text-xl font-extrabold text-text-main">
                    Indian Payroll Statutory Deduction Limits (FY 2025–26)
                  </h2>
                  <p className="text-xs text-text-main/70">
                    Authoritative standards, formatting thresholds, and official regulatory guidelines:
                  </p>
                </div>
                <span className="text-xs font-bold text-primary bg-primary-light px-2.5 py-1 rounded-full border border-primary/20">
                  Statutory Rules
                </span>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs border-collapse">
                  <thead>
                    <tr className="border-b border-surface-darker bg-surface text-text-main font-bold">
                      <th className="py-2.5 px-3 font-bold">Payroll Component</th><th className="py-2.5 px-3 font-bold">Mandatory Statutory Limit</th><th className="py-2.5 px-3 font-bold">Applicable Wage Threshold</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="hover:bg-surface/50 dark:hover:bg-slate-800/40 transition-colors"><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Employee Provident Fund (EPF)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">12% of Basic + DA (Wage ceiling: Rs 15,000/mo)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Mandatory for establishments with 20+ staff</td></tr>
                    <tr className="hover:bg-surface/50 dark:hover:bg-slate-800/40 transition-colors"><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Employees State Insurance (ESI)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">0.75% Employee, 3.25% Employer</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Applicable on gross monthly wages up to Rs 21,000</td></tr>
                    <tr className="hover:bg-surface/50 dark:hover:bg-slate-800/40 transition-colors"><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Professional Tax (PT)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Slab-based (Rs 0 to Rs 208/mo per state laws)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">State-specific (Maharashtra, TN, Karnataka)</td></tr>
                    <tr className="hover:bg-surface/50 dark:hover:bg-slate-800/40 transition-colors"><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">House Rent Allowance (HRA)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Typically 40% (Non-Metro) or 50% (Metro) of Basic</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Tax-exempt under Section 10(13A) subject to rent receipts</td></tr>
                    <tr className="hover:bg-surface/50 dark:hover:bg-slate-800/40 transition-colors"><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Tax Deducted at Source (TDS)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">As per employee chosen tax regime (Old vs New)</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Deducted monthly under Section 192</td></tr>
                    <tr className="hover:bg-surface/50 dark:hover:bg-slate-800/40 transition-colors"><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Net Salary Formula</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Gross Earnings minus Total Deductions</td><td className="py-2 px-3 border-b border-surface-darker/50 dark:border-slate-800/80">Amount credited to employee bank account</td></tr>
                  </tbody>
                </table>
              </div>
            </section>

            {/* Visible 5-Step Practical How-To Guide */}
            <section className="bg-white rounded-3xl border border-surface-darker shadow-card p-6 sm:p-8 space-y-4">
              <div className="space-y-1">
                <h2 className="text-xl sm:text-2xl font-extrabold text-text-main">
                  How to Generate a Professional Salary Slip in 5 Steps
                </h2>
                <p className="text-xs sm:text-sm text-text-main/70">
                  Follow this verified 5-step process for instant compliance and verified results:
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-5 gap-4 pt-2">
                {HOW_TO_STEPS.map((step) => (
                  <div key={step.step} className="p-4 rounded-2xl bg-surface border border-surface-darker/60 space-y-2">
                    <span className="w-7 h-7 rounded-full bg-primary text-white text-xs font-bold flex items-center justify-center shadow-xs">
                      {step.step}
                    </span>
                    <h3 className="text-xs font-bold text-text-main">{step.title}</h3>
                    <p className="text-xs text-text-main/70 leading-relaxed">{step.desc}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Common Errors & Troubleshooting Section */}
            <section className="bg-white rounded-3xl border border-surface-darker shadow-card p-6 sm:p-8 space-y-4">
              <div className="space-y-1">
                <h2 className="text-xl sm:text-2xl font-extrabold text-text-main">
                  Common Payroll Slip Errors & Compliance Traps
                </h2>
                <p className="text-xs sm:text-sm text-text-main/70">
                  Avoid common formatting errors, legal omissions, and calculation pitfalls:
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
                {COMMON_ERRORS.map((err, idx) => (
                  <div key={idx} className="p-4 rounded-2xl bg-surface border border-surface-darker/60 space-y-2">
                    <span className="text-xs font-bold text-amber-700 bg-amber-100 px-2 py-0.5 rounded-md inline-block">
                      {err.badge}
                    </span>
                    <h3 className="text-xs font-bold text-text-main">{err.title}</h3>
                    <p className="text-xs text-text-main/70 leading-relaxed">{err.desc}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Strict 10 Comprehensive FAQs Section */}
            <section className="bg-white rounded-3xl border border-surface-darker shadow-card p-6 sm:p-8 space-y-6">
              <div className="flex items-center justify-between border-b border-surface-darker pb-4">
                <div className="space-y-1">
                  <h2 className="text-lg font-bold text-text-main flex items-center gap-2">
                    <HelpCircle className="w-5 h-5 text-primary" />
                    Frequently Asked Questions
                  </h2>
                  <p className="text-xs text-text-main/60">
                    Comprehensive technical, legal, and operational answers
                  </p>
                </div>
                <span className="text-[11px] font-bold text-primary bg-primary-light px-2.5 py-1 rounded-full border border-primary/20">
                  10 Questions Answered
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {FAQS.map((faq, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-2xl bg-surface border border-surface-darker space-y-2 hover:border-primary/20 transition-all"
                  >
                    <h3 className="font-bold text-text-main text-xs sm:text-sm flex items-start gap-2">
                      <span className="text-primary font-black shrink-0">Q{idx + 1}.</span>
                      <span>{faq.question}</span>
                    </h3>
                    <p className="text-xs text-text-main/70 leading-relaxed pl-6">
                      {faq.answer}
                    </p>
                  </div>
                ))}
              </div>
            </section>
          </main>

          {/* Compact Sticky Right Sidebar Rail */}
          <aside className="lg:col-span-3 xl:col-span-2 space-y-4 lg:sticky lg:top-28">
            {/* Key Criteria Card */}
            <div className="bg-white rounded-3xl border border-surface-darker shadow-card p-3 space-y-2.5">
              <h3 className="text-[11px] font-black uppercase tracking-wider text-text-main/60 flex items-center gap-1.5">
                <Zap className="w-3.5 h-3.5 text-primary" />
                Payroll Criteria
              </h3>
              <div className="space-y-1.5 text-xs">
                <div className="p-2 rounded-xl bg-surface border border-surface-darker space-y-0.5">
                  <div className="font-bold text-text-main text-[11px]">Standard Canvas</div>
                  <div className="text-[10px] text-text-main/60 leading-tight">
                    Official A4 single-page layout with company seal box.
                  </div>
                </div>
                <div className="p-2 rounded-xl bg-surface border border-surface-darker space-y-0.5">
                  <div className="font-bold text-text-main text-[11px]">Statutory Accuracy</div>
                  <div className="text-[10px] text-text-main/60 leading-tight">
                    EPF 12%, ESI 0.75%, and Professional Tax compliance.
                  </div>
                </div>
                <div className="p-2 rounded-xl bg-surface border border-surface-darker space-y-0.5">
                  <div className="font-bold text-text-main text-[11px]">Confidential</div>
                  <div className="text-[10px] text-text-main/60 leading-tight">
                    Zero server transmission of financial or bank data.
                  </div>
                </div>
              </div>
            </div>

            {/* Related Tools Card */}
            <div className="bg-white rounded-3xl border border-surface-darker shadow-card p-3 space-y-2.5">
              <h3 className="text-[11px] font-black uppercase tracking-wider text-text-main/60 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-primary" />
                Related Tools
              </h3>
              <div className="space-y-1.5">
                <Link
                  href="/tools/income-tax-calculator-2025-26"
                  className="flex items-center justify-between p-2 rounded-xl bg-surface hover:bg-primary-light/50 border border-surface-darker hover:border-primary/30 transition-all group"
                >
                  <div className="flex items-center gap-2 min-w-0 pr-1">
                    <span className="text-[11px] font-bold text-text-main group-hover:text-primary transition-colors truncate">
                      Income Tax Calculator FY 2025-26
                    </span>
                  </div>
                  <span className="text-[9px] font-mono font-bold text-primary bg-primary-light px-1.5 py-0.5 rounded border border-primary/20 shrink-0">
                    Tax
                  </span>
                </Link>
                <Link
                  href="/tools/number-to-words-converter"
                  className="flex items-center justify-between p-2 rounded-xl bg-surface hover:bg-primary-light/50 border border-surface-darker hover:border-primary/30 transition-all group"
                >
                  <div className="flex items-center gap-2 min-w-0 pr-1">
                    <span className="text-[11px] font-bold text-text-main group-hover:text-primary transition-colors truncate">
                      Number to Words Converter
                    </span>
                  </div>
                  <span className="text-[9px] font-mono font-bold text-primary bg-primary-light px-1.5 py-0.5 rounded border border-primary/20 shrink-0">
                    Finance
                  </span>
                </Link>
                <Link
                  href="/tools/epfo-passbook-photo-resizer"
                  className="flex items-center justify-between p-2 rounded-xl bg-surface hover:bg-primary-light/50 border border-surface-darker hover:border-primary/30 transition-all group"
                >
                  <div className="flex items-center gap-2 min-w-0 pr-1">
                    <span className="text-[11px] font-bold text-text-main group-hover:text-primary transition-colors truncate">
                      EPFO Passbook Resizer
                    </span>
                  </div>
                  <span className="text-[9px] font-mono font-bold text-primary bg-primary-light px-1.5 py-0.5 rounded border border-primary/20 shrink-0">
                    PF
                  </span>
                </Link>
              </div>
            </div>

            {/* Sticky Sidebar Ad Slot */}
            <AdSlot slot="sidebar" />

            {/* Sovereign In-RAM Privacy Box */}
            <div className="bg-surface rounded-2xl border border-surface-darker p-3 space-y-1.5 text-text-main/80">
              <div className="flex items-center gap-1.5 text-xs font-bold text-primary">
                <Lock className="w-3.5 h-3.5" />
                <span>100% In-RAM Privacy</span>
              </div>
              <p className="text-[11px] leading-relaxed text-text-main/70">
                All calculations and document drafting occur strictly inside your device browser memory. Zero records, identity details, or files are sent to remote cloud servers.
              </p>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
