'use client';

import * as React from 'react';
import {
  Search,
  Server,
  Globe,
  Copy,
  Check,
  Download,
  Clock,
  ShieldCheck,
  AlertCircle,
  ExternalLink,
  ArrowRight,
  Filter,
} from 'lucide-react';

interface DnsRecord {
  name: string;
  type: string;
  data: string;
  TTL: number;
}

const TYPE_COLORS: Record<string, string> = {
  A: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
  AAAA: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
  CNAME: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
  MX: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
  TXT: 'bg-teal-500/10 text-teal-400 border-teal-500/30',
  NS: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/30',
  SOA: 'bg-rose-500/10 text-rose-400 border-rose-500/30',
  CAA: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
};

const SAMPLE_DOMAINS = ['google.com', 'cloudflare.com', 'github.com', 'wikipedia.org'];
const RECORD_TYPES = ['ALL', 'A', 'AAAA', 'CNAME', 'MX', 'TXT', 'NS', 'SOA', 'CAA'];

export function DnsLookupEngine() {
  const [domain, setDomain] = React.useState('cloudflare.com');
  const [selectedType, setSelectedType] = React.useState('ALL');
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [records, setRecords] = React.useState<DnsRecord[]>([]);
  const [responseTime, setResponseTime] = React.useState<number | null>(null);
  const [copiedIndex, setCopiedIndex] = React.useState<number | null>(null);
  const [copiedAll, setCopiedAll] = React.useState(false);

  const fetchDns = React.useCallback(async (targetDomain: string, type: string) => {
    if (!targetDomain.trim()) return;
    setLoading(true);
    setError(null);

    try {
      const res = await fetch(`/app/api/tools/dns-lookup?domain=${encodeURIComponent(targetDomain)}&type=${type}`.replace('/app', ''));
      const data = await res.json();

      if (!data.success) {
        setError(data.error || 'Failed to fetch DNS records');
        setRecords([]);
      } else {
        setRecords(data.data.records || []);
        setResponseTime(data.data.responseTimeMs || 0);
      }
    } catch (err: any) {
      setError(err.message || 'Network error occurred');
      setRecords([]);
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    fetchDns(domain, selectedType);
  }, []);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    fetchDns(domain, selectedType);
  };

  const handleCopySingle = (val: string, index: number) => {
    navigator.clipboard.writeText(val);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const handleCopyAllJson = () => {
    navigator.clipboard.writeText(JSON.stringify(records, null, 2));
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  const handleDownloadBind = () => {
    let bindText = `; Zone file export for ${domain}\n; Generated by VeriSeal Sovereign DNS Studio\n$TTL 300\n\n`;
    records.forEach((r) => {
      bindText += `${r.name.padEnd(30)} ${r.TTL.toString().padEnd(8)} IN ${r.type.padEnd(8)} ${r.data}\n`;
    });

    const blob = new Blob([bindText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${domain}-dns-zone.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const filteredRecords = React.useMemo(() => {
    if (selectedType === 'ALL') return records;
    return records.filter((r) => r.type === selectedType);
  }, [records, selectedType]);

  return (
    <div className="w-full space-y-6">
      {/* Search Bar Bar Card */}
      <div className="bg-[#12141A] border border-[#262833] rounded-2xl p-4 sm:p-6 shadow-xl">
        <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Globe className="absolute left-3.5 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              value={domain}
              onChange={(e) => setDomain(e.target.value)}
              placeholder="e.g. example.com or mail.google.com"
              className="w-full bg-[#1A1C24] border border-[#2E313D] rounded-xl pl-11 pr-4 py-3 text-white text-sm focus:outline-none focus:border-[#E6570B] focus:ring-1 focus:ring-[#E6570B] transition-colors"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="flex items-center justify-center gap-2 bg-[#E6570B] hover:bg-[#d04e0a] text-white font-medium px-6 py-3 rounded-xl text-sm transition-all shadow-lg shadow-[#E6570B]/20 disabled:opacity-50"
          >
            {loading ? (
              <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            ) : (
              <>
                <Search className="w-4 h-4" />
                <span>Resolve DNS</span>
              </>
            )}
          </button>
        </form>

        {/* Quick Sample Links */}
        <div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-gray-400">
          <span>Quick samples:</span>
          {SAMPLE_DOMAINS.map((sample) => (
            <button
              key={sample}
              type="button"
              onClick={() => {
                setDomain(sample);
                fetchDns(sample, selectedType);
              }}
              className="px-2 py-0.5 rounded-md bg-[#1A1C24] border border-[#2E313D] hover:border-[#E6570B] hover:text-[#E6570B] transition-colors"
            >
              {sample}
            </button>
          ))}
        </div>
      </div>

      {/* Record Filter Tabs & Export Actions */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 bg-[#12141A] border border-[#262833] rounded-2xl p-4">
        <div className="flex items-center gap-1.5 overflow-x-auto w-full sm:w-auto pb-2 sm:pb-0 scrollbar-thin">
          <Filter className="w-4 h-4 text-gray-500 ml-1 mr-1 shrink-0" />
          {RECORD_TYPES.map((type) => (
            <button
              key={type}
              onClick={() => setSelectedType(type)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all shrink-0 ${
                selectedType === type
                  ? 'bg-[#E6570B] text-white shadow-sm'
                  : 'bg-[#1A1C24] text-gray-400 hover:text-white hover:bg-[#222530]'
              }`}
            >
              {type}
            </button>
          ))}
        </div>

        {records.length > 0 && (
          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={handleCopyAllJson}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-[#1A1C24] border border-[#2E313D] hover:border-gray-500 rounded-lg text-xs text-gray-300 font-medium transition-colors"
              title="Copy JSON representation"
            >
              {copiedAll ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedAll ? 'Copied' : 'JSON'}</span>
            </button>
            <button
              onClick={handleDownloadBind}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-[#1A1C24] border border-[#2E313D] hover:border-[#E6570B] rounded-lg text-xs text-gray-300 hover:text-[#E6570B] font-medium transition-colors"
              title="Download BIND zone file"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Zone File</span>
            </button>
          </div>
        )}
      </div>

      {/* Metrics Banner */}
      {responseTime !== null && !error && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="bg-[#12141A] border border-[#262833] rounded-xl p-3">
            <span className="text-gray-400 text-xs">Total Records</span>
            <p className="text-xl font-bold text-white mt-0.5">{records.length}</p>
          </div>
          <div className="bg-[#12141A] border border-[#262833] rounded-xl p-3">
            <span className="text-gray-400 text-xs">Filtered Records</span>
            <p className="text-xl font-bold text-[#E6570B] mt-0.5">{filteredRecords.length}</p>
          </div>
          <div className="bg-[#12141A] border border-[#262833] rounded-xl p-3">
            <span className="text-gray-400 text-xs">Latency (DoH)</span>
            <div className="flex items-center gap-1 mt-0.5">
              <Clock className="w-4 h-4 text-emerald-400" />
              <p className="text-lg font-bold text-emerald-400">{responseTime} ms</p>
            </div>
          </div>
          <div className="bg-[#12141A] border border-[#262833] rounded-xl p-3">
            <span className="text-gray-400 text-xs">Resolver</span>
            <p className="text-sm font-semibold text-gray-300 mt-1 truncate">Cloudflare 1.1.1.1</p>
          </div>
        </div>
      )}

      {/* Error state */}
      {error && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-2xl p-4 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
          <div>
            <h4 className="text-sm font-semibold text-red-400">DNS Resolution Error</h4>
            <p className="text-xs text-red-300/80 mt-1">{error}</p>
          </div>
        </div>
      )}

      {/* Records Table */}
      <div className="bg-[#12141A] border border-[#262833] rounded-2xl overflow-hidden shadow-xl">
        <div className="px-5 py-4 border-b border-[#262833] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Server className="w-4 h-4 text-[#E6570B]" />
            <h3 className="text-sm font-semibold text-white">DNS Records Table</h3>
          </div>
          <span className="text-xs text-gray-500">{filteredRecords.length} records found</span>
        </div>

        {loading ? (
          <div className="py-16 text-center space-y-3">
            <div className="w-8 h-8 border-3 border-[#E6570B]/30 border-t-[#E6570B] rounded-full animate-spin mx-auto" />
            <p className="text-sm text-gray-400">Querying authoritative DNS root servers...</p>
          </div>
        ) : filteredRecords.length === 0 ? (
          <div className="py-16 text-center text-gray-500 text-sm">
            No {selectedType === 'ALL' ? '' : selectedType} records found for this domain.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-[#262833] text-[11px] font-semibold text-gray-400 uppercase tracking-wider bg-[#161822]">
                  <th className="py-3 px-4">Type</th>
                  <th className="py-3 px-4">Host / Name</th>
                  <th className="py-3 px-4">Value / Target</th>
                  <th className="py-3 px-4">TTL</th>
                  <th className="py-3 px-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#262833] text-xs">
                {filteredRecords.map((r, idx) => {
                  const badgeClass =
                    TYPE_COLORS[r.type] || 'bg-gray-500/10 text-gray-400 border-gray-500/30';
                  return (
                    <tr key={`${r.type}-${r.data}-${idx}`} className="hover:bg-[#181A24] transition-colors">
                      <td className="py-3 px-4 whitespace-nowrap">
                        <span className={`px-2 py-0.5 rounded border text-[11px] font-bold ${badgeClass}`}>
                          {r.type}
                        </span>
                      </td>
                      <td className="py-3 px-4 text-gray-300 font-mono text-[11px] max-w-[180px] truncate">
                        {r.name}
                      </td>
                      <td className="py-3 px-4 font-mono text-[11px] text-white break-all max-w-[340px]">
                        {r.data}
                      </td>
                      <td className="py-3 px-4 text-gray-400 whitespace-nowrap">
                        {r.TTL}s{' '}
                        <span className="text-[10px] text-gray-500">
                          ({r.TTL >= 60 ? `${Math.round(r.TTL / 60)}m` : `${r.TTL}s`})
                        </span>
                      </td>
                      <td className="py-3 px-4 text-right whitespace-nowrap">
                        <button
                          onClick={() => handleCopySingle(r.data, idx)}
                          className="p-1.5 rounded-lg bg-[#1A1C24] hover:bg-[#252836] border border-[#2E313D] text-gray-400 hover:text-white transition-colors"
                          title="Copy record value"
                        >
                          {copiedIndex === idx ? (
                            <Check className="w-3.5 h-3.5 text-green-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
