import { FaqItem, HowItWorksStep, SupportedDocItem, TrustBadgeItem } from '@/types';

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://veri-seal.vercel.app';

export const SITE_CONFIG = {
  name: 'VeriSeal',
  tagline: 'Verify government PDFs instantly. Made for India.',
  description:
    'Instantly verify digital signatures on e-Aadhaar, community certificate, nativity certificate, PAN card, DigiLocker PDFs. Fix yellow question mark. Free, no signup, files never stored. Supports Tamil Nadu, AP, Telangana, Karnataka, Kerala government certificates.',
  url: SITE_URL,
  upiId: 'veriseal@upi',
  supportEmail: 'support@veriseal.in',
  author: 'VeriSeal Team',
  verifiedCountDefault: 4215,
  maxFileSizeMB: 25,
};

export const STATES = [
  { id: 'all-india', name: 'All India', code: 'IN', count: 7 },
  { id: 'tamil-nadu', name: 'Tamil Nadu', code: 'TN', count: 14 },
  { id: 'ap-telangana', name: 'AP & Telangana', code: 'AP/TS', count: 5 },
  { id: 'karnataka', name: 'Karnataka', code: 'KA', count: 3 },
  { id: 'kerala', name: 'Kerala', code: 'KL', count: 3 },
  { id: 'more-states', name: 'More States', code: 'IN+', count: 8 },
] as const;

export const SUPPORTED_DOCS: SupportedDocItem[] = [
  // ALL INDIA
  {
    id: 'uidai-aadhaar',
    name: 'e-Aadhaar (UIDAI)',
    state: 'All India',
    category: 'all-india',
    portal: 'UIDAI myAadhaar',
    portalUrl: 'https://myaadhaar.uidai.gov.in',
    description: 'Digitally signed by Unique Identification Authority of India (UIDAI). Supports password-protected PDF.',
    isPasswordProtectedSupported: true,
    code: 'AADHAAR',
  },
  {
    id: 'pan-nsdl',
    name: 'PAN Card PDF (Protean/NSDL)',
    state: 'All India',
    category: 'all-india',
    portal: 'Protean / UTIITSL',
    portalUrl: 'https://www.onlineservices.nsdl.com',
    description: 'Instant e-PAN signed with official Income Tax / NSDL certificate.',
    isPasswordProtectedSupported: true,
    code: 'PAN',
  },
  {
    id: 'digilocker-general',
    name: 'DigiLocker Issued Documents',
    state: 'All India',
    category: 'all-india',
    portal: 'DigiLocker India',
    portalUrl: 'https://www.digilocker.gov.in',
    description: 'All legally recognized documents issued and signed by DigiLocker Authority.',
    isPasswordProtectedSupported: false,
    code: 'DIGILOCKER',
  },
  {
    id: 'itr-v-acknowledgement',
    name: 'ITR-V (Income Tax Return)',
    state: 'All India',
    category: 'all-india',
    portal: 'Income Tax e-Filing',
    portalUrl: 'https://www.incometax.gov.in',
    description: 'Income Tax Department signed acknowledgement receipt.',
    isPasswordProtectedSupported: true,
    code: 'ITR_V',
  },
  {
    id: 'tds-form-16',
    name: 'Form 16 / 16A',
    state: 'All India',
    category: 'all-india',
    portal: 'TRACES CPC',
    portalUrl: 'https://www.tdscpc.gov.in',
    description: 'Employer TDS certificate digitally signed under CCA India hierarchy.',
    isPasswordProtectedSupported: true,
    code: 'FORM16',
  },
  {
    id: 'digilocker-dl',
    name: 'Driving Licence (DigiLocker)',
    state: 'All India',
    category: 'all-india',
    portal: 'MoRTH Parivahan',
    portalUrl: 'https://parivahan.gov.in',
    description: 'Ministry of Road Transport and Highways signed driving licence PDF.',
    isPasswordProtectedSupported: false,
    code: 'DL',
  },
  {
    id: 'digilocker-rc',
    name: 'Vehicle RC (DigiLocker)',
    state: 'All India',
    category: 'all-india',
    portal: 'MoRTH Vahan',
    portalUrl: 'https://parivahan.gov.in',
    description: 'Vehicle Registration Certificate with CCA cryptographic signature.',
    isPasswordProtectedSupported: false,
    code: 'RC',
  },

  // TAMIL NADU
  {
    id: 'tn-community',
    name: 'Community Certificate (BC/MBC/SC/ST)',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Revenue administration signed caste certificate with QR and digital stamp.',
    isPasswordProtectedSupported: false,
    code: 'TN_COMMUNITY',
  },
  {
    id: 'tn-nativity',
    name: 'Nativity Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Official residency verification issued by Tahsildar / Revenue Department.',
    isPasswordProtectedSupported: false,
    code: 'TN_NATIVITY',
  },
  {
    id: 'tn-income',
    name: 'Income Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Annual family income certificate signed under CCA NIC hierarchy.',
    isPasswordProtectedSupported: false,
    code: 'TN_INCOME',
  },
  {
    id: 'tn-first-graduate',
    name: 'First Graduate Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Higher education tuition concession certificate issued by Tahsildar.',
    isPasswordProtectedSupported: false,
    code: 'TN_FIRST_GRAD',
  },
  {
    id: 'tn-birth-crstn',
    name: 'Birth Certificate (CRSTN)',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'Civil Registration System (CRSTN)',
    portalUrl: 'https://crstn.org/birth_death_tn/',
    description: 'Sanitary Inspector / Health Officer digitally signed birth certificate.',
    isPasswordProtectedSupported: false,
    code: 'TN_BIRTH',
  },
  {
    id: 'tn-death-crstn',
    name: 'Death Certificate (CRSTN)',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'Civil Registration System (CRSTN)',
    portalUrl: 'https://crstn.org/birth_death_tn/',
    description: 'Officially validated digital death certificate with NIC signature.',
    isPasswordProtectedSupported: false,
    code: 'TN_DEATH',
  },
  {
    id: 'tn-legal-heir',
    name: 'Legal Heir Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Tahsildar signed legal succession certificate.',
    isPasswordProtectedSupported: false,
    code: 'TN_LEGAL_HEIR',
  },
  {
    id: 'tn-residence',
    name: 'Residence Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Proof of residential address within Tamil Nadu state jurisdiction.',
    isPasswordProtectedSupported: false,
    code: 'TN_RESIDENCE',
  },
  {
    id: 'tn-obc',
    name: 'OBC Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Other Backward Class certificate for Central Government employment & UPSC.',
    isPasswordProtectedSupported: false,
    code: 'TN_OBC',
  },
  {
    id: 'tn-deserted-woman',
    name: 'Deserted Woman Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Revenue department verification for social welfare support.',
    isPasswordProtectedSupported: false,
    code: 'TN_DESERTED_WOMAN',
  },
  {
    id: 'tn-intercaste',
    name: 'Inter-caste Marriage Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Social welfare department incentive certification.',
    isPasswordProtectedSupported: false,
    code: 'TN_INTERCASTE',
  },
  {
    id: 'tn-agri-income',
    name: 'Agricultural Income Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Revenue authority assessment of agricultural land yield and income.',
    isPasswordProtectedSupported: false,
    code: 'TN_AGRI_INCOME',
  },
  {
    id: 'tn-widow',
    name: 'Widow Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Government pension and welfare benefits validation document.',
    isPasswordProtectedSupported: false,
    code: 'TN_WIDOW',
  },
  {
    id: 'tn-solvency',
    name: 'Solvency Certificate',
    state: 'Tamil Nadu',
    category: 'tamil-nadu',
    portal: 'TNeGA / e-District',
    portalUrl: 'https://tnesevai.tn.gov.in',
    description: 'Financial stability document for government contracts and tenders.',
    isPasswordProtectedSupported: false,
    code: 'TN_SOLVENCY',
  },

  // ANDHRA PRADESH & TELANGANA
  {
    id: 'apts-caste',
    name: 'Caste Certificate (MeeSeva)',
    state: 'AP & Telangana',
    category: 'ap-telangana',
    portal: 'MeeSeva Portal',
    portalUrl: 'https://onlineap.meeseva.gov.in',
    description: 'Integrated caste validation issued by Andhra Pradesh / Telangana MeeSeva.',
    isPasswordProtectedSupported: false,
    code: 'APTS_CASTE',
  },
  {
    id: 'apts-income',
    name: 'Income Certificate (MeeSeva)',
    state: 'AP & Telangana',
    category: 'ap-telangana',
    portal: 'MeeSeva Portal',
    portalUrl: 'https://onlineap.meeseva.gov.in',
    description: 'Digitally signed household income certificate for scholarship & welfare.',
    isPasswordProtectedSupported: false,
    code: 'APTS_INCOME',
  },
  {
    id: 'apts-residence',
    name: 'Residence Certificate (MeeSeva)',
    state: 'AP & Telangana',
    category: 'ap-telangana',
    portal: 'MeeSeva Portal',
    portalUrl: 'https://onlineap.meeseva.gov.in',
    description: 'Domicile proof signed by Mandal Revenue Officer (MRO).',
    isPasswordProtectedSupported: false,
    code: 'APTS_RESIDENCE',
  },
  {
    id: 'apts-birth',
    name: 'Birth Certificate (MeeSeva / GHMC)',
    state: 'AP & Telangana',
    category: 'ap-telangana',
    portal: 'MeeSeva / GHMC',
    portalUrl: 'https://onlineap.meeseva.gov.in',
    description: 'Municipal administration signed birth registration document.',
    isPasswordProtectedSupported: false,
    code: 'APTS_BIRTH',
  },
  {
    id: 'apts-death',
    name: 'Death Certificate (MeeSeva / GHMC)',
    state: 'AP & Telangana',
    category: 'ap-telangana',
    portal: 'MeeSeva / GHMC',
    portalUrl: 'https://onlineap.meeseva.gov.in',
    description: 'Digital death record signed with official government PKI certificate.',
    isPasswordProtectedSupported: false,
    code: 'APTS_DEATH',
  },

  // KARNATAKA
  {
    id: 'ka-caste-income',
    name: 'Caste & Income Certificate (Nadakacheri)',
    state: 'Karnataka',
    category: 'karnataka',
    portal: 'Nadakacheri (Atalji Janasnehi Kendra)',
    portalUrl: 'https://nadakacheri.karnataka.gov.in',
    description: 'Revenue department certificate signed by Tahsildar / Revenue Inspector.',
    isPasswordProtectedSupported: false,
    code: 'KA_CASTE_INCOME',
  },
  {
    id: 'ka-birth-ejanma',
    name: 'Birth Certificate (eJanma)',
    state: 'Karnataka',
    category: 'karnataka',
    portal: 'e-Janma Karnataka',
    portalUrl: 'https://ejanma.karnataka.gov.in',
    description: 'Vital statistics department cryptographic signature birth record.',
    isPasswordProtectedSupported: false,
    code: 'KA_BIRTH',
  },
  {
    id: 'ka-death-ejanma',
    name: 'Death Certificate (eJanma)',
    state: 'Karnataka',
    category: 'karnataka',
    portal: 'e-Janma Karnataka',
    portalUrl: 'https://ejanma.karnataka.gov.in',
    description: 'Official registrar certified digital death certificate.',
    isPasswordProtectedSupported: false,
    code: 'KA_DEATH',
  },

  // KERALA
  {
    id: 'kl-birth-sevana',
    name: 'Birth Certificate (Sevana/LSGD)',
    state: 'Kerala',
    category: 'kerala',
    portal: 'Sevana Civil Registration (LSGD Kerala)',
    portalUrl: 'https://cr.lsgkerala.gov.in',
    description: 'Local Self Government Department certified birth certificate.',
    isPasswordProtectedSupported: false,
    code: 'KL_BIRTH',
  },
  {
    id: 'kl-death-sevana',
    name: 'Death Certificate (Sevana/LSGD)',
    state: 'Kerala',
    category: 'kerala',
    portal: 'Sevana Civil Registration (LSGD Kerala)',
    portalUrl: 'https://cr.lsgkerala.gov.in',
    description: 'Registrar of Births & Deaths digitally signed death certificate.',
    isPasswordProtectedSupported: false,
    code: 'KL_DEATH',
  },
  {
    id: 'kl-community-edistrict',
    name: 'Community Certificate (e-District Kerala)',
    state: 'Kerala',
    category: 'kerala',
    portal: 'Kerala e-District Portal',
    portalUrl: 'https://edistrict.kerala.gov.in',
    description: 'Revenue officer digital signature under NIC Kerala CA.',
    isPasswordProtectedSupported: false,
    code: 'KL_COMMUNITY',
  },

  // MORE STATES
  {
    id: 'up-edistrict',
    name: 'Uttar Pradesh e-District Certificates',
    state: 'Uttar Pradesh',
    category: 'more-states',
    portal: 'UP eDistrict',
    portalUrl: 'https://edistrict.up.gov.in',
    description: 'Niwas, Jati, and Aay praman patra issued by UP government.',
    isPasswordProtectedSupported: false,
    code: 'UP_EDISTRICT',
  },
  {
    id: 'mh-aaplesarkar',
    name: 'Maharashtra Aaple Sarkar Certificates',
    state: 'Maharashtra',
    category: 'more-states',
    portal: 'Aaple Sarkar Portal',
    portalUrl: 'https://aaplesarkar.mahaonline.gov.in',
    description: 'Domicile, Caste, and Non-Creamy Layer certificates.',
    isPasswordProtectedSupported: false,
    code: 'MH_CERT',
  },
];

export const HOW_IT_WORKS: HowItWorksStep[] = [
  {
    step: 1,
    title: 'Upload Your PDF',
    description:
      'Drag and drop or click to upload your government PDF. We accept Aadhaar, community certificate, nativity, PAN, DigiLocker and all CCA India signed documents.',
    badge: 'Step 1 • Instant & Private',
  },
  {
    step: 2,
    title: 'We Verify the Signature',
    description:
      "Our engine checks the digital signature against India's official CCA root certificate hierarchy — NIC, eMudhra, Capricorn and all licensed CAs.",
    badge: 'Step 2 • RCAI Trust Chain',
  },
  {
    step: 3,
    title: 'Download Verified Copy',
    description:
      'Get a PDF with a permanent visible green tick that shows on any computer, phone or printout without any Adobe configuration.',
    badge: 'Step 3 • Permanent Green Tick',
  },
];

export const TRUST_BADGES: TrustBadgeItem[] = [
  {
    icon: 'Lock',
    title: 'Files Never Stored',
    description:
      'Your PDF is processed entirely in memory. We never write your file to disk or store it on any server. Deleted immediately after verification.',
  },
  {
    icon: 'Zap',
    title: 'No Account Required',
    description:
      'Start verifying instantly. No signup, no email, no phone number needed for basic use.',
  },
  {
    icon: 'ShieldCheck',
    title: 'CCA India Trust Chain',
    description:
      "We verify against India's official Root Certifying Authority (RCAI) — the same chain used by NIC, eMudhra, Capricorn and all licensed Indian CAs.",
  },
  {
    icon: 'Smartphone',
    title: 'Works on Any Device',
    description:
      'Browser-based tool works on Android, iPhone, Windows, Mac and Chromebook. No app or software installation needed.',
  },
];

export const FAQ: FaqItem[] = [
  {
    question: 'Why does my government PDF show a yellow question mark?',
    answer:
      "Indian government PDFs are digitally signed using certificates from NIC, eMudhra, or other CCA India licensed authorities. Adobe Acrobat and most PDF viewers don't include India's Root Certifying Authority (RCAI) in their default trusted certificate store. So even though the signature is completely valid and legally recognised under the Information Technology Act 2000, your PDF viewer shows a yellow question mark because it cannot automatically verify the issuer. VeriSeal checks your PDF against the actual CCA India trust hierarchy and gives you a copy with a permanent green tick visible on any device.",
  },
  {
    question: 'Is my document safe? Do you store my PDF?',
    answer:
      'Your PDF is processed entirely in memory during verification. We never write your file to disk, never store it on our servers, and never share it with any third party. The file is deleted from memory immediately after verification is complete. You can also verify this by checking our open source backend code.',
  },
  {
    question: 'Which documents does VeriSeal support?',
    answer:
      'VeriSeal supports any PDF digitally signed under India’s CCA certificate hierarchy. This includes e-Aadhaar, PAN card, DigiLocker documents, ITR-V, Form 16, and all state government certificates from Tamil Nadu e-District, AP and Telangana MeeSeva, Karnataka Nadakacheri and eJanma, Kerala Sevana portal, and more.',
  },
  {
    question: 'My Aadhaar PDF is password protected. Will it work?',
    answer:
      'Yes. Enter your Aadhaar password (first four letters of your name in capital letters followed by your birth year, for example RAMA1995) in the password field that appears after you upload your e-Aadhaar PDF. We decrypt it in memory, verify the signature, and return a verified copy.',
  },
  {
    question: 'What is the difference between "Signature Valid" and "Signature Unknown"?',
    answer:
      'Signature Valid means the document is genuinely issued by the government authority and has not been modified. Signature Unknown means your PDF viewer cannot verify the certificate chain — this is a viewer configuration issue, not a problem with your document. Signature Invalid means the document may have been tampered with or re-saved after signing.',
  },
  {
    question: 'Does this work on mobile?',
    answer:
      'Yes. VeriSeal is fully mobile responsive and works on any Android or iOS browser. No app installation required. Simply open veriseal.in on your phone browser, upload your PDF and verify instantly.',
  },
];
