// Voice-to-Text & Audio Transcription Processing Utilities
// Web Audio API Resampling, Timecode Formatting, Subtitle Generation (SRT/VTT), and Disfluency Cleaning

export interface TranscriptWord {
  word: string;
  start: number; // seconds
  end: number;   // seconds
  confidence?: number;
}

export interface TranscriptSegment {
  id: number | string;
  start: number; // in seconds
  end: number;   // in seconds
  text: string;
  speaker?: string;
  words?: TranscriptWord[];
}

/**
 * Decodes any browser-supported audio/video container (MP3, WAV, M4A, WEBM, MP4, FLAC, OGG)
 * into a single-channel 16,000 Hz Float32Array PCM buffer required by OpenAI Whisper models.
 */
export async function decodeAudioToPCM16k(fileOrBlob: Blob): Promise<{ pcm: Float32Array; duration: number }> {
  const arrayBuffer = await fileOrBlob.arrayBuffer();

  const AudioContextClass = window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
  if (!AudioContextClass) {
    throw new Error('Web Audio API is not supported in this browser.');
  }

  const audioCtx = new AudioContextClass();

  try {
    const audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);
    const duration = audioBuffer.duration;
    const targetSampleRate = 16000;

    // Use OfflineAudioContext for rapid, glitch-free hardware resampling to 16kHz mono
    const offlineCtx = new OfflineAudioContext(
      1,
      Math.max(1, Math.ceil(duration * targetSampleRate)),
      targetSampleRate
    );

    const source = offlineCtx.createBufferSource();
    source.buffer = audioBuffer;
    source.connect(offlineCtx.destination);
    source.start(0);

    const resampledBuffer = await offlineCtx.startRendering();
    const pcm = resampledBuffer.getChannelData(0);

    return { pcm, duration };
  } finally {
    audioCtx.close().catch(() => {});
  }
}

/**
 * Formats raw seconds into human-readable or standards-compliant timecodes.
 * - 'display': "01:23" or "01:02:03"
 * - 'srt': "00:01:23,450" (comma millisecond separator)
 * - 'vtt': "00:01:23.450" (dot millisecond separator)
 */
export function formatTimecode(
  seconds: number,
  format: 'display' | 'srt' | 'vtt' = 'display'
): string {
  if (isNaN(seconds) || seconds < 0) seconds = 0;

  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);

  const pad = (num: number, size = 2) => String(num).padStart(size, '0');

  if (format === 'srt') {
    return `${pad(hours)}:${pad(minutes)}:${pad(secs)},${pad(ms, 3)}`;
  }

  if (format === 'vtt') {
    return `${pad(hours)}:${pad(minutes)}:${pad(secs)}.${pad(ms, 3)}`;
  }

  // 'display'
  if (hours > 0) {
    return `${pad(hours)}:${pad(minutes)}:${pad(secs)}`;
  }
  return `${pad(minutes)}:${pad(secs)}`;
}

/**
 * Builds standard SubRip (.SRT) subtitle file content
 * Ready for YouTube, Premiere Pro, DaVinci Resolve, and CapCut.
 */
export function generateSRT(segments: TranscriptSegment[]): string {
  return segments
    .filter((s) => s.text && s.text.trim().length > 0)
    .map((seg, idx) => {
      const seq = idx + 1;
      const start = formatTimecode(seg.start, 'srt');
      const end = formatTimecode(seg.end, 'srt');
      const speakerPrefix = seg.speaker ? `[${seg.speaker}] ` : '';
      return `${seq}\n${start} --> ${end}\n${speakerPrefix}${seg.text.trim()}\n`;
    })
    .join('\n');
}

/**
 * Builds standard WebVTT (.VTT) subtitle file content
 */
export function generateVTT(segments: TranscriptSegment[]): string {
  const header = 'WEBVTT - Generated by Kagazo Voice Studio (https://kagazo.in)\n\n';
  const cues = segments
    .filter((s) => s.text && s.text.trim().length > 0)
    .map((seg) => {
      const start = formatTimecode(seg.start, 'vtt');
      const end = formatTimecode(seg.end, 'vtt');
      const speakerPrefix = seg.speaker ? `<v ${seg.speaker}>` : '';
      const speakerSuffix = seg.speaker ? `</v>` : '';
      return `${start} --> ${end}\n${speakerPrefix}${seg.text.trim()}${speakerSuffix}\n`;
    })
    .join('\n');

  return header + cues;
}

/**
 * Builds formatted text with bracketed timecodes
 */
export function generateTimestampedText(segments: TranscriptSegment[]): string {
  return segments
    .map((seg) => {
      const time = `[${formatTimecode(seg.start, 'display')} - ${formatTimecode(seg.end, 'display')}]`;
      const speaker = seg.speaker ? ` (${seg.speaker})` : '';
      return `${time}${speaker} ${seg.text.trim()}`;
    })
    .join('\n\n');
}

/**
 * Builds clean continuous prose text
 */
export function generateCleanText(segments: TranscriptSegment[]): string {
  return segments
    .map((s) => s.text.trim())
    .filter(Boolean)
    .join(' ');
}

/**
 * 1-Click Filler Word / Disfluency Cleaner
 * Removes verbal ticks (um, uh, like, you know, er, ah, hmm)
 */
export function cleanFillerWords(text: string): string {
  return text
    // remove compound fillers
    .replace(/\b(you know|i mean|sort of|kind of)\b/gi, '')
    // remove single word fillers
    .replace(/\b(um|uh|erm|er|ah|ahh|hmm|like)\b/gi, '')
    // cleanup orphaned punctuation and extra spaces
    .replace(/\s+,/g, ',')
    .replace(/\s+\./g, '.')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

/**
 * Calculates audio & speaking cadence metrics
 */
export function calculateTranscriptMetrics(segments: TranscriptSegment[], durationSeconds: number) {
  const wordCount = segments.reduce((acc, seg) => {
    return acc + seg.text.trim().split(/\s+/).filter(Boolean).length;
  }, 0);

  const minutes = Math.max(durationSeconds / 60, 0.1);
  const wpm = Math.round(wordCount / minutes);

  let paceDescription = 'Natural Cadence';
  if (wpm < 120) paceDescription = 'Slow / Deliberate';
  else if (wpm > 175) paceDescription = 'Fast / High-Energy';

  return {
    wordCount,
    durationFormatted: formatTimecode(durationSeconds, 'display'),
    wpm,
    paceDescription,
    segmentCount: segments.length,
  };
}
