/**
 * Kagazo Master Tools Catalog & Registry.
 * Single source of truth for all public utilities, exam resizers, and document tools.
 * Powers the /tools directory, search index, Navbar mega-menu, and Sitemap.
 */

export type ToolCategoryId =
  | 'exam_photos'
  | 'passport_visa'
  | 'pdf_tools'
  | 'media_studio'
  | 'developer_code'
  | 'network_webmaster'
  | 'text_speech'
  | 'communication_qr'
  | 'security_identity'
  | 'calculators_finance'
  | 'print_cybercafe';

export type FormatTag =
  | 'PDF'
  | 'IMAGE'
  | 'CODE'
  | 'URL'
  | 'TEXT'
  | 'QR'
  | 'SECURITY'
  | 'CALC'
  | 'PRINT';

export interface ToolItem {
  id: string;
  slug: string;
  name: string;
  category: ToolCategoryId;
  categoryLabel: string;
  shortDesc: string;
  badge?: string;
  formatTag?: FormatTag;
  examTags: string[];
  featuredInNav?: boolean;
  priorityOrder: number;
  authorityLogo?: string;
  authorityName?: string;
}

export interface ToolCategory {
  id: ToolCategoryId;
  label: string;
  description: string;
  iconName: string;
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: 'exam_photos',
    label: 'Exam & Recruitment Photos',
    description: 'Auto-pad undersized scans, cap oversized images, and format declarations to exact portal rules.',
    iconName: 'Camera',
  },
  {
    id: 'passport_visa',
    label: 'Passport & Visa Photo Lab',
    description: 'Standard biometric photo sizing, background whitening, and face-align checks for 50+ countries.',
    iconName: 'UserSquare2',
  },
  {
    id: 'pdf_tools',
    label: 'PDF Utilities & Compressors',
    description: 'Compress certificates to 200KB/100KB, merge marksheets, split, unlock, and convert documents.',
    iconName: 'FileDown',
  },
  {
    id: 'media_studio',
    label: 'Image & Media Studio',
    description: 'Client-side photo compression, resizing, format conversion, DPI adjustment, and YouTube grabber.',
    iconName: 'ImageIcon',
  },
  {
    id: 'developer_code',
    label: 'Developer & Code Studio',
    description: 'Format JSON, minify CSS/JS/HTML, convert Markdown/HTML, and encode Base64 in-browser.',
    iconName: 'Code',
  },
  {
    id: 'network_webmaster',
    label: 'Network & Webmaster Health',
    description: 'Lookup DNS records, test SSL certs, query WHOIS, inspect IP geolocation, and check HTTP redirects.',
    iconName: 'Globe',
  },
  {
    id: 'text_speech',
    label: 'Text, Speech & Content',
    description: 'Text-to-speech audio player, word and character counters, case converters, and text cleaners.',
    iconName: 'AlignLeft',
  },
  {
    id: 'communication_qr',
    label: 'Communication & QR Lab',
    description: 'Generate custom styled QR codes, barcodes, and pre-filled click-to-chat links for WhatsApp & Telegram.',
    iconName: 'QrCode',
  },
  {
    id: 'security_identity',
    label: 'Security, Hash & Identity',
    description: 'Cryptographically secure passwords, SHA/MD5 hashing, UUID v4 generation, and masked Aadhaar protection.',
    iconName: 'ShieldCheck',
  },
  {
    id: 'calculators_finance',
    label: 'Calculators & Finance',
    description: 'Calculate income tax for FY 2025-26, salary breakdown, age calculations, EMI, and currency conversions.',
    iconName: 'Calculator',
  },
  {
    id: 'print_cybercafe',
    label: 'Print, PVC & Cyber Cafe Lab',
    description: '5-in-1 A4 gang sheets, Epson L805 PVC card trays, 4×6 passport sheets, and fast WhatsApp doc print prep.',
    iconName: 'Printer',
  },
];

export const TOOLS_CATALOG: ToolItem[] = [
  // -------------------------------------------------------------
  // Category 1: PDF Compressors
  // -------------------------------------------------------------
  {
    id: 'pdf-compressor-master',
    slug: '/tools/pdf-compressor',
    name: 'Master PDF Compressor',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Compress any PDF to exact custom KB targets with batch processing and in-memory privacy.',
    badge: '100% FREE',
    examTags: ['All India', 'UPSC', 'SSC', 'TNPSC', 'State PSC'],
    featuredInNav: true,
    priorityOrder: 1,
  },
  {
    id: 'compress-pdf-200kb',
    slug: '/tools/compress-pdf-to-200kb',
    name: 'Compress PDF to 200KB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Strictly compress certificates under 200KB for TNPSC OTR, UPSC, and SSC recruitment portals.',
    badge: 'MOST POPULAR',
    examTags: ['TNPSC', 'UPSC', 'SSC', 'Police', 'High Court'],
    featuredInNav: true,
    priorityOrder: 2,
  },
  {
    id: 'compress-pdf-100kb',
    slug: '/tools/compress-pdf-to-100kb',
    name: 'Compress PDF to 100KB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Ultra-efficient compression to squeeze multi-page documents strictly below 100KB.',
    badge: 'STRICT LIMIT',
    examTags: ['Scholarships', 'State PSC', 'Universities', 'BPSC'],
    featuredInNav: true,
    priorityOrder: 3,
  },
  {
    id: 'compress-pdf-300kb',
    slug: '/tools/compress-pdf-to-300kb',
    name: 'Compress PDF to 300KB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Standard compression for UPSC Civil Services ORA portal educational qualification proof.',
    badge: 'UPSC PRESET',
    examTags: ['UPSC', 'IAS/IPS', 'Judiciary', 'High Court'],
    featuredInNav: true,
    priorityOrder: 4,
  },
  {
    id: 'compress-pdf-500kb',
    slug: '/tools/compress-pdf-to-500kb',
    name: 'Compress PDF to 500KB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Ideal for multi-page degree certificates and consolidated semester marksheets.',
    badge: 'MULTI-PAGE',
    examTags: ['Banking', 'IBPS', 'SBI', 'Staff Selection'],
    featuredInNav: true,
    priorityOrder: 5,
  },
  {
    id: 'compress-pdf-1mb',
    slug: '/tools/compress-pdf-to-1mb',
    name: 'Compress PDF to 1MB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Compress PDF files strictly under 1MB for email attachments, passport seva, and job portals.',
    badge: 'EMAIL 1MB',
    examTags: ['Email', 'Passport Seva', 'Visas', 'Resumes'],
    featuredInNav: true,
    priorityOrder: 5.1,
  },
  {
    id: 'compress-pdf-2mb',
    slug: '/tools/compress-pdf-to-2mb',
    name: 'Compress PDF to 2MB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Compress heavy multi-page documents strictly under 2MB for court e-filing and legal portals.',
    badge: 'LEGAL 2MB',
    examTags: ['Court e-Filing', 'Legal', 'MCA', 'Tenders'],
    featuredInNav: true,
    priorityOrder: 5.2,
  },
  {
    id: 'compress-pdf-5mb',
    slug: '/tools/compress-pdf-to-5mb',
    name: 'Compress PDF to 5MB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Compress heavy university thesis, e-tender documents, and portfolios strictly under 5MB.',
    badge: 'THESIS 5MB',
    examTags: ['PhD Thesis', 'Dissertation', 'GeM Tenders', 'Portfolios', 'Shodhganga'],
    featuredInNav: true,
    priorityOrder: 5.3,
  },
  {
    id: 'compress-pdf-10mb',
    slug: '/tools/compress-pdf-to-10mb',
    name: 'Compress PDF to 10MB',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Reduce large annual reports, scanned book archives, and engineering drawings strictly under 10MB.',
    badge: 'REPORTS 10MB',
    examTags: ['Annual Reports', 'CAD Drawings', 'Scanned Books', 'Blueprints', 'Enterprise'],
    featuredInNav: true,
    priorityOrder: 5.4,
  },
  {
    id: 'govt-exam-compressor',
    slug: '/tools/government-exam-pdf-compressor',
    name: 'Govt Exam PDF Compressor Hub',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: '1-click exam presets with automatic DPI, color normalization, and compliance badges.',
    badge: 'ALL EXAMS',
    examTags: ['UPSC', 'SSC', 'TNPSC', 'NEET', 'Railway RRB'],
    featuredInNav: true,
    priorityOrder: 6,
  },
  {
    id: 'tnpsc-pdf-compressor',
    slug: '/tools/tnpsc-pdf-compressor',
    name: 'TNPSC PDF Compressor (200KB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Tailored for Tamil Nadu PSC Group 1, 2, 4 and VAO One Time Registration certificate uploads.',
    badge: 'TNPSC OTR',
    examTags: ['TNPSC', 'Group 4', 'Group 2', 'VAO'],
    featuredInNav: false,
    priorityOrder: 7,
  },
  {
    id: 'upsc-pdf-compressor',
    slug: '/tools/upsc-pdf-compressor',
    name: 'UPSC PDF Compressor (300KB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Complies with UPSC Online Recruitment Application (ORA) 300KB single PDF limits.',
    badge: 'UPSC ORA',
    examTags: ['UPSC', 'NDA', 'CDS', 'Civil Services'],
    featuredInNav: false,
    priorityOrder: 8,
  },
  {
    id: 'ssc-pdf-compressor',
    slug: '/tools/ssc-pdf-compressor',
    name: 'SSC PDF Compressor',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Optimized for SSC CGL, CHSL, MTS, and CPO certificate verification uploads.',
    badge: 'SSC CGL/CHSL',
    examTags: ['SSC', 'CGL', 'CHSL', 'MTS', 'GD Constable'],
    featuredInNav: false,
    priorityOrder: 9,
  },

  // -------------------------------------------------------------
  // Category 2: Exam Photo & Signature Resizers
  // -------------------------------------------------------------
  {
    id: 'ssc-photo-resizer',
    slug: '/tools/ssc-photo-signature-resizer',
    name: 'SSC Photo & Signature Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Photo (20-50KB, 3.5×4.5cm) and Signature (10-20KB, 4.0×2.0cm) with bi-directional padding.',
    badge: 'POPULAR',
    examTags: ['SSC CGL', 'CHSL', 'MTS', 'GD', 'Delhi Police'],
    featuredInNav: true,
    priorityOrder: 10,
    authorityLogo: '/logos/ssc.png',
    authorityName: 'Staff Selection Commission',
  },
  {
    id: 'upsc-photo-resizer',
    slug: '/tools/upsc-photo-signature-resizer',
    name: 'UPSC Photo & Signature Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Exact 350×350 to 1000×1000 px sizing with candidate Name & 10-day Date of Photo banner.',
    badge: 'DOP BANNER',
    examTags: ['UPSC CSE', 'NDA', 'CDS', 'IES', 'EPFO'],
    featuredInNav: true,
    priorityOrder: 11,
    authorityLogo: '/logos/upsc.png',
    authorityName: 'UPSC Civil Services',
  },
  {
    id: 'rrb-photo-resizer',
    slug: '/tools/rrb-photo-signature-resizer',
    name: 'Railway RRB Photo & Signature Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Official Railway Recruitment Board rules: 320×240 px photo (20-50KB) & 160×80 px signature (10-40KB).',
    badge: 'RAILWAY PRESET',
    examTags: ['RRB NTPC', 'Group D', 'ALP', 'Technician', 'JE'],
    featuredInNav: true,
    priorityOrder: 12,
    authorityLogo: '/logos/rrb.svg',
    authorityName: 'Railway Recruitment Board',
  },
  {
    id: 'gate-photo-resizer',
    slug: '/tools/gate-photo-signature-resizer',
    name: 'GATE & JAM IIT GOAPS Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Mathematical 3.15:1 to 3.95:1 aspect ratio lock to prevent automatic GOAPS portal rejection.',
    badge: 'GOAPS RATIO LOCK',
    examTags: ['GATE', 'IIT JAM', 'IIT GOAPS', 'M.Tech'],
    featuredInNav: true,
    priorityOrder: 13,
  },
  {
    id: 'neet-photo-resizer',
    slug: '/tools/neet-photo-signature-resizer',
    name: 'NEET Postcard (4"×6") & Photo Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Postcard size (4×6 inch, 50-300KB), passport photo, and left thumb impression for NTA NEET UG.',
    badge: 'NTA NEET',
    examTags: ['NEET UG', 'NTA', 'Medical', 'AIIMS', 'JIPMER'],
    featuredInNav: true,
    priorityOrder: 14,
    authorityLogo: '/logos/nta.svg',
    authorityName: 'NTA NEET India',
  },
  {
    id: 'ibps-photo-resizer',
    slug: '/tools/ibps-photo-signature-resizer',
    name: 'IBPS & Bank Exam Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'All 4 mandatory banking uploads: Passport Photo, Signature, Left Thumb Impression & Handwritten Declaration.',
    badge: 'BANKING SUITE',
    examTags: ['IBPS PO', 'Clerk', 'SBI PO', 'RBI', 'NABARD'],
    featuredInNav: true,
    priorityOrder: 15,
    authorityLogo: '/logos/ibps.svg',
    authorityName: 'IBPS Banking Selection',
  },
  {
    id: 'tnpsc-photo-resizer',
    slug: '/tools/tnpsc-photo-signature-resizer',
    name: 'TNPSC Photo & Signature Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Generates compliant 20-50KB photo with candidate name & date strip + 10-20KB signature.',
    badge: 'TNPSC OTR',
    examTags: ['TNPSC', 'Group 1', 'Group 4', 'VAO'],
    featuredInNav: true,
    priorityOrder: 16,
    authorityLogo: '/logos/tnpsc.svg',
    authorityName: 'TNPSC Tamil Nadu',
  },
  {
    id: 'compress-image-20kb',
    slug: '/tools/compress-image-to-20kb',
    name: 'Compress Image to 20KB (Signature)',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Strict signature compressor for exams mandating files strictly between 10KB and 20KB.',
    badge: 'SIGNATURE 20KB',
    examTags: ['UPSC', 'SSC', 'State PSC', 'Judiciary'],
    featuredInNav: false,
    priorityOrder: 17,
  },
  {
    id: 'compress-image-50kb',
    slug: '/tools/compress-image-to-50kb',
    name: 'Compress Image to 50KB (Photo)',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Reduces high-resolution smartphone selfies to exact 20-50KB government portal passport limits.',
    badge: 'PHOTO 50KB',
    examTags: ['All Portals', 'SSC', 'RRB', 'Police'],
    featuredInNav: false,
    priorityOrder: 18,
  },
  {
    id: 'compress-image-exact-kb',
    slug: '/tools/compress-image-exact-kb',
    name: 'Compress Image to Exact KB/MB',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Set any exact file size target (50KB, 100KB, 200KB, 1MB) with smart quality preservation.',
    badge: 'UNIVERSAL',
    examTags: ['Universal', 'All Portals', 'Worldwide', 'Resumes'],
    featuredInNav: true,
    priorityOrder: 18.1,
  },
  {
    id: 'compress-image-to-100kb',
    slug: '/tools/compress-image-to-100kb',
    name: 'Compress Image to 100KB',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Compress photos and documents strictly under 100KB for job portals, LinkedIn, and university forms.',
    badge: '100KB TARGET',
    examTags: ['LinkedIn', 'Job Portals', 'Universities', 'Admissions'],
    featuredInNav: true,
    priorityOrder: 18.2,
  },
  {
    id: 'compress-image-to-200kb',
    slug: '/tools/compress-image-to-200kb',
    name: 'Compress Image to 200KB',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Compress certificate scans and document photos strictly under 200KB for government portals.',
    badge: '200KB TARGET',
    examTags: ['Govt Portals', 'UPSC', 'SSC', 'Certificates', 'State PSC'],
    featuredInNav: true,
    priorityOrder: 18.3,
  },
  {
    id: 'compress-image-to-1mb',
    slug: '/tools/compress-image-to-1mb',
    name: 'Compress Image to 1MB',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Compress heavy camera photos strictly under 1MB for email attachments and visa applications.',
    badge: '1MB TARGET',
    examTags: ['Email', 'Passport Seva', 'Visa', 'High-Res'],
    featuredInNav: true,
    priorityOrder: 18.4,
  },
  {
    id: 'passport-photo-maker-tool',
    slug: '/tools/passport-photo-maker',
    name: 'Passport Photo Maker Online (35×45 mm & 2×2 in)',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Create official passport size photos for Indian Passport (35x45mm, 300 DPI, 20-50KB), US Visa, UK, and Schengen with 4x6" 8-photo print sheet.',
    badge: 'FLAGSHIP PASSPORT',
    examTags: ['Passport Photo', '35x45mm', 'Passport Seva', 'MEA India', 'US Visa', 'Schengen', '4x6 Sheet'],
    featuredInNav: true,
    priorityOrder: 18.45,
  },
  {
    id: 'us-passport-photo-tool',
    slug: '/tools/us-passport-photo',
    name: 'US Passport & Visa Photo Maker (2x2")',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Create 2x2 inch (51x51 mm) official US passport and DS-160 visa photos at 300 DPI with 4x6 print sheet.',
    badge: 'US 2x2" • 300 DPI',
    examTags: ['US Passport', 'DS-160', 'DV Lottery', 'US Visa', 'Green Card', '4x6 Sheet'],
    featuredInNav: true,
    priorityOrder: 18.5,
  },
  {
    id: 'uk-passport-photo-tool',
    slug: '/tools/uk-passport-photo',
    name: 'UK Passport Photo Maker (35x45mm)',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'HM Passport Office compliant 35x45 mm British photos (29-34mm head height) with 8-copy 4x6 print sheet.',
    badge: 'UK 35x45 • HMPO',
    examTags: ['UK Passport', 'HM Passport Office', 'British Visa', '4x6 Sheet', 'Tesco Print'],
    featuredInNav: true,
    priorityOrder: 18.6,
  },
  {
    id: 'schengen-visa-photo-tool',
    slug: '/tools/schengen-visa-photo',
    name: 'Schengen Visa Photo Maker (35x45mm)',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'ICAO 9303 compliant 35x45 mm photos for 29 European states (70-80% face coverage) with 4x6 sheet.',
    badge: 'EU SCHENGEN • ICAO',
    examTags: ['Schengen Visa', 'France Visa', 'Germany Visa', 'VFS Global', 'BLS', 'ICAO 9303'],
    featuredInNav: true,
    priorityOrder: 18.7,
  },
  {
    id: 'canadian-passport-photo-tool',
    slug: '/tools/canadian-passport-photo',
    name: 'Canadian Passport & PR Photo (50x70mm)',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'IRCC compliant 50x70 mm Canadian passport, PR card, and citizenship photos with 4x6 sheet.',
    badge: 'CANADA 50x70 • IRCC',
    examTags: ['Canada Passport', 'IRCC', 'PR Card', 'Express Entry', 'Super Visa', '50x70mm'],
    featuredInNav: true,
    priorityOrder: 18.8,
  },
  {
    id: 'change-image-dpi-tool',
    slug: '/tools/change-image-dpi',
    name: 'Change Image DPI to 300 / 600 DPI',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Rewrite JFIF binary density metadata to exact 300 or 600 DPI for official portal compliance.',
    badge: '300 / 600 DPI',
    examTags: ['300 DPI', '600 DPI', 'JFIF', 'UPSC', 'SSC', 'High-Res Print', 'Resolution'],
    featuredInNav: true,
    priorityOrder: 18.9,
  },
  {
    id: 'heic-to-jpg-converter',
    slug: '/tools/heic-to-jpg',
    name: 'Apple HEIC to JPG Converter',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Batch convert iPhone & iPad .HEIC photos to universal JPG or PNG in browser RAM with 1-click ZIP export.',
    badge: '100% PRIVATE HEIC',
    examTags: ['iPhone', 'Apple HEIC', 'Batch Convert', 'Zero Upload', 'All Portals'],
    featuredInNav: true,
    priorityOrder: 18.91,
  },
  {
    id: 'heic-to-pdf-converter',
    slug: '/tools/heic-to-pdf',
    name: 'Apple HEIC to PDF Converter',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Combine multiple Apple iPhone .HEIC photos into a unified, print-ready A4 PDF document.',
    badge: 'A4 PDF MERGE',
    examTags: ['iPhone to PDF', 'A4 Merge', 'Homework', 'Receipts', 'Govt Forms'],
    featuredInNav: true,
    priorityOrder: 18.92,
  },
  {
    id: 'pan-card-photo-signature-resizer',
    slug: '/tools/pan-card-photo-signature-resizer',
    name: 'PAN Card Photo & Signature Resizer (NSDL / UTIITSL)',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Resize photo to 213x213 px (300 DPI, <30KB) and signature to 400x200 px (600 DPI, <60KB) for NSDL Form 49A.',
    badge: 'NSDL & UTIITSL',
    examTags: ['PAN Card', 'NSDL', 'UTIITSL', 'Form 49A', '213x213', '400x200', '600 DPI'],
    featuredInNav: true,
    priorityOrder: 18.93,
  },
  {
    id: 'uscis-photo-checker',
    slug: '/tools/uscis-photo-checker',
    name: 'USCIS & US Visa Photo Checker (600×600 px)',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Validate 600x600 px, 50%-69% head height ratio, 300 DPI, and generate 4x6" printable cards for US Visa & DS-160.',
    badge: 'USCIS & DS-160',
    examTags: ['USCIS', 'US Visa', 'DS-160', 'Green Card', '600x600', '300 DPI'],
    featuredInNav: true,
    priorityOrder: 18.94,
  },
  {
    id: 'dv-lottery-photo-tool',
    slug: '/tools/dv-lottery-photo-tool',
    name: 'DV Lottery Photo Tool 2026 / 2027 (Official 600×600)',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Official photo validator and cropper for the US Diversity Visa Green Card Lottery. 600x600 px @ 300 DPI < 240 KB.',
    badge: 'DV-2026/2027',
    examTags: ['DV Lottery', 'Diversity Visa', 'Green Card Lottery', 'DV-2026', 'DV-2027', '600x600'],
    featuredInNav: true,
    priorityOrder: 18.95,
  },
  {
    id: 'sign-pdf-tool',
    slug: '/tools/sign-pdf',
    name: 'Sign PDF Online Free (Draw, Type, Phone Scan)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Sign any PDF contract or form online free without account registration. Permanent vector flattening in browser RAM.',
    badge: '100% PRIVATE SIGN',
    examTags: ['Sign PDF', 'Digital Signature', 'No Sign-up', 'No Watermark', 'Agreements', 'Contracts'],
    featuredInNav: true,
    priorityOrder: 18.96,
  },
  {
    id: 'sarathi-driving-licence-resizer',
    slug: '/tools/sarathi-driving-licence-photo-signature-resizer',
    name: 'Sarathi Parivahan Driving Licence Photo & Signature Resizer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Resize photo (35x45mm, 20-50KB) and signature (20x50mm, 10-20KB) strictly for MoRTH Sarathi Parivahan DL/LL portal.',
    badge: 'SARATHI PARIVAHAN',
    examTags: ['Sarathi', 'Parivahan', 'Driving Licence', 'Learner Licence', 'RTO', 'MoRTH', '35x45mm', '20x50mm'],
    featuredInNav: true,
    priorityOrder: 18.97,
  },
  {
    id: 'epfo-passbook-resizer',
    slug: '/tools/epfo-passbook-photo-resizer',
    name: 'EPFO Cheque & Bank Passbook Photo Resizer (<500KB)',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Resize and compress cancelled cheque or bank passbook strictly between 100KB - 500KB with contrast booster for EPFO claim approval.',
    badge: 'EPFO UAN CLAIM',
    examTags: ['EPFO', 'UAN Portal', 'Provident Fund', 'Passbook Resizer', 'Cancelled Cheque', 'Under 500KB'],
    featuredInNav: true,
    priorityOrder: 18.98,
  },
  {
    id: 'marriage-biodata-maker',
    slug: '/tools/marriage-biodata-maker',
    name: 'Marriage Bio-Data Maker Online (A4 PDF & WhatsApp)',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc: 'Create elegant matrimonial biodata with 6 cultural vector themes (Vedic, Royal, Islamic, Christian). Instant watermark-free A4 PDF & WhatsApp image.',
    badge: '100% FREE BIODATA',
    examTags: ['Marriage Biodata', 'Matrimonial Profile', 'Shadi Biodata', 'Kundali', 'A4 PDF', 'WhatsApp Share', 'No Watermark'],
    featuredInNav: true,
    priorityOrder: 18.99,
  },
  {
    id: 'remove-background-hd',
    slug: '/tools/remove-background',
    name: 'Full-HD AI Background Remover (No 500px Limit)',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Remove backgrounds in 100% full original resolution (up to 4K). Export transparent PNG or custom colors. Zero limits, 100% free.',
    badge: 'FULL HD 4K',
    examTags: ['Background Remover', 'No 500px Limit', 'Transparent PNG', 'Product Photos', 'Signatures', 'Zero Upload'],
    featuredInNav: true,
    priorityOrder: 18.991,
  },
  {
    id: 'passport-white-background',
    slug: '/tools/passport-white-background',
    name: 'Convert Photo Background to White for Passport & Visa',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Convert any photo background to official pure white (#FFFFFF) or light blue with embedded 300 DPI JFIF for Passport Seva Kendra and US Visa.',
    badge: '300 DPI PASSPORT',
    examTags: ['White Background', 'Passport Photo', 'US Visa', 'Schengen Visa', '300 DPI', 'ICAO Doc 9303'],
    featuredInNav: true,
    priorityOrder: 18.992,
  },

  // -------------------------------------------------------------
  // Category 3: Degree, Marksheet & Scanner Tools
  // -------------------------------------------------------------
  {
    id: 'merge-marksheets-pdf',
    slug: '/tools/merge-marksheets-pdf',
    name: 'Multi-Marksheet to Single PDF (<1MB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Merges 1 to 12 semester marksheets into ONE continuous PDF strictly under <500KB or <1MB.',
    badge: 'NEW & EXCLUSIVE',
    examTags: ['UPSC', 'SSC', 'TNPSC', 'Banking', 'Universities'],
    featuredInNav: true,
    priorityOrder: 19,
  },
  {
    id: 'clean-document-scanner',
    slug: '/tools/clean-document-scanner',
    name: 'Clean Document Scanner & Xerox Binarizer',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Purges mobile camera shadows, corrects yellow bulb tints, and creates crisp flatbed scans.',
    badge: 'SHADOW REMOVER',
    examTags: ['All Marksheets', 'Certificates', 'ID Cards'],
    featuredInNav: true,
    priorityOrder: 20,
  },
  {
    id: 'image-to-pdf-200kb',
    slug: '/tools/image-to-pdf-200kb',
    name: 'Marksheet Image to PDF (<200KB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: '1-click convert marksheet photos directly into a compliant standard A4 PDF under 200KB.',
    badge: 'A4 FORMAT',
    examTags: ['TNPSC', 'Community Cert', 'Income Cert'],
    featuredInNav: true,
    priorityOrder: 21,
  },
  {
    id: 'image-to-pdf-300kb',
    slug: '/tools/image-to-pdf-300kb',
    name: 'Image to PDF (<300KB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Converts marksheet photos to PDF capped at 300KB for UPSC, State PSCs, and High Courts.',
    badge: 'UPSC 300KB',
    examTags: ['UPSC', 'State PSC', 'Court Filings'],
    featuredInNav: false,
    priorityOrder: 22,
  },
  {
    id: 'pdf-to-image-300dpi',
    slug: '/tools/pdf-to-image',
    name: 'PDF to High-Res 300 DPI Images',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Extracts e-Aadhaar, admit cards, and marksheets into crystal clear 300 DPI JPEG or PNG images.',
    badge: '300 DPI',
    examTags: ['e-Aadhaar', 'Admit Cards', 'Hall Tickets'],
    featuredInNav: true,
    priorityOrder: 23,
  },

  // -------------------------------------------------------------
  // Category 4: Security & Privacy Tools
  // -------------------------------------------------------------
  {
    id: 'unlock-pdf-tool',
    slug: '/tools/unlock-pdf',
    name: 'Unlock e-Aadhaar & Encrypted PDF',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc: 'Permanently remove password encryption from e-Aadhaar and Form 16 in volatile RAM memory.',
    badge: 'RAM PRIVACY',
    examTags: ['e-Aadhaar', 'Form 16', 'Bank Statement'],
    featuredInNav: true,
    priorityOrder: 24,
  },
  {
    id: 'mask-aadhaar-tool',
    slug: '/tools/mask-aadhaar',
    name: 'Official Masked Aadhaar Redactor',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc: 'Physically redacts first 8 digits (XXXX-XXXX-1234) and censors QR codes for RBI/UIDAI compliance.',
    badge: 'RBI COMPLIANT',
    examTags: ['UIDAI', 'Bank KYC', 'Exam ID Proof', 'Sim KYC'],
    featuredInNav: true,
    priorityOrder: 25,
    authorityLogo: '/logos/uidai.svg',
    authorityName: 'UIDAI & RBI Compliance',
  },

  // -------------------------------------------------------------
  // Category 5: Cyber Cafe & Studio Tools
  // -------------------------------------------------------------
  {
    id: 'passport-photo-sheet-maker',
    slug: '/tools/passport-photo-sheet-maker',
    name: 'Cyber Cafe Passport Photo Sheet Maker',
    category: 'print_cybercafe',
    categoryLabel: 'Print, PVC & Cyber Cafe Lab',
    formatTag: 'PRINT',
    shortDesc: 'Tiles 1 photo into printable 4"×6" (8 photos), 5"×7", or A4 (32 photos) sheets at 300/600 DPI with cutting lines & direct print.',
    badge: 'SAVE ₹100 • 300 DPI',
    examTags: ['Cyber Cafe', 'Studio', 'Print 4x6', 'Admit Cards', 'Epson Print'],
    featuredInNav: true,
    priorityOrder: 26,
  },
  {
    id: 'formal-attire-changer',
    slug: '/tools/formal-attire-changer',
    name: 'Instant Formal Attire & Suit Changer',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Add formal dark blazers, neckties, and professional collared shirts onto casual selfies with 1-click drag & scale snapping.',
    badge: 'STUDIO PRO • NO PHOTOSHOP',
    examTags: ['Passport Suit', 'Blazer Overlay', 'SSC Photo', 'UPSC Attire', 'Studio Formal', 'Job CV'],
    featuredInNav: true,
    priorityOrder: 27,
  },
  {
    id: 'photo-date-name-stamper',
    slug: '/tools/photo-date-name-stamper',
    name: 'Exam Photo Name & Date (DOP) Stamper',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc: 'Add candidate name and official Date of Photograph (DOP) bottom banner with SSC/UPSC 90-day validity verification.',
    badge: 'SSC & UPSC COMPLIANT',
    examTags: ['SSC CGL', 'UPSC CSE', 'DOP Strip', 'Name On Photo', 'White Banner', 'IBPS'],
    featuredInNav: true,
    priorityOrder: 28,
  },
  {
    id: 'biometric-face-aligner',
    slug: '/tools/biometric-face-aligner',
    name: 'ICAO Biometric Passport Face & Head Aligner',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Align crown to chin strictly within 70%–80% biometric frame with eye level guidelines to prevent visa/exam rejections.',
    badge: 'ICAO 9303 • 70-80% FACE',
    examTags: ['Indian Passport', 'US Visa 2x2', 'Schengen', '70-80% Head', 'Biometric Frame'],
    featuredInNav: true,
    priorityOrder: 29,
  },
  {
    id: 'stamp-size-photo-maker',
    slug: '/tools/stamp-size-photo-maker',
    name: 'Stamp Size & NEET Postcard Photo Studio',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc: 'Tile 16 stamp-size photos (20×25mm) on 4x6" card for railway/college passes or format 4x6" NTA NEET UG admit card postcards.',
    badge: '16 STAMPS FOR ₹5 • NEET',
    examTags: ['Stamp Size', '20x25mm', 'NEET Postcard', 'Railway MST Pass', 'Student ID', '4x6 Card'],
    featuredInNav: true,
    priorityOrder: 30,
  },

  // -------------------------------------------------------------
  // Category 6: Digital Verification Tools
  // -------------------------------------------------------------
  {
    id: 'digital-signature-verifier',
    slug: '/#upload-zone',
    name: 'Official DSC Signature Verifier',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc: 'Validate cryptographic PKI digital signatures on government certificates against Controller of Certifying Authorities (CCA).',
    badge: 'CCA TRUST STORE',
    examTags: ['e-Aadhaar', 'Community', 'Nativity', 'PAN', 'DigiLocker'],
    featuredInNav: true,
    priorityOrder: 27,
  },
  {
    id: 'verify-aadhaar-pdf',
    slug: '/verify-aadhaar-pdf',
    name: 'Verify e-Aadhaar Digital Signature',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc: 'Fix the yellow question mark on e-Aadhaar PDFs and convert to green checkmark.',
    badge: 'UIDAI CA',
    examTags: ['UIDAI', 'myAadhaar', 'e-KYC'],
    featuredInNav: false,
    priorityOrder: 28,
  },
  {
    id: 'signature-cleaner-extractor',
    slug: '/tools/signature-cleaner-extractor',
    name: 'Black Ink Signature Extractor & Enhancer',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc:
      'Remove ruled notebook lines, eliminate background shadows, and convert blue ballpoint ink to dense official India Black.',
    badge: 'NEW • NO RULED LINES',
    examTags: ['SSC CGL', 'UPSC CSE', 'IBPS PO', 'TNPSC', 'Black Ink', '140x60'],
    featuredInNav: true,
    priorityOrder: 29,
  },
  {
    id: 'thumb-impression-resizer',
    slug: '/tools/thumb-impression-resizer',
    name: 'Left Thumb Impression (LTI) Resizer & Sharpener',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc:
      'Sharpen friction ridges, eliminate ink smudges, and format strictly to 240×240 px (20KB–50KB) for bank & railway recruitment.',
    badge: 'NEW • BIOMETRIC RIDGE',
    examTags: ['IBPS Clerk', 'SBI PO', 'Railway RRB', 'SSC LTI', '240x240'],
    featuredInNav: true,
    priorityOrder: 30,
  },
  {
    id: 'driving-license-card-merger',
    slug: '/tools/driving-license-card-merger',
    name: 'Driving License Front & Back Merger (<200KB)',
    category: 'print_cybercafe',
    categoryLabel: 'Print, PVC & Cyber Cafe Lab',
    formatTag: 'PRINT',
    shortDesc:
      'Combine Front and Back sides of smart card DL or Vehicle RC onto single-page A4 PDF strictly under 200KB for Parivahan Sarathi.',
    badge: 'NEW • SARATHI RTO',
    examTags: ['Parivahan', 'Sarathi', 'Smart Card', 'RC', 'FASTag', '200KB'],
    featuredInNav: true,
    priorityOrder: 31,
    authorityLogo: '/logos/parivahan.svg',
    authorityName: 'Parivahan Sarathi MoRTH',
  },
  {
    id: 'photo-signature-joiner',
    slug: '/tools/photo-signature-joiner',
    name: 'Combined Photo & Signature Slip Maker',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc:
      'Join passport photo, signature, and handwritten declaration into single template slip for MP Vyapam, UPSSSC, and Kerala PSC.',
    badge: 'NEW • VYAPAM / UPSSSC',
    examTags: ['MP PEB', 'UPSSSC', 'Rajasthan RSMSSB', 'Kerala PSC', 'DOP'],
    featuredInNav: true,
    priorityOrder: 32,
  },
  {
    id: 'batch-photo-resizer',
    slug: '/tools/batch-photo-resizer',
    name: 'Bulk Batch Photo Resizer & ZIP Downloader',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc:
      'Resize, crop, and compress up to 50 applicant photos & signatures in 1 click with instant structured ZIP download. Perfect for cyber cafes and CSC centres.',
    badge: 'NEW • BATCH 50 FILES',
    examTags: ['Cyber Cafe', 'CSC Centre', 'SSC Batch', 'UPSC', 'IBPS', 'ZIP Stream'],
    featuredInNav: true,
    priorityOrder: 33,
  },
  {
    id: 'pvc-id-card-maker',
    slug: '/tools/pvc-id-card-maker',
    name: 'PVC Smart ID Card Tray Print Studio',
    category: 'print_cybercafe',
    categoryLabel: 'Print, PVC & Cyber Cafe Lab',
    formatTag: 'PRINT',
    shortDesc:
      'Extract Front & Back Aadhaar, PAN, Voter, and College ID cards into exact CR-80 plastic card dimensions (85.6mm × 53.98mm) at 300 DPI for Epson L805 trays.',
    badge: 'NEW • CR-80 EPSON L805',
    examTags: ['Epson L805', 'PVC Card', 'Aadhaar Smart Card', 'PAN Card', '300 DPI', 'A4 Lamination'],
    featuredInNav: true,
    priorityOrder: 34,
  },
  {
    id: 'self-attest-pdf',
    slug: '/tools/self-attest-pdf',
    name: 'Digital Self-Attestation & Date Stamper',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc:
      'Overlay official handwritten signature, candidate name, and attestation date directly onto certificate & marksheet PDFs without flattening vector text.',
    badge: 'NEW • VECTOR PRESERVE',
    examTags: ['Marksheet', 'Caste Certificate', 'UPSC OTR', 'SSC DV', 'Self Attested', '<200KB'],
    featuredInNav: true,
    priorityOrder: 35,
  },
  {
    id: 'exam-specifications-radar',
    slug: '/tools/specifications',
    name: 'Exam Photo & Signature Specifications Radar',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc:
      'Interactive radar with official dimensions, file size budgets (KB), background color requirements, and signature rules across 40+ Indian recruitment exams.',
    badge: '2026 OFFICIAL RULES',
    examTags: ['UPSC', 'SSC', 'IBPS', 'NEET', 'JEE', 'RRB', 'TNPSC', 'State PSC', 'Guidelines'],
    featuredInNav: true,
    priorityOrder: 36,
  },
  {
    id: 'a4-multi-card-sheet',
    slug: '/tools/a4-multi-card-sheet',
    name: 'Multi-Card A4 Gang Sheet Studio (5-in-1 ID Print)',
    category: 'print_cybercafe',
    categoryLabel: 'Print, PVC & Cyber Cafe Lab',
    formatTag: 'PRINT',
    shortDesc:
      'Tile 1 to 5 Front & Back ID cards (Aadhaar, PAN, Voter, DL) onto a single A4 glossy sheet at 300 DPI with cutting marks & lamination gutters.',
    badge: 'HOT • 5-IN-1 CYBER CAFE',
    examTags: ['Aadhaar Print', 'PAN Card', 'Voter ID', 'A4 Gang Sheet', '300 DPI', 'CSC VLE', 'Cyber Cafe'],
    featuredInNav: true,
    priorityOrder: 37,
  },
  {
    id: 'handwritten-declaration-scanner',
    slug: '/tools/handwritten-declaration-scanner',
    name: 'IBPS & SBI Handwritten Declaration Scanner (50KB–100KB)',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc:
      'Purge ruled notebook lines, whiten camera shadows, and strictly lock declaration file size between 50KB and 100KB for IBPS, SBI, and Railway RRB 2026.',
    badge: 'IBPS / SBI PRESET',
    examTags: ['IBPS PO', 'IBPS Clerk', 'SBI Clerk', 'RRB NTPC', '50KB to 100KB', 'Ruled Line Remover'],
    featuredInNav: true,
    priorityOrder: 38,
  },
  {
    id: 'aadhaar-pan-kyc-merge',
    slug: '/tools/aadhaar-pan-kyc-merge',
    name: 'Aadhaar + PAN Single PDF KYC Merger (<200KB)',
    category: 'print_cybercafe',
    categoryLabel: 'Print, PVC & Cyber Cafe Lab',
    formatTag: 'PRINT',
    shortDesc:
      'Combine Aadhaar card (front & back) and PAN card into a single A4 PDF strictly under 200KB or 500KB with 1-click RBI masking.',
    badge: 'HOT • BANK KYC',
    examTags: ['Aadhaar PAN', 'Bank KYC', 'SIM KYC', 'Single PDF', 'RBI Masked', '<200KB'],
    featuredInNav: true,
    priorityOrder: 39,
  },
  {
    id: 'affidavit-generator',
    slug: '/tools/affidavit-generator',
    name: 'Bilingual Legal Affidavit Generator (English & தமிழ்)',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc:
      'Generate sworn legal affidavits for Name Correction, DOB Discrepancy, Gap Year, and Lost Documents with 3.5" e-Stamp paper spacing.',
    badge: 'FIRST IN INDIA • தமிழ்',
    examTags: ['Affidavit', 'Name Change', 'e-Stamp Paper', 'Notary', 'Gap Year', 'Tamil Affidavit'],
    featuredInNav: true,
    priorityOrder: 40,
    authorityLogo: '/logos/emblem_of_india.svg',
    authorityName: 'Government of India / Gazette',
  },
  {
    id: 'gst-number-verifier',
    slug: '/tools/gst-number-verifier',
    name: 'GST Number (GSTIN) Instant Verifier & Lookup',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc:
      'Mathematically verify 15-digit Indian GST numbers, decode State & embedded PAN, and validate official MOD 36 checksum.',
    badge: 'MOD 36 CHECKSUM',
    examTags: ['GSTIN', 'GST Verify', 'ITC Input Credit', 'Taxpayer Search', 'State Code'],
    featuredInNav: true,
    priorityOrder: 41,
  },
  {
    id: 'salary-slip-generator',
    slug: '/tools/salary-slip-generator',
    name: 'Bilingual Salary Slip / Pay Slip Generator',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc:
      'Generate professional corporate & MSME monthly salary slips in English and Tamil with automatic EPF, ESIC, and PT calculations.',
    badge: 'LOAN & VISA READY',
    examTags: ['Salary Slip', 'Payslip Maker', 'Bank Loan Proof', 'Visa Payslip', 'EPF Calculator', 'Tamil Payslip'],
    featuredInNav: true,
    priorityOrder: 42,
  },
  {
    id: 'compress-for-whatsapp',
    slug: '/tools/compress-for-whatsapp',
    name: 'Compress PDF & Photos for WhatsApp (<500KB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc:
      'Compress heavy marksheet scans and ID cards strictly under 500KB or 200KB for fast, zero-blur WhatsApp sharing on mobile.',
    badge: 'FAST MOBILE 4G/5G',
    examTags: ['WhatsApp Compress', '<500KB', 'No Blur', 'Marksheet Share', 'Mobile 4G'],
    featuredInNav: true,
    priorityOrder: 43,
  },
  {
    id: 'income-tax-calculator-2025-26',
    slug: '/tools/income-tax-calculator-2025-26',
    name: 'Income Tax Calculator FY 2025–26 (New vs Old Regime)',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc:
      'Compare New vs Old Tax Regime with revised Union Budget slabs, ₹75,000 standard deduction, and Section 87A rebate.',
    badge: 'UNION BUDGET 2025-26',
    examTags: ['Income Tax', 'Budget 2025-26', 'New Regime', 'Standard Deduction ₹75k', 'Sec 87A'],
    featuredInNav: true,
    priorityOrder: 44,
    authorityLogo: '/logos/incometax.png',
    authorityName: 'Income Tax Department',
  },
  {
    id: 'ifsc-code-finder',
    slug: '/tools/ifsc-code-finder',
    name: 'IFSC Code & Bank Branch Finder',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc:
      'Search IFSC codes, MICR numbers, and branch addresses for all Indian banks (SBI, Indian Bank, Canara, HDFC, ICICI, PNB) with 1-click copy.',
    badge: 'RBI NEFT / RTGS',
    examTags: ['IFSC Code', 'MICR Code', 'Bank Branch', 'SBI IFSC', 'Indian Bank', 'NEFT RTGS'],
    featuredInNav: true,
    priorityOrder: 45,
  },
  // -------------------------------------------------------------
  // Phase 2: Tamil Nadu Monopoly & Academic Admission Suite
  // -------------------------------------------------------------
  {
    id: 'tnpsc-otr-compliance-kit',
    slug: '/tools/tnpsc-otr-compliance-kit',
    name: 'TNPSC OTR Photo, Signature & Thumb Compliance Kit',
    category: 'exam_photos',
    categoryLabel: 'Exam & Recruitment Photos',
    formatTag: 'IMAGE',
    shortDesc:
      'Prepare Photo (20-50KB with Name/Date), Signature (10-20KB lock), and Left Thumb (10-50KB) for TNPSC Group 1, 2, 4 & VAO OTR with 1-click batch download.',
    badge: 'TNPSC OTR BUNDLE',
    examTags: ['TNPSC', 'Group 4', 'Group 2', 'VAO', 'OTR Photo', 'TNPSC Signature', '10-20KB', 'Thumb'],
    featuredInNav: true,
    priorityOrder: 46,
    authorityLogo: '/logos/tnpsc.svg',
    authorityName: 'TNPSC Tamil Nadu',
  },
  {
    id: 'tn-marksheet-compressor',
    slug: '/tools/tn-marksheet-compressor',
    name: 'TN 10th & 12th Marksheet PDF Compressor (<200KB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc:
      'Compress Tamil Nadu SSLC (10th) and HSC (12th) marksheets strictly between 100KB and 200KB with State Board seal protection and dual-side merger.',
    badge: '100-200KB SAFE ZONE',
    examTags: ['SSLC Marksheet', '12th Marksheet', 'TNEA', 'TNGASA', 'TNPSC', 'Marksheet PDF', '200KB'],
    featuredInNav: true,
    priorityOrder: 47,
  },
  {
    id: 'tnea-cutoff-calculator',
    slug: '/tools/tnea-cutoff-calculator',
    name: 'TNEA Engineering Cutoff Calculator & Counseling Kit',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc:
      'Calculate Anna University 200 cutoff score [Maths + (Physics/2) + (Chemistry/2)], check college tier closing ranks, and estimate 7.5% Govt school fee waiver.',
    badge: 'ANNA UNIV 200',
    examTags: ['TNEA 2025', 'TNEA Cutoff', 'Anna University', 'Engineering Cutoff', '7.5 Quota', 'First Graduate'],
    featuredInNav: true,
    priorityOrder: 48,
  },
  {
    id: 'pstm-certificate-generator',
    slug: '/tools/pstm-certificate-generator',
    name: 'Official Bilingual PSTM Certificate Generator (G.O. Ms. No. 82)',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc:
      'Generate statutory Tamil & English PSTM certificate for 20% TNPSC horizontal reservation with school letterhead top clearance and clean legal printout.',
    badge: '20% TNPSC QUOTA',
    examTags: ['PSTM', 'GO 82', 'Tamil Medium', 'TNPSC Reservation', 'School Certificate', 'Group 4'],
    featuredInNav: true,
    priorityOrder: 49,
  },
  {
    id: 'aadhaar-front-back-pdf',
    slug: '/tools/aadhaar-front-back-pdf',
    name: 'Aadhaar Front + Back Single Page PDF Merger (<200KB)',
    category: 'print_cybercafe',
    categoryLabel: 'Print, PVC & Cyber Cafe Lab',
    formatTag: 'PRINT',
    shortDesc:
      'Merge Front and Back sides of Aadhaar card onto single A4 page with UIDAI 8-digit masking, photocopy Xerox mode, and self-attestation box.',
    badge: 'TOP SEARCHED',
    examTags: ['Aadhaar Front Back', 'Aadhaar Both Sides', 'Aadhaar Single Page', 'Masked Aadhaar', '200KB PDF'],
    featuredInNav: true,
    priorityOrder: 50,
  },
  {
    id: 'tn-esevai-certificate-prep',
    slug: '/tools/tn-esevai-certificate-prep',
    name: 'TN e-Sevai Revenue Certificate PDF Optimizer (<200KB)',
    category: 'pdf_tools',
    categoryLabel: 'PDF Utilities & Compressors',
    formatTag: 'PDF',
    shortDesc:
      'Optimize Community, Nativity, Income, and First Graduate certificates strictly under 200KB with Tahsildar digital signature QR code sharpness lock.',
    badge: 'E-SEVAI <200KB',
    examTags: ['e-Sevai', 'Community Certificate', 'Nativity', 'First Graduate', 'Tahsildar QR', 'TNPSC Upload'],
    featuredInNav: true,
    priorityOrder: 51,
  },
  {
    id: 'college-admission-photo-maker',
    slug: '/tools/college-admission-photo-maker',
    name: 'College Admission & Exam Photo Sheet Studio',
    category: 'passport_visa',
    categoryLabel: 'Passport & Visa Photo Lab',
    formatTag: 'IMAGE',
    shortDesc:
      'Generate 4x6" (8 photos), Combo (Passport + Stamp size), or A4 30-copy sheets at 300 DPI with name/DOP banner and scissors cut lines. Save ₹120.',
    badge: '4x6 COMBO LAB',
    examTags: ['College Photo', 'Passport Sheet 4x6', 'Stamp Size Photo', 'Admission Photo', 'Print Sheet'],
    featuredInNav: true,
    priorityOrder: 52,
  },
  {
    id: 'free-ats-resume-builder',
    slug: '/tools/free-ats-resume-builder',
    name: 'Free ATS Resume Builder & Sovereign Bio-Data Studio',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc:
      'Build 100% ATS-compliant software engineer resumes, fresher 1-page CVs, Sarkari PSU tabular biodata, and marriage biodata with real-time scoring and zero cloud storage.',
    badge: 'ATS SCORE 95+',
    examTags: ['ATS Resume', 'Tech Resume', 'Sarkari CV', 'Indian Bio-Data', 'Fresher 1-Page', 'Software Engineer Resume', 'Zero Cloud Storage'],
    featuredInNav: true,
    priorityOrder: 53,
  },
  // -------------------------------------------------------------
  // Phase 1: High-Volume Media, Image & Color Studios
  // -------------------------------------------------------------
  {
    id: 'image-optimizer-master',
    slug: '/tools/image-optimizer',
    name: 'Image Optimizer & Multi-Format Compressor',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Compress images up to 90% without quality loss. Convert to WebP & AVIF, strip Exif, and batch download as ZIP.',
    badge: 'WEBP & AVIF',
    examTags: ['Image Optimizer', 'WebP Compressor', 'AVIF Converter', 'Batch Compress', 'Strip Exif', 'Web Speed'],
    featuredInNav: true,
    priorityOrder: 54,
  },
  {
    id: 'image-converter-matrix',
    slug: '/tools/image-converter',
    name: 'Universal Image Format Converter',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Convert photos between PNG, JPG, WebP, Favicon ICO, BMP, and GIF with multi-size icon bundling.',
    badge: 'MULTI-RES ICO',
    examTags: ['PNG to JPG', 'WebP to PNG', 'Favicon ICO', 'Image Converter', 'Batch Convert'],
    featuredInNav: true,
    priorityOrder: 55,
  },
  {
    id: 'youtube-thumbnail-downloader-tool',
    slug: '/tools/youtube-thumbnail-downloader',
    name: 'YouTube Thumbnail Downloader HD/4K',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Download YouTube video covers in Full HD 1080p (maxresdefault), 4K, 480p, and WebP formats.',
    badge: '1080P FULL HD',
    examTags: ['YouTube Thumbnail', 'YouTube Shorts Cover', 'Maxresdefault', 'HD Thumbnail Downloader'],
    featuredInNav: true,
    priorityOrder: 56,
  },
  {
    id: 'signature-generator-studio',
    slug: '/tools/signature-generator',
    name: 'Digital Signature Generator Studio',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc: 'Create electronic signatures in 12+ calligraphy fonts, draw with smooth ink, or clean paper photo scans into transparent PNG.',
    badge: 'TRANSPARENT PNG',
    examTags: ['Digital Signature', 'Calligraphy Signature', 'Draw Signature', 'E-Sign PDF', 'Transparent Signature'],
    featuredInNav: true,
    priorityOrder: 57,
  },
  {
    id: 'color-picker-studio',
    slug: '/tools/color-picker',
    name: 'Modern Color Picker & Palette Studio',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Interactive color picker and palette extractor. Real-time conversion across HEX, RGB, HSL, CMYK, and WCAG contrast check.',
    badge: 'WCAG AAA',
    examTags: ['Color Picker', 'HEX to RGB', 'RGB to HSL', 'Palette Extractor', 'WCAG Contrast Checker'],
    featuredInNav: true,
    priorityOrder: 58,
  },
  {
    id: 'color-converter-tool',
    slug: '/tools/color-converter',
    name: 'Color Converter Matrix (8 Formats)',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Convert color codes across 8 universal standards: HEX, HEXA, RGB, RGBA, HSL, HSLA, HSV, and CMYK.',
    badge: '8 FORMATS',
    examTags: ['Color Converter', 'HEX to CMYK', 'RGB to HEX', 'CSS Color Codes'],
    featuredInNav: false,
    priorityOrder: 59,
  },
  {
    id: 'png-to-jpg-tool',
    slug: '/tools/png-to-jpg',
    name: 'PNG to JPG Converter',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Convert transparent PNG images to JPG with white background leveling and quality tuning.',
    badge: 'FAST CONVERT',
    examTags: ['PNG to JPG', 'Convert PNG', 'JPEG Converter'],
    featuredInNav: false,
    priorityOrder: 60,
  },
  {
    id: 'jpg-to-png-tool',
    slug: '/tools/jpg-to-png',
    name: 'JPG to PNG Converter',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Convert compressed JPG/JPEG files to lossless uncompressed 24-bit PNG format.',
    badge: 'LOSSLESS',
    examTags: ['JPG to PNG', 'JPEG to PNG', 'Lossless PNG'],
    featuredInNav: false,
    priorityOrder: 61,
  },
  {
    id: 'png-to-webp-tool',
    slug: '/tools/png-to-webp',
    name: 'PNG to WebP Converter',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Convert PNG graphics to next-gen WebP format with 80% compression and transparency preservation.',
    badge: 'NEXT-GEN',
    examTags: ['PNG to WebP', 'WebP Converter', 'PageSpeed Optimizer'],
    featuredInNav: false,
    priorityOrder: 62,
  },
  {
    id: 'webp-to-png-tool',
    slug: '/tools/webp-to-png',
    name: 'WebP to PNG Converter',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Convert WebP images to universal PNG format for Photoshop and legacy image editors.',
    badge: 'ALPHA PRESERVE',
    examTags: ['WebP to PNG', 'Unpack WebP', 'Transparent PNG'],
    featuredInNav: false,
    priorityOrder: 63,
  },
  {
    id: 'png-to-ico-tool',
    slug: '/tools/png-to-ico',
    name: 'PNG to Favicon ICO Generator',
    category: 'media_studio',
    categoryLabel: 'Image & Media Studio',
    formatTag: 'IMAGE',
    shortDesc: 'Generate genuine multi-resolution Windows favicon.ico files packing 16x16, 32x32, and 48x48 frames.',
    badge: 'FAVICON.ICO',
    examTags: ['PNG to ICO', 'Favicon Generator', 'Multi-Res Favicon', 'Windows Icon'],
    featuredInNav: false,
    priorityOrder: 64,
  },
  // -------------------------------------------------------------
  // Phase 2: Communication, Deep Links & QR Lab
  // -------------------------------------------------------------
  {
    id: 'whatsapp-link-generator-tool',
    slug: '/tools/whatsapp-link-generator',
    name: 'WhatsApp Direct Link & QR Generator',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Create wa.me direct chat links with pre-filled messages, live mobile simulator, and printable high-res QR codes.',
    badge: 'WA.ME QR',
    examTags: ['WhatsApp Link', 'wa.me generator', 'WhatsApp QR', 'Click to Chat', 'Business WhatsApp'],
    featuredInNav: true,
    priorityOrder: 65,
  },
  {
    id: 'qr-code-generator-studio',
    slug: '/tools/qr-code-generator',
    name: 'Custom QR Code Generator with Logo',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Create high-res QR codes for Wi-Fi auto-connect, URLs, UPI payments, and vCards with custom colors & logo embedding.',
    badge: '300 DPI VECTOR',
    examTags: ['QR Code Generator', 'WiFi QR', 'UPI QR Code', 'vCard QR', 'Custom QR with Logo'],
    featuredInNav: true,
    priorityOrder: 66,
  },
  {
    id: 'qr-code-reader-tool',
    slug: '/tools/qr-code-reader',
    name: 'QR Code Reader & Camera Scanner',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Scan and decode QR codes from saved photos, gallery screenshots, or live camera stream with client-side privacy.',
    badge: 'INSTANT SCAN',
    examTags: ['QR Code Reader', 'Scan QR from Image', 'Camera QR Scanner', 'Decode QR Online'],
    featuredInNav: false,
    priorityOrder: 67,
  },
  {
    id: 'barcode-generator-studio',
    slug: '/tools/barcode-generator',
    name: 'Barcode Generator (Code 128, EAN-13, UPC)',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Generate thermal printer-ready 300 DPI barcodes in Code 128, EAN-13, UPC-A, and Code 39 with SVG and PNG export.',
    badge: 'THERMAL 300 DPI',
    examTags: ['Barcode Generator', 'Code 128', 'EAN 13', 'UPC Barcode', 'Shipping Label Barcode'],
    featuredInNav: true,
    priorityOrder: 68,
  },
  {
    id: 'barcode-reader-tool',
    slug: '/tools/barcode-reader',
    name: 'Barcode Reader & Scanner',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Scan retail and industrial barcodes from packaging photos or camera stream with instant hardware decoding.',
    badge: '1D SCANNER',
    examTags: ['Barcode Reader', 'Scan Barcode Online', 'EAN Scanner', 'UPC Reader'],
    featuredInNav: false,
    priorityOrder: 69,
  },
  {
    id: 'utm-link-generator-tool',
    slug: '/tools/utm-link-generator',
    name: 'GA4 UTM Campaign Link Builder',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Build clean, trackable Google Analytics 4 (GA4) campaign URLs with lowercase sanitation and campaign QR codes.',
    badge: 'GA4 TRACKING',
    examTags: ['UTM Builder', 'GA4 Link Builder', 'Campaign URL Maker', 'UTM Generator'],
    featuredInNav: false,
    priorityOrder: 70,
  },
  {
    id: 'mailto-link-generator-tool',
    slug: '/tools/mailto-link-generator',
    name: 'Deep Mailto Link & HTML Code Generator',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Generate deep mailto links with pre-filled subject, body, CC, and BCC. Includes ready-to-use HTML button embed code.',
    badge: 'HTML EMBED',
    examTags: ['Mailto Generator', 'Email Link Builder', 'Mailto with Subject', 'Contact Button Code'],
    featuredInNav: false,
    priorityOrder: 71,
  },
  {
    id: 'paypal-link-generator-tool',
    slug: '/tools/paypal-link-generator',
    name: 'PayPal.me Payment Link & QR Generator',
    category: 'communication_qr',
    categoryLabel: 'Communication & QR Lab',
    formatTag: 'QR',
    shortDesc: 'Generate instant PayPal payment and donation links with pre-set amounts, multi-currencies, and counter checkout QR codes.',
    badge: 'PAYPAL.ME',
    examTags: ['PayPal Link Generator', 'PayPal.me Maker', 'Donation Link', 'Payment QR Code'],
    featuredInNav: false,
    priorityOrder: 72,
  },
  // -------------------------------------------------------------
  // Phase 3: Network, Domain & Security Health Checkers
  // -------------------------------------------------------------
  {
    id: 'dns-lookup-tool',
    slug: '/tools/dns-lookup',
    name: 'DNS Record Lookup & Zone Inspector',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Query authoritative DNS records (A, AAAA, MX, TXT, NS, SOA, CAA) with Cloudflare DoH and export BIND zone files.',
    badge: 'DOH RESOLVER',
    examTags: ['DNS Lookup', 'MX Records', 'SPF DKIM TXT', 'Nameserver Check', 'BIND Zone File', 'Cloudflare DoH'],
    featuredInNav: true,
    priorityOrder: 73,
  },
  {
    id: 'ssl-lookup-tool',
    slug: '/tools/ssl-lookup',
    name: 'SSL Certificate Checker & Expiry Monitor',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Inspect TLS 1.3 handshake, x509 expiration countdown, Subject Alternative Names (SANs), and cryptographic cipher suites.',
    badge: 'TLS 1.3 HANDSHAKE',
    examTags: ['SSL Lookup', 'TLS Handshake', 'SSL Expiration', 'SAN Domains', 'Cipher Suite Check'],
    featuredInNav: true,
    priorityOrder: 74,
  },
  {
    id: 'whois-lookup-tool',
    slug: '/tools/whois-lookup',
    name: 'WHOIS Lookup & Domain Age Checker',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Lookup authoritative ICANN RDAP records, registrar IANA credentials, exact domain age in years, and lifecycle expiration dates.',
    badge: 'ICANN RDAP',
    examTags: ['WHOIS Lookup', 'Domain Age Checker', 'ICANN RDAP', 'Registrar Lookup', 'Domain Expiration'],
    featuredInNav: true,
    priorityOrder: 75,
  },
  {
    id: 'ip-lookup-tool',
    slug: '/tools/ip-lookup',
    name: 'IP Address Lookup & Geolocation',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Trace any IPv4 or IPv6 address to geographic location, coordinates, ISP organization, and Autonomous System Number (ASN).',
    badge: 'GEO & ASN',
    examTags: ['IP Lookup', 'IP Geolocation', 'ASN Lookup', 'ISP Finder', 'My IP Address'],
    featuredInNav: true,
    priorityOrder: 76,
  },
  {
    id: 'reverse-ip-lookup-tool',
    slug: '/tools/reverse-ip-lookup',
    name: 'Reverse IP Lookup & Hostname Pointer',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Resolve IP addresses backward to their canonical domain hostnames and PTR records for mail server verification.',
    badge: 'PTR RECORDS',
    examTags: ['Reverse IP', 'PTR Lookup', 'rDNS Checker', 'Mail Server Verification', 'FCrDNS'],
    featuredInNav: false,
    priorityOrder: 77,
  },
  {
    id: 'http-headers-lookup-tool',
    slug: '/tools/http-headers-lookup',
    name: 'HTTP Headers Checker & Security Audit',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Inspect HTTP response headers, server latency, and audit security headers (HSTS, CSP, X-Frame-Options, Permissions-Policy).',
    badge: 'SECURITY AUDIT',
    examTags: ['HTTP Headers', 'Security Headers', 'HSTS Checker', 'CSP Validator', 'Server Response'],
    featuredInNav: true,
    priorityOrder: 78,
  },
  {
    id: 'url-redirect-checker-tool',
    slug: '/tools/url-redirect-checker',
    name: 'URL Redirect Checker & Chain Tracer',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Trace hop-by-hop redirects, audit 301 vs 302 status codes, detect cyclic redirect loops, and protect SEO link equity.',
    badge: '301 / 302 TRACE',
    examTags: ['Redirect Checker', '301 Redirect Tracer', 'Redirect Chain', 'Status Code Checker', 'SEO Redirects'],
    featuredInNav: false,
    priorityOrder: 79,
  },
  {
    id: 'meta-tags-checker-tool',
    slug: '/tools/meta-tags-checker',
    name: 'Meta Tags Checker & Social Preview',
    category: 'network_webmaster',
    categoryLabel: 'Network & Webmaster Health',
    formatTag: 'URL',
    shortDesc: 'Inspect HTML title, description, and canonical tags with live simulators for Google SERP, Open Graph, and Twitter cards.',
    badge: 'SERP & OG PREVIEW',
    examTags: ['Meta Tags Checker', 'Open Graph Preview', 'Twitter Card Validator', 'SERP Simulator', 'SEO Meta Tags'],
    featuredInNav: true,
    priorityOrder: 80,
  },
  // -------------------------------------------------------------
  // Phase 4: Developer Code, Formatter & Minifier Suite
  // -------------------------------------------------------------
  {
    id: 'json-formatter-master',
    slug: '/tools/json-formatter',
    name: 'JSON Formatter, Validator & Beautifier',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Format, validate, and minify JSON with RFC 8259 compliance, line & column syntax error pinpointing, and collapsible tree viewer.',
    badge: 'RFC 8259 PARSER',
    examTags: ['JSON Formatter', 'JSON Validator', 'JSON Beautifier', 'JSON Tree View', 'Minify JSON', 'Sort JSON Keys'],
    featuredInNav: true,
    priorityOrder: 81,
  },
  {
    id: 'json-validator-tool',
    slug: '/tools/json-validator',
    name: 'JSON Validator & Error Debugger',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Validate JSON payloads with line-and-column syntax error highlights, trailing comma alerts, and RFC 8259 checks.',
    badge: 'SYNTAX CHECKER',
    examTags: ['JSON Validator', 'JSON Lint', 'JSON Syntax Error', 'RFC 8259'],
    featuredInNav: false,
    priorityOrder: 82,
  },
  {
    id: 'json-beautifier-tool',
    slug: '/tools/json-beautifier',
    name: 'JSON Beautifier & Pretty Printer',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Pretty print single-line JSON into readable hierarchical data with custom 2-space or 4-space indentation.',
    badge: 'PRETTY PRINT',
    examTags: ['JSON Beautifier', 'Pretty Print JSON', 'Format JSON', 'Indent JSON'],
    featuredInNav: false,
    priorityOrder: 83,
  },
  {
    id: 'html-minifier-tool',
    slug: '/tools/html-minifier',
    name: 'HTML Minifier & Code Compressor',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Compress HTML documents online. Remove comments, whitespace, and empty attributes to boost Core Web Vitals.',
    badge: 'HTML COMPRESSOR',
    examTags: ['HTML Minifier', 'Compress HTML', 'HTML Optimizer', 'Core Web Vitals'],
    featuredInNav: true,
    priorityOrder: 84,
  },
  {
    id: 'css-minifier-tool',
    slug: '/tools/css-minifier',
    name: 'CSS Minifier & Stylesheet Optimizer',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Minify CSS stylesheets. Strip comments, zero units, and shorten hex colors to accelerate render times.',
    badge: 'CSS COMPRESSOR',
    examTags: ['CSS Minifier', 'Compress CSS', 'Clean CSS', 'Stylesheet Optimizer'],
    featuredInNav: true,
    priorityOrder: 85,
  },
  {
    id: 'js-minifier-tool',
    slug: '/tools/js-minifier',
    name: 'JavaScript Minifier & Compressor',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Minify JavaScript scripts safely. Strip inline comments and compress whitespace while preserving literals.',
    badge: 'JS COMPRESSOR',
    examTags: ['JavaScript Minifier', 'JS Compressor', 'Minify JS', 'Code Optimization'],
    featuredInNav: true,
    priorityOrder: 86,
  },
  {
    id: 'sql-formatter-tool',
    slug: '/tools/sql-formatter',
    name: 'SQL Formatter & Query Beautifier',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Format SQL queries with multi-dialect support (PostgreSQL, MySQL, SQLite, BigQuery, T-SQL) and UPPERCASE keywords.',
    badge: 'MULTI-DIALECT',
    examTags: ['SQL Formatter', 'Beautify SQL', 'PostgreSQL Formatter', 'MySQL Beautifier', 'Format SQL Query'],
    featuredInNav: true,
    priorityOrder: 87,
  },
  {
    id: 'markdown-to-html-tool',
    slug: '/tools/markdown-to-html',
    name: 'Markdown to HTML Converter & Editor',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Convert GitHub Flavored Markdown (GFM) to clean semantic HTML with live split-screen preview and tables.',
    badge: 'GFM STUDIO',
    examTags: ['Markdown to HTML', 'GFM Converter', 'Markdown Editor', 'HTML Export'],
    featuredInNav: true,
    priorityOrder: 88,
  },
  {
    id: 'base64-encode-tool',
    slug: '/tools/base64-encode',
    name: 'Base64 Encoder & Data URI Generator',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Encode plain text, emojis, and binary files to Base64 format with URL-safe mode and CSS/HTML Data URI generation.',
    badge: 'UTF-8 & DATA URI',
    examTags: ['Base64 Encoder', 'Text to Base64', 'File to Base64', 'Data URI Generator', 'URL-Safe Base64'],
    featuredInNav: true,
    priorityOrder: 89,
  },
  {
    id: 'base64-decode-tool',
    slug: '/tools/base64-decode',
    name: 'Base64 Decoder & Image Viewer',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Decode Base64 strings to readable text or preview decoded images with automatic URL-safe padding repairs.',
    badge: 'IMAGE VIEWER',
    examTags: ['Base64 Decoder', 'Base64 to Text', 'Base64 to Image', 'Decode Base64'],
    featuredInNav: false,
    priorityOrder: 90,
  },
  {
    id: 'url-encode-tool',
    slug: '/tools/url-encode',
    name: 'URL Encoder & Parameter Inspector',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Percent-encode URLs and query parameters with encodeURIComponent and encodeURI modes plus query string breakdown.',
    badge: 'PERCENT ENCODER',
    examTags: ['URL Encoder', 'Percent Encoding', 'encodeURIComponent', 'Query String Encoder'],
    featuredInNav: false,
    priorityOrder: 91,
  },
  {
    id: 'url-decode-tool',
    slug: '/tools/url-decode',
    name: 'URL Decoder & Query Unpacker',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Decode percent-encoded URL characters (%20, %2F, %26) back into readable text and clean URLs.',
    badge: 'PERCENT DECODER',
    examTags: ['URL Decoder', 'Decode URL', 'Percent Decoding', 'Unpack Query String'],
    featuredInNav: false,
    priorityOrder: 92,
  },
  {
    id: 'html-entity-encoder-tool',
    slug: '/tools/html-entity-encoder',
    name: 'HTML Entity Encoder & Escaper',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Escape special characters into named, decimal, and hex HTML entities to prevent Cross-Site Scripting (XSS).',
    badge: 'XSS ESCAPER',
    examTags: ['HTML Entity Encoder', 'Escape HTML', 'XSS Prevention', 'HTML Entities'],
    featuredInNav: false,
    priorityOrder: 93,
  },
  {
    id: 'html-entity-decoder-tool',
    slug: '/tools/html-entity-decoder',
    name: 'HTML Entity Decoder & Unescaper',
    category: 'developer_code',
    categoryLabel: 'Developer & Code Studio',
    formatTag: 'CODE',
    shortDesc: 'Decode named (&amp;, &lt;, &gt;), decimal, and hex HTML entities back into standard symbols.',
    badge: 'ENTITY DECODER',
    examTags: ['HTML Entity Decoder', 'Unescape HTML', 'Decode Entities', 'HTML Symbols'],
    featuredInNav: false,
    priorityOrder: 94,
  },
  // -------------------------------------------------------------
  // Phase 5: Text Manipulation, Speech & Security Generator Suite
  // -------------------------------------------------------------
  {
    id: 'text-to-speech-tool',
    slug: '/tools/text-to-speech',
    name: 'Text to Voice & Speech Converter (Free Unlimited)',
    category: 'text_speech',
    categoryLabel: 'Text, Speech & Content',
    formatTag: 'TEXT',
    shortDesc: 'Convert text into realistic AI spoken voices online with 20+ neural voices, 24kHz MP3 download, and unlimited free conversions.',
    badge: 'FREE UNLIMITED',
    examTags: [
      'Text to Voice',
      'Text to Voice Converter',
      'Text to Voice Free Unlimited',
      'Text to Voice AI Free',
      'Text to Voice Free Website',
      'Text to Voice Free Hindi',
      'Text to Voice Converter Telugu',
      'Free AI Voice Text to Speech Website',
      'Best Text to Voice Converter Website Free',
      'Text to Speech Free MP3 Download',
      'Text to Speech Free Fire',
      'Text to Voice Converter App',
      'Speech Synthesis',
      'Audio Reader',
      'ElevenLabs Free Alternative',
    ],
    featuredInNav: true,
    priorityOrder: 95,
  },
  {
    id: 'lorem-ipsum-generator-tool',
    slug: '/tools/lorem-ipsum-generator',
    name: 'Lorem Ipsum Dummy Text Generator',
    category: 'text_speech',
    categoryLabel: 'Text, Speech & Content',
    formatTag: 'TEXT',
    shortDesc: 'Generate custom placeholder text by paragraphs, sentences, words, or lists with optional HTML wrap tags.',
    badge: 'DUMMY TEXT',
    examTags: ['Lorem Ipsum Generator', 'Placeholder Text', 'Dummy Text', 'Mockup Text'],
    featuredInNav: true,
    priorityOrder: 96,
  },
  {
    id: 'case-converter-tool',
    slug: '/tools/case-converter',
    name: 'Case Converter & String Transformer',
    category: 'text_speech',
    categoryLabel: 'Text, Speech & Content',
    formatTag: 'TEXT',
    shortDesc: 'Convert text between 10+ casing formats: UPPERCASE, lowercase, Title Case, camelCase, PascalCase, snake_case, and kebab-case.',
    badge: '10-IN-1 CASING',
    examTags: ['Case Converter', 'UPPERCASE', 'lowercase', 'Title Case', 'camelCase', 'snake_case'],
    featuredInNav: true,
    priorityOrder: 97,
  },
  {
    id: 'word-counter-tool',
    slug: '/tools/word-counter',
    name: 'Word Counter & Character Statistics',
    category: 'text_speech',
    categoryLabel: 'Text, Speech & Content',
    formatTag: 'TEXT',
    shortDesc: 'Count words, characters, sentences, paragraphs, reading and speaking time in real time with keyword density analysis.',
    badge: 'TEXT ANALYTICS',
    examTags: ['Word Counter', 'Character Count', 'Reading Time', 'Keyword Density', 'Sentence Counter'],
    featuredInNav: true,
    priorityOrder: 98,
  },
  {
    id: 'text-cleaner-tool',
    slug: '/tools/text-cleaner',
    name: 'Text Cleaner & Whitespace Sanitizer',
    category: 'text_speech',
    categoryLabel: 'Text, Speech & Content',
    formatTag: 'TEXT',
    shortDesc: 'Clean messy text by collapsing duplicate spaces, removing blank lines, trimming margins, and stripping HTML tags.',
    badge: 'WHITESPACE FIXER',
    examTags: ['Text Cleaner', 'Remove Extra Spaces', 'Clean Text', 'Strip HTML', 'Whitespace Sanitizer'],
    featuredInNav: false,
    priorityOrder: 99,
  },
  {
    id: 'remove-line-breaks-tool',
    slug: '/tools/remove-line-breaks',
    name: 'Line Break Remover for Copied Text',
    category: 'text_speech',
    categoryLabel: 'Text, Speech & Content',
    formatTag: 'TEXT',
    shortDesc: 'Remove hard line breaks and carriage returns from copied PDF text and scanned documents into fluid paragraphs.',
    badge: 'LINE REMOVER',
    examTags: ['Remove Line Breaks', 'Line Break Remover', 'Fix Copied PDF Text', 'Paragraph Formatter'],
    featuredInNav: false,
    priorityOrder: 100,
  },
  {
    id: 'password-generator-tool',
    slug: '/tools/password-generator',
    name: 'Strong Password Generator CSPRNG',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc: 'Generate uncrackable, cryptographically secure random passwords using window.crypto.getRandomValues() with entropy metrics.',
    badge: 'CSPRNG ENTROPY',
    examTags: ['Password Generator', 'Strong Password', 'Random Password', 'CSPRNG', 'Secure Password'],
    featuredInNav: true,
    priorityOrder: 101,
  },
  {
    id: 'unix-timestamp-converter',
    slug: '/tools/unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc: 'Convert epoch seconds and milliseconds to human readable dates, UTC, ISO 8601, and relative expiry.',
    badge: 'EPOCH LIVE',
    examTags: ['Unix Timestamp', 'Epoch Converter', 'Epoch to Date', 'ISO 8601', 'Timestamp'],
    featuredInNav: true,
    priorityOrder: 102,
  },
  {
    id: 'unit-converter',
    slug: '/tools/unit-converter',
    name: 'Universal Unit Converter Matrix',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc: 'Instant bi-directional unit conversion across length, weight/mass, temperature, binary digital storage (1024 bytes), speed, and area.',
    badge: '7-IN-1 MATRIX',
    examTags: ['Unit Converter', 'Metric Converter', 'Measurement', 'Bytes to GB', 'Length Converter'],
    featuredInNav: true,
    priorityOrder: 103,
  },
  {
    id: 'number-to-words-converter',
    slug: '/tools/number-to-words-converter',
    name: 'Number to Words Converter',
    category: 'calculators_finance',
    categoryLabel: 'Calculators & Finance',
    formatTag: 'CALC',
    shortDesc: 'Convert numeric amounts into English words with Indian (Lakhs & Crores) and International scales for bank cheques and invoices.',
    badge: 'CHEQUE FORMAT',
    examTags: ['Number to Words', 'Cheque Words', 'Lakhs and Crores', 'Rupees in Words', 'Invoice'],
    featuredInNav: true,
    priorityOrder: 104,
  },
  {
    id: 'hash-generator',
    slug: '/tools/hash-generator',
    name: 'Cryptographic Hash Generator',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc: 'Generate SHA-256, SHA-512, MD5, SHA-384, and SHA-1 hashes directly in-browser. Verify file integrity checksums with zero server uploads.',
    badge: 'WEB CRYPTO',
    examTags: ['SHA256 Generator', 'MD5 Hash', 'File Checksum', 'SHA512', 'Cryptographic Hash'],
    featuredInNav: true,
    priorityOrder: 105,
  },
  {
    id: 'uuid-generator',
    slug: '/tools/uuid-generator',
    name: 'UUID / GUID v4 Generator',
    category: 'security_identity',
    categoryLabel: 'Security, Hash & Identity',
    formatTag: 'SECURITY',
    shortDesc: 'Generate cryptographically random RFC 4122 Version 4 UUIDs and Microsoft GUIDs in bulk with JSON and TXT export.',
    badge: 'RFC 4122',
    examTags: ['UUID Generator', 'GUID Generator', 'UUID v4', 'Random UUID', 'RFC 4122'],
    featuredInNav: true,
    priorityOrder: 106,
  },
];

/** Canonical category matcher bridging legacy and modern 11-category taxonomy */
export function normalizeCategory(cat: string): string {
  if (cat === 'pdf_compressor' || cat === 'marksheet_scanner' || cat === 'pdf_tools') return 'pdf_tools';
  if (cat === 'photo_signature' || cat === 'photo_image') return 'exam_photos';
  if (cat === 'cyber_cafe' || cat === 'print_share') return 'print_cybercafe';
  if (cat === 'verification' || cat === 'verify') return 'security_identity';
  if (cat === 'security_privacy' || cat === 'kyc_documents') return 'security_identity';
  if (cat === 'calculators') return 'calculators_finance';
  return cat;
}

/** Helper to get all categories */
export function getAllCategories(): ToolCategory[] {
  return TOOL_CATEGORIES;
}

/** Helper to filter tools by category */
export function getToolsByCategory(category: ToolItem['category']): ToolItem[] {
  const target = normalizeCategory(category);
  return TOOLS_CATALOG.filter((t) => normalizeCategory(t.category) === target).sort(
    (a, b) => a.priorityOrder - b.priorityOrder
  );
}

/** Helper to search tools */
export function searchTools(query: string, activeCategory?: string): ToolItem[] {
  const cleanQ = query.trim().toLowerCase();
  const targetCategory = activeCategory && activeCategory !== 'all' ? normalizeCategory(activeCategory) : null;

  return TOOLS_CATALOG.filter((t) => {
    if (targetCategory && normalizeCategory(t.category) !== targetCategory) {
      return false;
    }
    if (!cleanQ) return true;

    const inName = t.name.toLowerCase().includes(cleanQ);
    const inDesc = t.shortDesc.toLowerCase().includes(cleanQ);
    const inCategory = t.categoryLabel.toLowerCase().includes(cleanQ);
    const inTags = t.examTags.some((tag) => tag.toLowerCase().includes(cleanQ));
    const inBadge = t.badge?.toLowerCase().includes(cleanQ);

    return inName || inDesc || inCategory || inTags || inBadge;
  }).sort((a, b) => a.priorityOrder - b.priorityOrder);
}

/** Helper to get featured tools for the navbar */
export function getFeaturedNavTools(): ToolItem[] {
  return TOOLS_CATALOG.filter((t) => t.featuredInNav).sort(
    (a, b) => a.priorityOrder - b.priorityOrder
  );
}
