import * as React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import {
  FileText,
  ChevronRight,
  ShieldCheck,
  Zap,
  HelpCircle,
  Sparkles,
  Printer,
  CheckCircle2,
  Languages,
  BookOpen,
} from 'lucide-react';
import AffidavitGeneratorEngine from '@/components/tools/AffidavitGeneratorEngine';
import { AdSlot } from '@/components/ads/AdSlot';

export const metadata: Metadata = {
  title: 'Bilingual Legal Affidavit Generator (English & தமிழ்) | e-Stamp Paper',
  description:
    'Generate sworn affidavits and self-declarations in English and Tamil. Standard formats for Name Correction, Date of Birth, Address Proof, Gap Year, and Lost Documents with 3.5" Non-Judicial e-Stamp paper top margins. 100% free RAM privacy.',
  alternates: {
    canonical: 'https://veriseal.in/tools/affidavit-generator',
  },
  openGraph: {
    title: 'Free Legal Affidavit Generator (English & தமிழ்) | VeriSeal',
    description:
      'Generate legally valid affidavits formatted for ₹20, ₹50, and ₹100 Non-Judicial stamp papers in English & Tamil.',
    url: 'https://veriseal.in/tools/affidavit-generator',
    siteName: 'VeriSeal',
    type: 'website',
  },
};

const STAMP_DUTY_RULES = [
  { purpose: 'Name Change / Correction', recommendedStamp: '₹20 or ₹50 Non-Judicial Stamp', attestation: 'Notary Public / Advocate' },
  { purpose: 'Date of Birth Rectification', recommendedStamp: '₹50 or ₹100 Non-Judicial Stamp', attestation: 'First Class Magistrate / Notary' },
  { purpose: 'Education Gap Year / Break', recommendedStamp: '₹20 e-Stamp or Plain A4 Paper', attestation: 'Notary Public / Self Attested' },
  { purpose: 'Lost Marksheet / Certificate', recommendedStamp: '₹50 or ₹100 Non-Judicial Stamp', attestation: 'Notary Public + Police NCR' },
  { purpose: 'Residential Address Proof', recommendedStamp: 'Plain A4 or ₹20 e-Stamp', attestation: 'Self Declaration / Gazetted Officer' },
];

const FAQS = [
  {
    question: 'Is an online generated affidavit legally valid in Indian courts and government offices?',
    answer:
      'Yes. The text generated by VeriSeal complies with standard legal drafting precedents across Indian High Courts. Once printed on the appropriate Non-Judicial Stamp Paper (or e-Stamp certificate) and signed by the deponent in the presence of an authorized Notary Public or Oath Commissioner with their official seal, it carries full legal evidentiary validity under the Indian Evidence Act.',
  },
  {
    question: 'How do I print this directly onto ₹20, ₹50, or ₹100 Non-Judicial Stamp Paper?',
    answer:
      'Select the "e-Stamp Paper (3.5\\" Gap)" mode. This automatically inserts a blank 3.5-inch header margin at the top of the A4 page, allowing you to feed your green stamp paper or electronic e-Stamp certificate directly into your office printer without overlapping the official government emblem or barcode.',
  },
  {
    question: 'Can I generate the affidavit in Tamil (தமிழ்)?',
    answer:
      'Yes! VeriSeal is the only platform in India offering verified Tamil legal phrasing (உறுதிமொழிப் பத்திரம்) for Name Correction (பெயர் திருத்தம்), Study Gap (படிப்பு இடைவெளி), and Lost Certificates (சான்றிதழ் தொலைந்தமை). Simply toggle the "தமிழ் (Tamil)" language button.',
  },
  {
    question: 'Are my personal details or affidavit statements stored on your servers?',
    answer:
      'No. 100% of the document generation runs in volatile client-side browser RAM. None of your names, family details, or identity numbers are ever saved or transmitted to cloud databases.',
  },
];

export default function AffidavitGeneratorPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebApplication',
        name: 'VeriSeal Bilingual Legal Affidavit Generator',
        url: 'https://veriseal.in/tools/affidavit-generator',
        applicationCategory: 'UtilityApplication',
        operatingSystem: 'All',
        offers: {
          '@type': 'Offer',
          price: '0.00',
          priceCurrency: 'INR',
        },
        description:
          'Generate sworn affidavits and self-declarations in English and Tamil with Non-Judicial stamp paper margins.',
      },
      {
        '@type': 'HowTo',
        name: 'How to Draft and Print an Affidavit on Stamp Paper',
        step: [
          {
            '@type': 'HowToStep',
            name: 'Select Legal Purpose',
            text: 'Choose Name Correction, DOB Discrepancy, Gap Year, or Lost Document.',
          },
          {
            '@type': 'HowToStep',
            name: 'Choose Language & Paper Mode',
            text: 'Select English or Tamil, and enable 3.5-inch e-Stamp header gap if printing on Non-Judicial stamp paper.',
          },
          {
            '@type': 'HowToStep',
            name: 'Fill Deponent Details',
            text: 'Enter your name, relation, age, residential address, and ID details.',
          },
          {
            '@type': 'HowToStep',
            name: '1-Click Print A4 PDF',
            text: 'Print directly onto stamp paper or download clean A4 PDF for notary sign.',
          },
        ],
      },
      {
        '@type': 'FAQPage',
        mainEntity: FAQS.map((faq) => ({
          '@type': 'Question',
          name: faq.question,
          acceptedAnswer: {
            '@type': 'Answer',
            text: faq.answer,
          },
        })),
      },
    ],
  };

  return (
    <div className="min-h-screen bg-background bg-dot-grid text-text-main pt-28 pb-20 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
      {/* Ambient glow */}
      <div className="absolute top-28 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[350px] bg-amber-500/10 rounded-full blur-3xl pointer-events-none -z-10" />

      {/* JSON-LD Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="max-w-7xl mx-auto space-y-8">
        {/* Breadcrumb Navigation */}
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-text-main/60">
          <Link href="/" className="hover:text-primary transition-colors font-medium">
            Home
          </Link>
          <ChevronRight className="w-3.5 h-3.5 text-text-main/30" />
          <Link href="/tools" className="hover:text-primary transition-colors font-medium">
            Legal Templates
          </Link>
          <ChevronRight className="w-3.5 h-3.5 text-text-main/30" />
          <span className="text-primary font-bold truncate">Bilingual Affidavit Generator</span>
        </nav>

        {/* Main Grid: 68% Left Focus + 32% Right Sidebar */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Left Column (68%) */}
          <div className="lg:col-span-8 space-y-10">
            {/* Header Hero */}
            <div className="space-y-4">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-amber-50 dark:bg-amber-950/40 text-amber-800 dark:text-amber-300 border border-amber-200 dark:border-amber-800">
                <Languages className="w-3.5 h-3.5 text-amber-600 dark:text-amber-400" />
                <span>First In India • Bilingual Legal Format (English + தமிழ்)</span>
              </div>
              <h1 className="text-3xl sm:text-4xl font-extrabold text-foreground tracking-tight leading-tight">
                Bilingual Legal Affidavit &amp; Self-Declaration Generator
              </h1>
              <p className="text-base text-muted-foreground leading-relaxed">
                Generate sworn legal affidavits for Name Correction, DOB Discrepancy, Education Gap Years, and Lost Marksheets. Fully formatted with 3.5&quot; top margins for ₹20, ₹50, and ₹100 Non-Judicial e-Stamp papers.
              </p>
            </div>

            {/* Privacy Badge */}
            <div className="flex items-center gap-3 p-3.5 bg-amber-500/10 border border-amber-500/20 rounded-2xl text-xs text-amber-950 dark:text-amber-200 font-medium">
              <ShieldCheck className="w-5 h-5 text-amber-600 shrink-0" />
              <span>
                <strong>Confidential In-Browser Generation:</strong> Your sensitive family details and sworn legal statements are drafted strictly inside local device RAM. Zero data is recorded or stored.
              </span>
            </div>

            {/* Core Interactive Tool Engine */}
            <AffidavitGeneratorEngine />

            {/* Stamp Duty Reference Cheatsheet */}
            <div className="bg-white dark:bg-slate-900 rounded-3xl border border-surface-darker/70 dark:border-slate-800 p-6 sm:p-8 space-y-6 shadow-sm">
              <div className="flex items-center justify-between border-b border-surface-darker/60 dark:border-slate-800 pb-4">
                <div className="flex items-center gap-2.5">
                  <BookOpen className="w-5 h-5 text-amber-600" />
                  <h3 className="text-lg font-bold text-foreground">
                    Indian Stamp Duty &amp; Notary Rules Reference
                  </h3>
                </div>
                <span className="text-xs font-semibold px-2.5 py-1 bg-amber-50 dark:bg-amber-950 text-amber-800 dark:text-amber-300 rounded-full border border-amber-200 dark:border-amber-800">
                  Legal Precedents
                </span>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs border-collapse">
                  <thead>
                    <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/60 text-slate-700 dark:text-slate-300">
                      <th className="py-2.5 px-3 font-bold">Affidavit Purpose</th>
                      <th className="py-2.5 px-3 font-bold">Stamp Paper Value</th>
                      <th className="py-2.5 px-3 font-bold">Attesting Authority</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 dark:divide-slate-800 text-slate-600 dark:text-slate-300">
                    {STAMP_DUTY_RULES.map((rule, idx) => (
                      <tr key={idx} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/40">
                        <td className="py-2.5 px-3 font-bold text-slate-900 dark:text-white flex items-center gap-2">
                          <CheckCircle2 className="w-3.5 h-3.5 text-amber-500" />
                          <span>{rule.purpose}</span>
                        </td>
                        <td className="py-2.5 px-3 font-medium text-amber-700 dark:text-amber-400">
                          {rule.recommendedStamp}
                        </td>
                        <td className="py-2.5 px-3">{rule.attestation}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* FAQ Accordion */}
            <div className="bg-white dark:bg-slate-900 rounded-3xl border border-surface-darker/70 dark:border-slate-800 p-6 sm:p-8 space-y-6 shadow-sm">
              <div className="flex items-center gap-2.5 border-b border-surface-darker/60 dark:border-slate-800 pb-4">
                <HelpCircle className="w-5 h-5 text-amber-600" />
                <h3 className="text-lg font-bold text-foreground">Frequently Asked Questions</h3>
              </div>
              <div className="space-y-4">
                {FAQS.map((faq, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/80 dark:border-slate-700/80 space-y-1.5"
                  >
                    <h4 className="font-bold text-foreground text-sm flex items-start gap-2">
                      <span className="text-amber-600 font-extrabold">Q:</span>
                      {faq.question}
                    </h4>
                    <p className="text-xs text-muted-foreground leading-relaxed pl-5">
                      {faq.answer}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right Sidebar (32%) */}
          <div className="lg:col-span-4 space-y-6">
            {/* Notary Verification Card */}
            <div className="p-6 bg-white dark:bg-slate-900 rounded-3xl border border-surface-darker/70 dark:border-slate-800 shadow-sm space-y-4">
              <h3 className="font-bold text-slate-800 dark:text-white text-sm flex items-center gap-2">
                <Zap className="w-4 h-4 text-amber-600" />
                <span>Printing On Stamp Paper</span>
              </h3>
              <div className="space-y-3 text-xs text-slate-600 dark:text-slate-300">
                <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700">
                  <div className="font-bold text-slate-800 dark:text-white">Printer Feed Direction</div>
                  <div className="text-[11px] text-slate-500 mt-0.5">
                    Insert your green stamp paper or e-Stamp certificate top-first into the manual feed tray.
                  </div>
                </div>
                <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700">
                  <div className="font-bold text-slate-800 dark:text-white">Page Scale: 100% (Actual)</div>
                  <div className="text-[11px] text-slate-500 mt-0.5">
                    Leave margins at 100% so text starts precisely 3.5 inches below the stamp header.
                  </div>
                </div>
              </div>
            </div>

            {/* Related Tools */}
            <div className="p-6 bg-white dark:bg-slate-900 rounded-3xl border border-surface-darker/70 dark:border-slate-800 shadow-sm space-y-3">
              <h3 className="font-bold text-slate-800 dark:text-white text-sm flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-amber-600" />
                <span>Related Document Tools</span>
              </h3>
              <div className="space-y-2">
                <Link
                  href="/tools/self-attest-pdf"
                  className="flex items-center justify-between p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 hover:bg-amber-50/50 dark:hover:bg-amber-950/30 border border-slate-200/80 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:text-amber-700 transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-amber-600" />
                    Digital Self-Attestation PDF
                  </span>
                  <ChevronRight className="w-4 h-4 text-slate-400" />
                </Link>
                <Link
                  href="/tools/aadhaar-pan-kyc-merge"
                  className="flex items-center justify-between p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 hover:bg-amber-50/50 dark:hover:bg-amber-950/30 border border-slate-200/80 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:text-amber-700 transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <ShieldCheck className="w-4 h-4 text-amber-600" />
                    Aadhaar + PAN Single PDF KYC
                  </span>
                  <ChevronRight className="w-4 h-4 text-slate-400" />
                </Link>
                <Link
                  href="/tools/handwritten-declaration-scanner"
                  className="flex items-center justify-between p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 hover:bg-amber-50/50 dark:hover:bg-amber-950/30 border border-slate-200/80 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:text-amber-700 transition-colors"
                >
                  <span className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-amber-600" />
                    Exam Declaration Scanner
                  </span>
                  <ChevronRight className="w-4 h-4 text-slate-400" />
                </Link>
              </div>
            </div>

            {/* Ad Space (Ostrune Exclusive) */}
            <AdSlot slot="sidebar" />
          </div>
        </div>
      </div>
    </div>
  );
}
