import { ApplianceDef, HomeProfilePreset } from './types';

export const APPLIANCES_DATABASE: ApplianceDef[] = [
  {
    id: 'ac_1_5_ton_3star',
    name: '1.5 Ton Split AC (3-Star Inverter)',
    category: 'cooling',
    defaultWattage: 1200,
    wattageRange: [800, 1600],
    typicalDailyHours: 8,
    seasonal: true,
    bEEStars: 3,
    efficientAlternative: {
      name: '1.5 Ton 5-Star AI Inverter AC (ISEER 5.2+)',
      wattage: 850,
      price: 42000,
      notes: 'Saves 350W per hour (~₹3,200/year at 8h/day). Payback in ~2.5 years over 3-star.',
      affiliateKeyword: '5 star inverter ac 1.5 ton daikin panasonic',
    },
  },
  {
    id: 'ac_1_ton_inverter',
    name: '1.0 Ton Split AC (Inverter)',
    category: 'cooling',
    defaultWattage: 950,
    wattageRange: [650, 1250],
    typicalDailyHours: 7,
    seasonal: true,
    bEEStars: 4,
    efficientAlternative: {
      name: '1.0 Ton 5-Star Heavy Duty Inverter AC',
      wattage: 700,
      price: 34000,
      notes: 'Best for small bedrooms up to 120 sq ft. Saves ₹2,100/year.',
      affiliateKeyword: '1 ton 5 star inverter ac',
    },
  },
  {
    id: 'ac_2_ton_inverter',
    name: '2.0 Ton Split AC (Large Hall)',
    category: 'cooling',
    defaultWattage: 1850,
    wattageRange: [1400, 2400],
    typicalDailyHours: 6,
    seasonal: true,
    bEEStars: 3,
    efficientAlternative: {
      name: '2.0 Ton 5-Star Dual Inverter AC',
      wattage: 1350,
      price: 54000,
      notes: 'Saves 500W per hour (~₹4,500/year) in spacious living rooms (>220 sq ft).',
      affiliateKeyword: '2 ton 5 star dual inverter ac',
    },
  },
  {
    id: 'ceiling_fan_conventional',
    name: 'Ceiling Fan (Conventional Induction)',
    category: 'cooling',
    defaultWattage: 75,
    wattageRange: [70, 80],
    typicalDailyHours: 14,
    seasonal: false,
    bEEStars: 1,
    efficientAlternative: {
      name: '28W Smart BLDC Motor Ceiling Fan',
      wattage: 28,
      price: 2899,
      notes: 'Cuts fan power by 63%. 1 fan saves ~240 units/year (₹1,800/yr). Pays for itself in 18 months!',
      affiliateKeyword: 'atomberg bldc ceiling fan 28w remote',
    },
  },
  {
    id: 'ceiling_fan_bldc',
    name: 'Ceiling Fan (BLDC Energy Saver)',
    category: 'cooling',
    defaultWattage: 28,
    wattageRange: [26, 32],
    typicalDailyHours: 14,
    seasonal: false,
    bEEStars: 5,
  },
  {
    id: 'air_cooler',
    name: 'Desert / Personal Air Cooler',
    category: 'cooling',
    defaultWattage: 180,
    wattageRange: [120, 250],
    typicalDailyHours: 8,
    seasonal: true,
  },
  {
    id: 'refrigerator_old',
    name: 'Old Refrigerator (>8 Years / Non-Inverter)',
    category: 'kitchen',
    defaultWattage: 180, // High continuous compressor cycle ~1.6 kWh/day
    wattageRange: [150, 250],
    typicalDailyHours: 24,
    seasonal: false,
    efficientAlternative: {
      name: 'New 5-Star Smart Inverter Refrigerator (260L)',
      wattage: 75, // ~0.55 kWh/day
      price: 28000,
      notes: 'Old fridge wastes ~450 units/year (₹3,400/yr). Upgrading provides massive reliability & power savings.',
      affiliateKeyword: '5 star double door inverter refrigerator samsung lg',
    },
  },
  {
    id: 'refrigerator_frost_free',
    name: 'Double Door Refrigerator (Inverter 3-5 Star)',
    category: 'kitchen',
    defaultWattage: 80,
    wattageRange: [60, 120],
    typicalDailyHours: 24,
    seasonal: false,
    bEEStars: 4,
  },
  {
    id: 'geyser_storage',
    name: 'Water Geyser (Storage 15L/25L)',
    category: 'heating',
    defaultWattage: 2000,
    wattageRange: [1500, 2500],
    typicalDailyHours: 1.5,
    seasonal: true,
    efficientAlternative: {
      name: 'Rooftop Solar Water Heater / Heat Pump',
      wattage: 0,
      price: 24000,
      notes: '100% free hot water from sun for 300+ days/year. Saves ₹5,000–₹8,000 annually.',
      affiliateKeyword: 'solar water heater 150 lpd racold',
    },
  },
  {
    id: 'geyser_instant',
    name: 'Instant Water Heater (3L)',
    category: 'heating',
    defaultWattage: 3000,
    wattageRange: [3000, 4500],
    typicalDailyHours: 0.5,
    seasonal: true,
  },
  {
    id: 'washing_machine_front',
    name: 'Front Load Washing Machine (Inverter)',
    category: 'cleaning',
    defaultWattage: 500, // Average wash cycle
    wattageRange: [300, 2000],
    typicalDailyHours: 1,
    seasonal: false,
    bEEStars: 5,
  },
  {
    id: 'washing_machine_top',
    name: 'Top Load Washing Machine',
    category: 'cleaning',
    defaultWattage: 400,
    wattageRange: [350, 500],
    typicalDailyHours: 1,
    seasonal: false,
    bEEStars: 3,
  },
  {
    id: 'television_led',
    name: '50–55" 4K Smart LED TV',
    category: 'entertainment',
    defaultWattage: 95,
    wattageRange: [75, 140],
    typicalDailyHours: 5,
    seasonal: false,
  },
  {
    id: 'water_pump_1hp',
    name: 'Water Submersible / Monoblock Pump (1.0 HP)',
    category: 'general',
    defaultWattage: 750,
    wattageRange: [700, 850],
    typicalDailyHours: 1.2,
    seasonal: false,
  },
  {
    id: 'water_purifier_ro',
    name: 'RO + UV Water Purifier',
    category: 'kitchen',
    defaultWattage: 45,
    wattageRange: [35, 60],
    typicalDailyHours: 2,
    seasonal: false,
  },
  {
    id: 'induction_cooktop',
    name: 'Induction Cooktop (1800W–2000W)',
    category: 'kitchen',
    defaultWattage: 1400,
    wattageRange: [1200, 2000],
    typicalDailyHours: 1.5,
    seasonal: false,
  },
  {
    id: 'microwave_oven',
    name: 'Microwave / Convection Oven',
    category: 'kitchen',
    defaultWattage: 1200,
    wattageRange: [800, 1600],
    typicalDailyHours: 0.4,
    seasonal: false,
  },
  {
    id: 'led_tubelight',
    name: 'LED Tube Light / Batten',
    category: 'lighting',
    defaultWattage: 20,
    wattageRange: [18, 24],
    typicalDailyHours: 6,
    seasonal: false,
  },
  {
    id: 'led_bulb',
    name: 'LED Bulb (9W–12W)',
    category: 'lighting',
    defaultWattage: 10,
    wattageRange: [9, 14],
    typicalDailyHours: 6,
    seasonal: false,
  },
  {
    id: 'laptop_charger',
    name: 'Work / Study Laptop',
    category: 'entertainment',
    defaultWattage: 65,
    wattageRange: [45, 100],
    typicalDailyHours: 8,
    seasonal: false,
  },
  {
    id: 'desktop_computer',
    name: 'Desktop PC + Dual Monitors',
    category: 'entertainment',
    defaultWattage: 250,
    wattageRange: [180, 400],
    typicalDailyHours: 6,
    seasonal: false,
  },
  {
    id: 'wifi_router',
    name: 'Wi-Fi Fiber Router + ONT Box',
    category: 'entertainment',
    defaultWattage: 12,
    wattageRange: [10, 18],
    typicalDailyHours: 24,
    seasonal: false,
  },
  {
    id: 'inverter_standby',
    name: 'Home Inverter + Battery Float Loss',
    category: 'general',
    defaultWattage: 25,
    wattageRange: [15, 40],
    typicalDailyHours: 24,
    seasonal: false,
  },
  {
    id: 'electric_iron',
    name: 'Electric Clothes Iron',
    category: 'cleaning',
    defaultWattage: 1000,
    wattageRange: [750, 1400],
    typicalDailyHours: 0.5,
    seasonal: false,
  },
];

export const PRESET_HOMES: HomeProfilePreset[] = [
  {
    id: 'preset_1bhk',
    title: '1 BHK (Bachelor / Couple)',
    bhk: '1BHK',
    city: 'Bengaluru / Pune',
    state: 'karnataka',
    familyMembers: 2,
    estimatedUnits: 145,
    appliances: [
      { instanceId: 'p1_fan1', applianceId: 'ceiling_fan_conventional', quantity: 2, wattage: 75, dailyHours: 12, category: 'cooling' },
      { instanceId: 'p1_fridge', applianceId: 'refrigerator_frost_free', quantity: 1, wattage: 70, dailyHours: 24, category: 'kitchen' },
      { instanceId: 'p1_lights', applianceId: 'led_bulb', quantity: 4, wattage: 10, dailyHours: 6, category: 'lighting' },
      { instanceId: 'p1_tube', applianceId: 'led_tubelight', quantity: 2, wattage: 20, dailyHours: 5, category: 'lighting' },
      { instanceId: 'p1_tv', applianceId: 'television_led', quantity: 1, wattage: 85, dailyHours: 4, category: 'entertainment' },
      { instanceId: 'p1_laptop', applianceId: 'laptop_charger', quantity: 1, wattage: 65, dailyHours: 8, category: 'entertainment' },
      { instanceId: 'p1_router', applianceId: 'wifi_router', quantity: 1, wattage: 12, dailyHours: 24, category: 'entertainment' },
      { instanceId: 'p1_geyser', applianceId: 'geyser_storage', quantity: 1, wattage: 2000, dailyHours: 0.8, category: 'heating' },
      { instanceId: 'p1_wm', applianceId: 'washing_machine_top', quantity: 1, wattage: 400, dailyHours: 0.6, category: 'cleaning' },
    ],
  },
  {
    id: 'preset_2bhk_chennai',
    title: '2 BHK Family of 3 (Hot Climate)',
    bhk: '2BHK',
    city: 'Chennai / Hyderabad',
    state: 'tamil_nadu',
    familyMembers: 3,
    estimatedUnits: 340,
    appliances: [
      { instanceId: 'p2_ac1', applianceId: 'ac_1_5_ton_3star', quantity: 1, wattage: 1200, dailyHours: 7, category: 'cooling' },
      { instanceId: 'p2_fan', applianceId: 'ceiling_fan_conventional', quantity: 4, wattage: 75, dailyHours: 14, category: 'cooling' },
      { instanceId: 'p2_fridge', applianceId: 'refrigerator_old', quantity: 1, wattage: 160, dailyHours: 24, category: 'kitchen' },
      { instanceId: 'p2_geyser', applianceId: 'geyser_storage', quantity: 1, wattage: 2000, dailyHours: 1.2, category: 'heating' },
      { instanceId: 'p2_wm', applianceId: 'washing_machine_top', quantity: 1, wattage: 400, dailyHours: 0.8, category: 'cleaning' },
      { instanceId: 'p2_tv', applianceId: 'television_led', quantity: 1, wattage: 95, dailyHours: 5, category: 'entertainment' },
      { instanceId: 'p2_pump', applianceId: 'water_pump_1hp', quantity: 1, wattage: 750, dailyHours: 1.0, category: 'general' },
      { instanceId: 'p2_lights', applianceId: 'led_bulb', quantity: 6, wattage: 10, dailyHours: 6, category: 'lighting' },
      { instanceId: 'p2_tubes', applianceId: 'led_tubelight', quantity: 3, wattage: 20, dailyHours: 5, category: 'lighting' },
      { instanceId: 'p2_router', applianceId: 'wifi_router', quantity: 1, wattage: 12, dailyHours: 24, category: 'entertainment' },
    ],
  },
  {
    id: 'preset_3bhk_delhi',
    title: '3 BHK Family of 4 (Summer Peak Load)',
    bhk: '3BHK',
    city: 'Delhi NCR / Mumbai',
    state: 'delhi',
    familyMembers: 4,
    estimatedUnits: 580,
    appliances: [
      { instanceId: 'p3_ac1', applianceId: 'ac_1_5_ton_3star', quantity: 2, wattage: 1200, dailyHours: 8, category: 'cooling' },
      { instanceId: 'p3_fan', applianceId: 'ceiling_fan_conventional', quantity: 5, wattage: 75, dailyHours: 15, category: 'cooling' },
      { instanceId: 'p3_fridge', applianceId: 'refrigerator_frost_free', quantity: 1, wattage: 85, dailyHours: 24, category: 'kitchen' },
      { instanceId: 'p3_geyser', applianceId: 'geyser_storage', quantity: 2, wattage: 2000, dailyHours: 1.5, category: 'heating' },
      { instanceId: 'p3_wm', applianceId: 'washing_machine_front', quantity: 1, wattage: 500, dailyHours: 1.0, category: 'cleaning' },
      { instanceId: 'p3_tv', applianceId: 'television_led', quantity: 2, wattage: 95, dailyHours: 5, category: 'entertainment' },
      { instanceId: 'p3_ro', applianceId: 'water_purifier_ro', quantity: 1, wattage: 45, dailyHours: 2.5, category: 'kitchen' },
      { instanceId: 'p3_micro', applianceId: 'microwave_oven', quantity: 1, wattage: 1200, dailyHours: 0.5, category: 'kitchen' },
      { instanceId: 'p3_pump', applianceId: 'water_pump_1hp', quantity: 1, wattage: 750, dailyHours: 1.2, category: 'general' },
      { instanceId: 'p3_lights', applianceId: 'led_bulb', quantity: 10, wattage: 10, dailyHours: 6, category: 'lighting' },
      { instanceId: 'p3_tubes', applianceId: 'led_tubelight', quantity: 5, wattage: 20, dailyHours: 6, category: 'lighting' },
      { instanceId: 'p3_router', applianceId: 'wifi_router', quantity: 1, wattage: 12, dailyHours: 24, category: 'entertainment' },
      { instanceId: 'p3_inverter', applianceId: 'inverter_standby', quantity: 1, wattage: 25, dailyHours: 24, category: 'general' },
    ],
  },
  {
    id: 'preset_villa',
    title: '4 BHK Independent House / Villa',
    bhk: 'Villa',
    city: 'Ahmedabad / Coimbatore / Chandigarh',
    state: 'gujarat',
    familyMembers: 5,
    estimatedUnits: 980,
    appliances: [
      { instanceId: 'p4_ac_hall', applianceId: 'ac_2_ton_inverter', quantity: 1, wattage: 1850, dailyHours: 6, category: 'cooling' },
      { instanceId: 'p4_ac_bed', applianceId: 'ac_1_5_ton_3star', quantity: 3, wattage: 1200, dailyHours: 8, category: 'cooling' },
      { instanceId: 'p4_fans', applianceId: 'ceiling_fan_conventional', quantity: 8, wattage: 75, dailyHours: 15, category: 'cooling' },
      { instanceId: 'p4_fridge', applianceId: 'refrigerator_frost_free', quantity: 2, wattage: 90, dailyHours: 24, category: 'kitchen' },
      { instanceId: 'p4_geyser', applianceId: 'geyser_storage', quantity: 3, wattage: 2000, dailyHours: 2.0, category: 'heating' },
      { instanceId: 'p4_wm', applianceId: 'washing_machine_front', quantity: 1, wattage: 500, dailyHours: 1.2, category: 'cleaning' },
      { instanceId: 'p4_tvs', applianceId: 'television_led', quantity: 3, wattage: 110, dailyHours: 6, category: 'entertainment' },
      { instanceId: 'p4_pump', applianceId: 'water_pump_1hp', quantity: 1, wattage: 1100, dailyHours: 1.5, category: 'general' },
      { instanceId: 'p4_ro', applianceId: 'water_purifier_ro', quantity: 1, wattage: 45, dailyHours: 3.0, category: 'kitchen' },
      { instanceId: 'p4_induction', applianceId: 'induction_cooktop', quantity: 1, wattage: 1600, dailyHours: 1.5, category: 'kitchen' },
      { instanceId: 'p4_lights', applianceId: 'led_bulb', quantity: 18, wattage: 10, dailyHours: 6, category: 'lighting' },
      { instanceId: 'p4_tubes', applianceId: 'led_tubelight', quantity: 8, wattage: 20, dailyHours: 6, category: 'lighting' },
      { instanceId: 'p4_router', applianceId: 'wifi_router', quantity: 2, wattage: 12, dailyHours: 24, category: 'entertainment' },
      { instanceId: 'p4_inverter', applianceId: 'inverter_standby', quantity: 1, wattage: 35, dailyHours: 24, category: 'general' },
    ],
  },
];
